# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from BaseClasses import ItemClassification
from typing import TypedDict, Dict, Set 


class ItemDict(TypedDict, total=False): 
    classification: ItemClassification 
    count: int 
    name: str 
    doom_type: int # Unique numerical id used to spawn the item. -1 is level item, -2 is level complete item. 
    episode: int # Relevant if that item targets a specific level, like keycard or map reveal pickup. 
    map: int 


item_table: Dict[int, ItemDict] = {
    364000: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Tazer',
             'doom_type': 2001,
             'episode': -1,
             'map': -1},
    364001: {'classification': ItemClassification.progression,
             'count': 1,
             'name': "Photon 'zooka",
             'doom_type': 2003,
             'episode': -1,
             'map': -1},
    364002: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Stick',
             'doom_type': 2004,
             'episode': -1,
             'map': -1},
    364003: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'HOIG Reznator',
             'doom_type': 2005,
             'episode': -1,
             'map': -1},
    364004: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Uzi',
             'doom_type': 2002,
             'episode': -1,
             'map': -1},
    364005: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuker',
             'doom_type': 2006,
             'episode': -1,
             'map': -1},
    364006: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cryogun',
             'doom_type': 82,
             'episode': -1,
             'map': -1},
    364007: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Valise',
             'doom_type': 8,
             'episode': -1,
             'map': -1},
    364008: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Kevlar vest',
             'doom_type': 2018,
             'episode': -1,
             'map': -1},
    364009: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Super kevlar vest',
             'doom_type': 2019,
             'episode': -1,
             'map': -1},
    364010: {'classification': ItemClassification.filler,
             'count': 0,
             'name': '007Microtel',
             'doom_type': 2023,
             'episode': -1,
             'map': -1},
    364011: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Force field',
             'doom_type': 2022,
             'episode': -1,
             'map': -1},
    364012: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'EnK blinder',
             'doom_type': 2024,
             'episode': -1,
             'map': -1},
    364013: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Centrophenoxine',
             'doom_type': 2013,
             'episode': -1,
             'map': -1},
    364014: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Body armor',
             'doom_type': 83,
             'episode': -1,
             'map': -1},
    364015: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Hypo',
             'doom_type': 2012,
             'episode': -1,
             'map': -1},
    364016: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Case of rounds',
             'doom_type': 2048,
             'episode': -1,
             'map': -1},
    364017: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Case of torpedoes',
             'doom_type': 2046,
             'episode': -1,
             'map': -1},
    364018: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Case of cartridges',
             'doom_type': 2049,
             'episode': -1,
             'map': -1},
    364019: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Molecule tank',
             'doom_type': 17,
             'episode': -1,
             'map': -1},
    364200: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'GenEmp Corp. (MAP01) - Keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 1},
    364201: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'GenEmp Corp. (MAP01) - Password',
             'doom_type': 13,
             'episode': 1,
             'map': 1},
    364202: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Tunnel Town (MAP02) - Keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 2},
    364203: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Tunnel Town (MAP02) - Password',
             'doom_type': 13,
             'episode': 1,
             'map': 2},
    364204: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Lava Annex (MAP03) - Blue Z-key',
             'doom_type': 40,
             'episode': 1,
             'map': 3},
    364205: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Lava Annex (MAP03) - Red Z-key',
             'doom_type': 38,
             'episode': 1,
             'map': 3},
    364206: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cyber Circus (MAP05) - C-key',
             'doom_type': 6,
             'episode': 1,
             'map': 5},
    364207: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Digi-Ota (MAP06) - Password',
             'doom_type': 13,
             'episode': 2,
             'map': 1},
    364208: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Digi-Ota (MAP06) - Blue Z-key',
             'doom_type': 40,
             'episode': 2,
             'map': 1},
    364209: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Great Wall (MAP07) - Password',
             'doom_type': 13,
             'episode': 2,
             'map': 2},
    364210: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hidden Fortress (MAP09) - Blue Z-key',
             'doom_type': 40,
             'episode': 2,
             'map': 4},
    364211: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Notus Us! (MAP11) - Password',
             'doom_type': 13,
             'episode': 3,
             'map': 1},
    364212: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Notus Us! (MAP11) - Keycard',
             'doom_type': 5,
             'episode': 3,
             'map': 1},
    364213: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Gothik Gauntlet (MAP12) - Keycard',
             'doom_type': 5,
             'episode': 3,
             'map': 2},
    364214: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Gothik Gauntlet (MAP12) - Password',
             'doom_type': 13,
             'episode': 3,
             'map': 2},
    364215: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Sewers (MAP13) - Blue Z-key',
             'doom_type': 40,
             'episode': 3,
             'map': 3},
    364216: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Sewers (MAP13) - Red Z-key',
             'doom_type': 38,
             'episode': 3,
             'map': 3},
    364217: {'classification': ItemClassification.progression,
             'count': 1,
             'name': "'Trode Wars (MAP14) - C-key",
             'doom_type': 6,
             'episode': 3,
             'map': 4},
    364218: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Twilight of EnKs (MAP15) - Red Z-key',
             'doom_type': 38,
             'episode': 3,
             'map': 5},
    364219: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Twilight of EnKs (MAP15) - Blue Z-key',
             'doom_type': 40,
             'episode': 3,
             'map': 5},
    364220: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Twilight of EnKs (MAP15) - Yellow Z-key',
             'doom_type': 39,
             'episode': 3,
             'map': 5},
    364221: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Desiccant Room (MAP31) - Keycard',
             'doom_type': 5,
             'episode': 4,
             'map': 1},
    364222: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Bizarro (MAP18) - Blue Z-key',
             'doom_type': 40,
             'episode': 4,
             'map': 4},
    364223: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Intruder Alert! (MAP20) - C-key',
             'doom_type': 6,
             'episode': 4,
             'map': 6},
    364400: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'GenEmp Corp. (MAP01)',
             'doom_type': -1,
             'episode': 1,
             'map': 1},
    364401: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'GenEmp Corp. (MAP01) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 1},
    364402: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'GenEmp Corp. (MAP01) - SI array',
             'doom_type': 2026,
             'episode': 1,
             'map': 1},
    364403: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Tunnel Town (MAP02)',
             'doom_type': -1,
             'episode': 1,
             'map': 2},
    364404: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Tunnel Town (MAP02) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 2},
    364405: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Tunnel Town (MAP02) - SI array',
             'doom_type': 2026,
             'episode': 1,
             'map': 2},
    364406: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Lava Annex (MAP03)',
             'doom_type': -1,
             'episode': 1,
             'map': 3},
    364407: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Lava Annex (MAP03) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 3},
    364408: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Lava Annex (MAP03) - SI array',
             'doom_type': 2026,
             'episode': 1,
             'map': 3},
    364409: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Alcatraz (MAP04)',
             'doom_type': -1,
             'episode': 1,
             'map': 4},
    364410: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Alcatraz (MAP04) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 4},
    364411: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Alcatraz (MAP04) - SI array',
             'doom_type': 2026,
             'episode': 1,
             'map': 4},
    364412: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cyber Circus (MAP05)',
             'doom_type': -1,
             'episode': 1,
             'map': 5},
    364413: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cyber Circus (MAP05) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 5},
    364414: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Cyber Circus (MAP05) - SI array',
             'doom_type': 2026,
             'episode': 1,
             'map': 5},
    364415: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Digi-Ota (MAP06)',
             'doom_type': -1,
             'episode': 2,
             'map': 1},
    364416: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Digi-Ota (MAP06) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 1},
    364417: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Digi-Ota (MAP06) - SI array',
             'doom_type': 2026,
             'episode': 2,
             'map': 1},
    364418: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Great Wall (MAP07)',
             'doom_type': -1,
             'episode': 2,
             'map': 2},
    364419: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Great Wall (MAP07) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 2},
    364420: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'The Great Wall (MAP07) - SI array',
             'doom_type': 2026,
             'episode': 2,
             'map': 2},
    364421: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Garden of Delight (MAP08)',
             'doom_type': -1,
             'episode': 2,
             'map': 3},
    364422: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Garden of Delight (MAP08) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 3},
    364423: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Garden of Delight (MAP08) - SI array',
             'doom_type': 2026,
             'episode': 2,
             'map': 3},
    364424: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hidden Fortress (MAP09)',
             'doom_type': -1,
             'episode': 2,
             'map': 4},
    364425: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hidden Fortress (MAP09) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 4},
    364426: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Hidden Fortress (MAP09) - SI array',
             'doom_type': 2026,
             'episode': 2,
             'map': 4},
    364427: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Anarchist Dream (MAP10)',
             'doom_type': -1,
             'episode': 2,
             'map': 5},
    364428: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Anarchist Dream (MAP10) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 5},
    364429: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Anarchist Dream (MAP10) - SI array',
             'doom_type': 2026,
             'episode': 2,
             'map': 5},
    364430: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Notus Us! (MAP11)',
             'doom_type': -1,
             'episode': 3,
             'map': 1},
    364431: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Notus Us! (MAP11) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 1},
    364432: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Notus Us! (MAP11) - SI array',
             'doom_type': 2026,
             'episode': 3,
             'map': 1},
    364433: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Gothik Gauntlet (MAP12)',
             'doom_type': -1,
             'episode': 3,
             'map': 2},
    364434: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Gothik Gauntlet (MAP12) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 2},
    364435: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Gothik Gauntlet (MAP12) - SI array',
             'doom_type': 2026,
             'episode': 3,
             'map': 2},
    364436: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Sewers (MAP13)',
             'doom_type': -1,
             'episode': 3,
             'map': 3},
    364437: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Sewers (MAP13) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 3},
    364438: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'The Sewers (MAP13) - SI array',
             'doom_type': 2026,
             'episode': 3,
             'map': 3},
    364439: {'classification': ItemClassification.progression,
             'count': 1,
             'name': "'Trode Wars (MAP14)",
             'doom_type': -1,
             'episode': 3,
             'map': 4},
    364440: {'classification': ItemClassification.progression,
             'count': 1,
             'name': "'Trode Wars (MAP14) - Complete",
             'doom_type': -2,
             'episode': 3,
             'map': 4},
    364441: {'classification': ItemClassification.filler,
             'count': 1,
             'name': "'Trode Wars (MAP14) - SI array",
             'doom_type': 2026,
             'episode': 3,
             'map': 4},
    364442: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Twilight of EnKs (MAP15)',
             'doom_type': -1,
             'episode': 3,
             'map': 5},
    364443: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Twilight of EnKs (MAP15) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 5},
    364444: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Twilight of EnKs (MAP15) - SI array',
             'doom_type': 2026,
             'episode': 3,
             'map': 5},
    364445: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Desiccant Room (MAP31)',
             'doom_type': -1,
             'episode': 4,
             'map': 1},
    364446: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Desiccant Room (MAP31) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 1},
    364447: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Desiccant Room (MAP31) - SI array',
             'doom_type': 2026,
             'episode': 4,
             'map': 1},
    364448: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Protean Cybex (MAP16)',
             'doom_type': -1,
             'episode': 4,
             'map': 2},
    364449: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Protean Cybex (MAP16) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 2},
    364450: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Protean Cybex (MAP16) - SI array',
             'doom_type': 2026,
             'episode': 4,
             'map': 2},
    364451: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'River of Blood (MAP17)',
             'doom_type': -1,
             'episode': 4,
             'map': 3},
    364452: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'River of Blood (MAP17) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 3},
    364453: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'River of Blood (MAP17) - SI array',
             'doom_type': 2026,
             'episode': 4,
             'map': 3},
    364454: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Bizarro (MAP18)',
             'doom_type': -1,
             'episode': 4,
             'map': 4},
    364455: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Bizarro (MAP18) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 4},
    364456: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Bizarro (MAP18) - SI array',
             'doom_type': 2026,
             'episode': 4,
             'map': 4},
    364457: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The War Rooms (MAP19)',
             'doom_type': -1,
             'episode': 4,
             'map': 5},
    364458: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The War Rooms (MAP19) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 5},
    364459: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'The War Rooms (MAP19) - SI array',
             'doom_type': 2026,
             'episode': 4,
             'map': 5},
    364460: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Intruder Alert! (MAP20)',
             'doom_type': -1,
             'episode': 4,
             'map': 6},
    364461: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Intruder Alert! (MAP20) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 6},
    364462: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Intruder Alert! (MAP20) - SI array',
             'doom_type': 2026,
             'episode': 4,
             'map': 6},
    364600: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Round capacity',
             'doom_type': 65001,
             'episode': -1,
             'map': -1},
    364601: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Cartridge capacity',
             'doom_type': 65002,
             'episode': -1,
             'map': -1},
    364602: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Molecule capacity',
             'doom_type': 65003,
             'episode': -1,
             'map': -1},
    364603: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Torpedo capacity',
             'doom_type': 65004,
             'episode': -1,
             'map': -1},
}


item_name_groups: Dict[str, Set[str]] = {
    'Ammos': {'Case of cartridges', 'Case of rounds', 'Case of torpedoes', 'Molecule tank', },
    'Capacity upgrades': {'Cartridge capacity', 'Molecule capacity', 'Round capacity', 'Torpedo capacity', 'Valise', },
    'Keys': {"'Trode Wars (MAP14) - C-key", 'Bizarro (MAP18) - Blue Z-key', 'Cyber Circus (MAP05) - C-key', 'Desiccant Room (MAP31) - Keycard', 'Digi-Ota (MAP06) - Blue Z-key', 'Digi-Ota (MAP06) - Password', 'GenEmp Corp. (MAP01) - Keycard', 'GenEmp Corp. (MAP01) - Password', 'Gothik Gauntlet (MAP12) - Keycard', 'Gothik Gauntlet (MAP12) - Password', 'Hidden Fortress (MAP09) - Blue Z-key', 'Intruder Alert! (MAP20) - C-key', 'Lava Annex (MAP03) - Blue Z-key', 'Lava Annex (MAP03) - Red Z-key', 'Notus Us! (MAP11) - Keycard', 'Notus Us! (MAP11) - Password', 'The Great Wall (MAP07) - Password', 'The Sewers (MAP13) - Blue Z-key', 'The Sewers (MAP13) - Red Z-key', 'Tunnel Town (MAP02) - Keycard', 'Tunnel Town (MAP02) - Password', 'Twilight of EnKs (MAP15) - Blue Z-key', 'Twilight of EnKs (MAP15) - Red Z-key', 'Twilight of EnKs (MAP15) - Yellow Z-key', },
    'Levels': {"'Trode Wars (MAP14)", 'Alcatraz (MAP04)', 'Anarchist Dream (MAP10)', 'Bizarro (MAP18)', 'Cyber Circus (MAP05)', 'Desiccant Room (MAP31)', 'Digi-Ota (MAP06)', 'Garden of Delight (MAP08)', 'GenEmp Corp. (MAP01)', 'Gothik Gauntlet (MAP12)', 'Hidden Fortress (MAP09)', 'Intruder Alert! (MAP20)', 'Lava Annex (MAP03)', 'Notus Us! (MAP11)', 'Protean Cybex (MAP16)', 'River of Blood (MAP17)', 'The Great Wall (MAP07)', 'The Sewers (MAP13)', 'The War Rooms (MAP19)', 'Tunnel Town (MAP02)', 'Twilight of EnKs (MAP15)', },
    'MAP01': {'GenEmp Corp. (MAP01)', },
    'MAP01 Keycard': {'GenEmp Corp. (MAP01) - Keycard', },
    'MAP01 Keys': {'GenEmp Corp. (MAP01) - Keycard', 'GenEmp Corp. (MAP01) - Password', },
    'MAP01 Map': {'GenEmp Corp. (MAP01) - SI array', },
    'MAP01 Password': {'GenEmp Corp. (MAP01) - Password', },
    'MAP01 SI': {'GenEmp Corp. (MAP01) - SI array', },
    'MAP02': {'Tunnel Town (MAP02)', },
    'MAP02 Keycard': {'Tunnel Town (MAP02) - Keycard', },
    'MAP02 Keys': {'Tunnel Town (MAP02) - Keycard', 'Tunnel Town (MAP02) - Password', },
    'MAP02 Map': {'Tunnel Town (MAP02) - SI array', },
    'MAP02 Password': {'Tunnel Town (MAP02) - Password', },
    'MAP02 SI': {'Tunnel Town (MAP02) - SI array', },
    'MAP03': {'Lava Annex (MAP03)', },
    'MAP03 Blue': {'Lava Annex (MAP03) - Blue Z-key', },
    'MAP03 Keys': {'Lava Annex (MAP03) - Blue Z-key', 'Lava Annex (MAP03) - Red Z-key', },
    'MAP03 Map': {'Lava Annex (MAP03) - SI array', },
    'MAP03 Red': {'Lava Annex (MAP03) - Red Z-key', },
    'MAP03 SI': {'Lava Annex (MAP03) - SI array', },
    'MAP04': {'Alcatraz (MAP04)', },
    'MAP04 Map': {'Alcatraz (MAP04) - SI array', },
    'MAP04 SI': {'Alcatraz (MAP04) - SI array', },
    'MAP05': {'Cyber Circus (MAP05)', },
    'MAP05 C-key': {'Cyber Circus (MAP05) - C-key', },
    'MAP05 Keys': {'Cyber Circus (MAP05) - C-key', },
    'MAP05 Map': {'Cyber Circus (MAP05) - SI array', },
    'MAP05 SI': {'Cyber Circus (MAP05) - SI array', },
    'MAP06': {'Digi-Ota (MAP06)', },
    'MAP06 Blue': {'Digi-Ota (MAP06) - Blue Z-key', },
    'MAP06 Keys': {'Digi-Ota (MAP06) - Blue Z-key', 'Digi-Ota (MAP06) - Password', },
    'MAP06 Map': {'Digi-Ota (MAP06) - SI array', },
    'MAP06 Password': {'Digi-Ota (MAP06) - Password', },
    'MAP06 SI': {'Digi-Ota (MAP06) - SI array', },
    'MAP07': {'The Great Wall (MAP07)', },
    'MAP07 Keys': {'The Great Wall (MAP07) - Password', },
    'MAP07 Map': {'The Great Wall (MAP07) - SI array', },
    'MAP07 Password': {'The Great Wall (MAP07) - Password', },
    'MAP07 SI': {'The Great Wall (MAP07) - SI array', },
    'MAP08': {'Garden of Delight (MAP08)', },
    'MAP08 Map': {'Garden of Delight (MAP08) - SI array', },
    'MAP08 SI': {'Garden of Delight (MAP08) - SI array', },
    'MAP09': {'Hidden Fortress (MAP09)', },
    'MAP09 Blue': {'Hidden Fortress (MAP09) - Blue Z-key', },
    'MAP09 Keys': {'Hidden Fortress (MAP09) - Blue Z-key', },
    'MAP09 Map': {'Hidden Fortress (MAP09) - SI array', },
    'MAP09 SI': {'Hidden Fortress (MAP09) - SI array', },
    'MAP10': {'Anarchist Dream (MAP10)', },
    'MAP10 Map': {'Anarchist Dream (MAP10) - SI array', },
    'MAP10 SI': {'Anarchist Dream (MAP10) - SI array', },
    'MAP11': {'Notus Us! (MAP11)', },
    'MAP11 Keycard': {'Notus Us! (MAP11) - Keycard', },
    'MAP11 Keys': {'Notus Us! (MAP11) - Keycard', 'Notus Us! (MAP11) - Password', },
    'MAP11 Map': {'Notus Us! (MAP11) - SI array', },
    'MAP11 Password': {'Notus Us! (MAP11) - Password', },
    'MAP11 SI': {'Notus Us! (MAP11) - SI array', },
    'MAP12': {'Gothik Gauntlet (MAP12)', },
    'MAP12 Keycard': {'Gothik Gauntlet (MAP12) - Keycard', },
    'MAP12 Keys': {'Gothik Gauntlet (MAP12) - Keycard', 'Gothik Gauntlet (MAP12) - Password', },
    'MAP12 Map': {'Gothik Gauntlet (MAP12) - SI array', },
    'MAP12 Password': {'Gothik Gauntlet (MAP12) - Password', },
    'MAP12 SI': {'Gothik Gauntlet (MAP12) - SI array', },
    'MAP13': {'The Sewers (MAP13)', },
    'MAP13 Blue': {'The Sewers (MAP13) - Blue Z-key', },
    'MAP13 Keys': {'The Sewers (MAP13) - Blue Z-key', 'The Sewers (MAP13) - Red Z-key', },
    'MAP13 Map': {'The Sewers (MAP13) - SI array', },
    'MAP13 Red': {'The Sewers (MAP13) - Red Z-key', },
    'MAP13 SI': {'The Sewers (MAP13) - SI array', },
    'MAP14': {"'Trode Wars (MAP14)", },
    'MAP14 C-key': {"'Trode Wars (MAP14) - C-key", },
    'MAP14 Keys': {"'Trode Wars (MAP14) - C-key", },
    'MAP14 Map': {"'Trode Wars (MAP14) - SI array", },
    'MAP14 SI': {"'Trode Wars (MAP14) - SI array", },
    'MAP15': {'Twilight of EnKs (MAP15)', },
    'MAP15 Blue': {'Twilight of EnKs (MAP15) - Blue Z-key', },
    'MAP15 Keys': {'Twilight of EnKs (MAP15) - Blue Z-key', 'Twilight of EnKs (MAP15) - Red Z-key', 'Twilight of EnKs (MAP15) - Yellow Z-key', },
    'MAP15 Map': {'Twilight of EnKs (MAP15) - SI array', },
    'MAP15 Red': {'Twilight of EnKs (MAP15) - Red Z-key', },
    'MAP15 SI': {'Twilight of EnKs (MAP15) - SI array', },
    'MAP15 Yellow': {'Twilight of EnKs (MAP15) - Yellow Z-key', },
    'MAP16': {'Protean Cybex (MAP16)', },
    'MAP16 Map': {'Protean Cybex (MAP16) - SI array', },
    'MAP16 SI': {'Protean Cybex (MAP16) - SI array', },
    'MAP17': {'River of Blood (MAP17)', },
    'MAP17 Map': {'River of Blood (MAP17) - SI array', },
    'MAP17 SI': {'River of Blood (MAP17) - SI array', },
    'MAP18': {'Bizarro (MAP18)', },
    'MAP18 Blue': {'Bizarro (MAP18) - Blue Z-key', },
    'MAP18 Keys': {'Bizarro (MAP18) - Blue Z-key', },
    'MAP18 Map': {'Bizarro (MAP18) - SI array', },
    'MAP18 SI': {'Bizarro (MAP18) - SI array', },
    'MAP19': {'The War Rooms (MAP19)', },
    'MAP19 Map': {'The War Rooms (MAP19) - SI array', },
    'MAP19 SI': {'The War Rooms (MAP19) - SI array', },
    'MAP20': {'Intruder Alert! (MAP20)', },
    'MAP20 C-key': {'Intruder Alert! (MAP20) - C-key', },
    'MAP20 Keys': {'Intruder Alert! (MAP20) - C-key', },
    'MAP20 Map': {'Intruder Alert! (MAP20) - SI array', },
    'MAP20 SI': {'Intruder Alert! (MAP20) - SI array', },
    'MAP31': {'Desiccant Room (MAP31)', },
    'MAP31 Keycard': {'Desiccant Room (MAP31) - Keycard', },
    'MAP31 Keys': {'Desiccant Room (MAP31) - Keycard', },
    'MAP31 Map': {'Desiccant Room (MAP31) - SI array', },
    'MAP31 SI': {'Desiccant Room (MAP31) - SI array', },
    'Powerups': {'007Microtel', 'Body armor', 'Centrophenoxine', 'EnK blinder', 'Force field', 'Kevlar vest', 'Super kevlar vest', },
    'SI arrays': {"'Trode Wars (MAP14) - SI array", 'Alcatraz (MAP04) - SI array', 'Anarchist Dream (MAP10) - SI array', 'Bizarro (MAP18) - SI array', 'Cyber Circus (MAP05) - SI array', 'Desiccant Room (MAP31) - SI array', 'Digi-Ota (MAP06) - SI array', 'Garden of Delight (MAP08) - SI array', 'GenEmp Corp. (MAP01) - SI array', 'Gothik Gauntlet (MAP12) - SI array', 'Hidden Fortress (MAP09) - SI array', 'Intruder Alert! (MAP20) - SI array', 'Lava Annex (MAP03) - SI array', 'Notus Us! (MAP11) - SI array', 'Protean Cybex (MAP16) - SI array', 'River of Blood (MAP17) - SI array', 'The Great Wall (MAP07) - SI array', 'The Sewers (MAP13) - SI array', 'The War Rooms (MAP19) - SI array', 'Tunnel Town (MAP02) - SI array', 'Twilight of EnKs (MAP15) - SI array', },
    'Weapons': {'Cryogun', 'HOIG Reznator', 'Nuker', "Photon 'zooka", 'Stick', 'Tazer', 'Uzi', },
}
