# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from typing import Dict, TypedDict, List, Set 


class LocationDict(TypedDict, total=False): 
    name: str 
    episode: int 
    map: int 
    index: int # Thing index as it is stored in the wad file. 
    doom_type: int # In case index end up unreliable, we can use doom type. Maps have often only one of each important things. 
    region: str 


location_table: Dict[int, LocationDict] = {
    365000: {'name': 'GenEmp Corp. (MAP01) - Keycard (Security Room)',
             'episode': 1,
             'map': 1,
             'index': 0,
             'doom_type': 5,
             'region': "GenEmp Corp. (MAP01) Main"},
    365001: {'name': 'GenEmp Corp. (MAP01) - Password (Upper Floor, Project Room)',
             'episode': 1,
             'map': 1,
             'index': 1,
             'doom_type': 13,
             'region': "GenEmp Corp. (MAP01) Password"},
    365002: {'name': 'GenEmp Corp. (MAP01) - SI array (Security Room)',
             'episode': 1,
             'map': 1,
             'index': 216,
             'doom_type': 2026,
             'region': "GenEmp Corp. (MAP01) Main"},
    365003: {'name': 'GenEmp Corp. (MAP01) - Kevlar vest (Security Room, Desk Switch)',
             'episode': 1,
             'map': 1,
             'index': 228,
             'doom_type': 2018,
             'region': "GenEmp Corp. (MAP01) Main"},
    365004: {'name': 'GenEmp Corp. (MAP01) - Kevlar vest (Outside)',
             'episode': 1,
             'map': 1,
             'index': 230,
             'doom_type': 2018,
             'region': "GenEmp Corp. (MAP01) Main"},
    365005: {'name': 'GenEmp Corp. (MAP01) - Kevlar vest (Security Weapons Room)',
             'episode': 1,
             'map': 1,
             'index': 243,
             'doom_type': 2018,
             'region': "GenEmp Corp. (MAP01) Keycard"},
    365006: {'name': 'GenEmp Corp. (MAP01) - Force field (Foyer)',
             'episode': 1,
             'map': 1,
             'index': 247,
             'doom_type': 2022,
             'region': "GenEmp Corp. (MAP01) Keycard"},
    365007: {'name': 'GenEmp Corp. (MAP01) - Kevlar vest (Upper Floor, Office)',
             'episode': 1,
             'map': 1,
             'index': 275,
             'doom_type': 2018,
             'region': "GenEmp Corp. (MAP01) Keycard"},
    365008: {'name': 'GenEmp Corp. (MAP01) - 007Microtel (Upper Floor, Office )',
             'episode': 1,
             'map': 1,
             'index': 276,
             'doom_type': 2023,
             'region': "GenEmp Corp. (MAP01) Keycard"},
    365009: {'name': 'GenEmp Corp. (MAP01) - Kevlar vest (Waste Treatment)',
             'episode': 1,
             'map': 1,
             'index': 339,
             'doom_type': 2018,
             'region': "GenEmp Corp. (MAP01) Password"},
    365010: {'name': 'GenEmp Corp. (MAP01) - Force field (Waste Treatment)',
             'episode': 1,
             'map': 1,
             'index': 344,
             'doom_type': 2022,
             'region': "GenEmp Corp. (MAP01) Password"},
    365011: {'name': 'GenEmp Corp. (MAP01) - Super kevlar vest (Waste Treatment)',
             'episode': 1,
             'map': 1,
             'index': 348,
             'doom_type': 2019,
             'region': "GenEmp Corp. (MAP01) Password"},
    365012: {'name': 'GenEmp Corp. (MAP01) - Kevlar vest (Waste Treatment, Ammo Room )',
             'episode': 1,
             'map': 1,
             'index': 374,
             'doom_type': 2018,
             'region': "GenEmp Corp. (MAP01) Password"},
    365013: {'name': 'GenEmp Corp. (MAP01) - 007Microtel (Train Station)',
             'episode': 1,
             'map': 1,
             'index': 410,
             'doom_type': 2023,
             'region': "GenEmp Corp. (MAP01) Password"},
    365014: {'name': 'GenEmp Corp. (MAP01) - 007Microtel 2 (Train Station)',
             'episode': 1,
             'map': 1,
             'index': 425,
             'doom_type': 2023,
             'region': "GenEmp Corp. (MAP01) Password"},
    365015: {'name': 'GenEmp Corp. (MAP01) - Super kevlar vest (Train Station)',
             'episode': 1,
             'map': 1,
             'index': 426,
             'doom_type': 2019,
             'region': "GenEmp Corp. (MAP01) Password"},
    365016: {'name': 'GenEmp Corp. (MAP01) - Tazer (Foyer)',
             'episode': 1,
             'map': 1,
             'index': 440,
             'doom_type': 2001,
             'region': "GenEmp Corp. (MAP01) Keycard"},
    365017: {'name': 'GenEmp Corp. (MAP01) - Valise (Security Weapons Room)',
             'episode': 1,
             'map': 1,
             'index': 467,
             'doom_type': 8,
             'region': "GenEmp Corp. (MAP01) Keycard"},
    365018: {'name': 'GenEmp Corp. (MAP01) - Centrophenoxine (Waste Treatment)',
             'episode': 1,
             'map': 1,
             'index': 533,
             'doom_type': 2013,
             'region': "GenEmp Corp. (MAP01) Password"},
    365019: {'name': 'GenEmp Corp. (MAP01) - Exit',
             'episode': 1,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "GenEmp Corp. (MAP01) Password"},
    365020: {'name': "Tunnel Town (MAP02) - Photon 'zooka (Curved Staircase)",
             'episode': 1,
             'map': 2,
             'index': 7,
             'doom_type': 2003,
             'region': "Tunnel Town (MAP02) Keycard"},
    365021: {'name': 'Tunnel Town (MAP02) - Keycard (Bridge)',
             'episode': 1,
             'map': 2,
             'index': 9,
             'doom_type': 5,
             'region': "Tunnel Town (MAP02) Main"},
    365022: {'name': 'Tunnel Town (MAP02) - Password (Assembly Room)',
             'episode': 1,
             'map': 2,
             'index': 79,
             'doom_type': 13,
             'region': "Tunnel Town (MAP02) Keycard"},
    365023: {'name': 'Tunnel Town (MAP02) - Super kevlar vest (North Puzzle Area)',
             'episode': 1,
             'map': 2,
             'index': 254,
             'doom_type': 2019,
             'region': "Tunnel Town (MAP02) Main"},
    365024: {'name': 'Tunnel Town (MAP02) - 007Microtel (Blackout Room)',
             'episode': 1,
             'map': 2,
             'index': 258,
             'doom_type': 2023,
             'region': "Tunnel Town (MAP02) Main"},
    365025: {'name': 'Tunnel Town (MAP02) - Kevlar vest (Blackout Room)',
             'episode': 1,
             'map': 2,
             'index': 261,
             'doom_type': 2018,
             'region': "Tunnel Town (MAP02) Main"},
    365026: {'name': 'Tunnel Town (MAP02) - SI array (Assembly Room)',
             'episode': 1,
             'map': 2,
             'index': 309,
             'doom_type': 2026,
             'region': "Tunnel Town (MAP02) Keycard"},
    365027: {'name': 'Tunnel Town (MAP02) - 007Microtel (Last Hall)',
             'episode': 1,
             'map': 2,
             'index': 405,
             'doom_type': 2023,
             'region': "Tunnel Town (MAP02) Password"},
    365028: {'name': 'Tunnel Town (MAP02) - Exit',
             'episode': 1,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "Tunnel Town (MAP02) Password"},
    365029: {'name': 'Lava Annex (MAP03) - 007Microtel (Elevator Room)',
             'episode': 1,
             'map': 3,
             'index': 6,
             'doom_type': 2023,
             'region': "Lava Annex (MAP03) Main"},
    365030: {'name': 'Lava Annex (MAP03) - Super kevlar vest (Cave Entrance)',
             'episode': 1,
             'map': 3,
             'index': 17,
             'doom_type': 2019,
             'region': "Lava Annex (MAP03) Opening"},
    365031: {'name': 'Lava Annex (MAP03) - Blue Z-key (Elevator Room)',
             'episode': 1,
             'map': 3,
             'index': 23,
             'doom_type': 40,
             'region': "Lava Annex (MAP03) Main"},
    365032: {'name': "Lava Annex (MAP03) - Photon 'zooka (Lift Shot Secret)",
             'episode': 1,
             'map': 3,
             'index': 54,
             'doom_type': 2003,
             'region': "Lava Annex (MAP03) Main"},
    365033: {'name': 'Lava Annex (MAP03) - Centrophenoxine (Android Hallway)',
             'episode': 1,
             'map': 3,
             'index': 119,
             'doom_type': 2013,
             'region': "Lava Annex (MAP03) Main"},
    365034: {'name': 'Lava Annex (MAP03) - Valise (Android Hallway)',
             'episode': 1,
             'map': 3,
             'index': 126,
             'doom_type': 8,
             'region': "Lava Annex (MAP03) Main"},
    365035: {'name': 'Lava Annex (MAP03) - Cryogun (Elevator Room)',
             'episode': 1,
             'map': 3,
             'index': 130,
             'doom_type': 82,
             'region': "Lava Annex (MAP03) Main"},
    365036: {'name': 'Lava Annex (MAP03) - Body armor (Volcano, Side Rooms)',
             'episode': 1,
             'map': 3,
             'index': 152,
             'doom_type': 83,
             'region': "Lava Annex (MAP03) Z Blue"},
    365037: {'name': 'Lava Annex (MAP03) - Red Z-key (Volcano)',
             'episode': 1,
             'map': 3,
             'index': 179,
             'doom_type': 38,
             'region': "Lava Annex (MAP03) Z Blue"},
    365038: {'name': 'Lava Annex (MAP03) - Centrophenoxine (Volcano, Side Rooms)',
             'episode': 1,
             'map': 3,
             'index': 185,
             'doom_type': 2013,
             'region': "Lava Annex (MAP03) Z Blue"},
    365039: {'name': 'Lava Annex (MAP03) - HOIG Reznator (Volcano)',
             'episode': 1,
             'map': 3,
             'index': 194,
             'doom_type': 2005,
             'region': "Lava Annex (MAP03) Z Blue"},
    365040: {'name': 'Lava Annex (MAP03) - Centrophenoxine (Volcano)',
             'episode': 1,
             'map': 3,
             'index': 253,
             'doom_type': 2013,
             'region': "Lava Annex (MAP03) Z Blue"},
    365041: {'name': 'Lava Annex (MAP03) - SI array (Volcano)',
             'episode': 1,
             'map': 3,
             'index': 254,
             'doom_type': 2026,
             'region': "Lava Annex (MAP03) Z Blue"},
    365042: {'name': 'Lava Annex (MAP03) - Centrophenoxine (South Lava Cavern)',
             'episode': 1,
             'map': 3,
             'index': 358,
             'doom_type': 2013,
             'region': "Lava Annex (MAP03) Z Red"},
    365043: {'name': 'Lava Annex (MAP03) - Exit',
             'episode': 1,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "Lava Annex (MAP03) Z Red"},
    365044: {'name': 'Alcatraz (MAP04) - Super kevlar vest (Hallway to Upper Cell Block)',
             'episode': 1,
             'map': 4,
             'index': 56,
             'doom_type': 2019,
             'region': "Alcatraz (MAP04) Main"},
    365045: {'name': 'Alcatraz (MAP04) - 007Microtel (Hallway to Upper Cell Block)',
             'episode': 1,
             'map': 4,
             'index': 57,
             'doom_type': 2023,
             'region': "Alcatraz (MAP04) Main"},
    365046: {'name': 'Alcatraz (MAP04) - 007Microtel (Lower Cell Block)',
             'episode': 1,
             'map': 4,
             'index': 58,
             'doom_type': 2023,
             'region': "Alcatraz (MAP04) Main"},
    365047: {'name': "Alcatraz (MAP04) - Photon 'zooka (Hidden Entrance)",
             'episode': 1,
             'map': 4,
             'index': 59,
             'doom_type': 2003,
             'region': "Alcatraz (MAP04) Main"},
    365048: {'name': 'Alcatraz (MAP04) - Tazer (Elevator to the Wall)',
             'episode': 1,
             'map': 4,
             'index': 95,
             'doom_type': 2001,
             'region': "Alcatraz (MAP04) Main"},
    365049: {'name': "Alcatraz (MAP04) - Photon 'zooka (Elevator to the Wall)",
             'episode': 1,
             'map': 4,
             'index': 96,
             'doom_type': 2003,
             'region': "Alcatraz (MAP04) Main"},
    365050: {'name': 'Alcatraz (MAP04) - 007Microtel (Atop the Wall)',
             'episode': 1,
             'map': 4,
             'index': 100,
             'doom_type': 2023,
             'region': "Alcatraz (MAP04) Main"},
    365051: {'name': 'Alcatraz (MAP04) - SI array (Lower Cell Block)',
             'episode': 1,
             'map': 4,
             'index': 137,
             'doom_type': 2026,
             'region': "Alcatraz (MAP04) Main"},
    365052: {'name': 'Alcatraz (MAP04) - HOIG Reznator (Mysterious Column)',
             'episode': 1,
             'map': 4,
             'index': 156,
             'doom_type': 2005,
             'region': "Alcatraz (MAP04) Main"},
    365053: {'name': 'Alcatraz (MAP04) - Super kevlar vest (Mysterious Column)',
             'episode': 1,
             'map': 4,
             'index': 186,
             'doom_type': 2019,
             'region': "Alcatraz (MAP04) Main"},
    365054: {'name': 'Alcatraz (MAP04) - Force field (Mysterious Column, Hidden Switch)',
             'episode': 1,
             'map': 4,
             'index': 202,
             'doom_type': 2022,
             'region': "Alcatraz (MAP04) Main"},
    365055: {'name': 'Alcatraz (MAP04) - Super kevlar vest (Rock Climbing)',
             'episode': 1,
             'map': 4,
             'index': 204,
             'doom_type': 2019,
             'region': "Alcatraz (MAP04) Main"},
    365056: {'name': 'Alcatraz (MAP04) - Exit',
             'episode': 1,
             'map': 4,
             'index': -1,
             'doom_type': -1,
             'region': "Alcatraz (MAP04) Main"},
    365057: {'name': 'Cyber Circus (MAP05) - HOIG Reznator (Western Side Rooms)',
             'episode': 1,
             'map': 5,
             'index': 6,
             'doom_type': 2005,
             'region': "Cyber Circus (MAP05) Main"},
    365058: {'name': 'Cyber Circus (MAP05) - Valise (Western Side Rooms, to Erratic Room)',
             'episode': 1,
             'map': 5,
             'index': 7,
             'doom_type': 8,
             'region': "Cyber Circus (MAP05) Main"},
    365059: {'name': 'Cyber Circus (MAP05) - Super kevlar vest (Sigma Room)',
             'episode': 1,
             'map': 5,
             'index': 10,
             'doom_type': 2019,
             'region': "Cyber Circus (MAP05) Sigma"},
    365060: {'name': 'Cyber Circus (MAP05) - 007Microtel (Sigma Room)',
             'episode': 1,
             'map': 5,
             'index': 11,
             'doom_type': 2023,
             'region': "Cyber Circus (MAP05) Sigma"},
    365061: {'name': 'Cyber Circus (MAP05) - Super kevlar vest (Behind Pulsar)',
             'episode': 1,
             'map': 5,
             'index': 37,
             'doom_type': 2019,
             'region': "Cyber Circus (MAP05) Main"},
    365062: {'name': 'Cyber Circus (MAP05) - 007Microtel (Behind Pulsar)',
             'episode': 1,
             'map': 5,
             'index': 38,
             'doom_type': 2023,
             'region': "Cyber Circus (MAP05) Main"},
    365063: {'name': "Cyber Circus (MAP05) - Photon 'zooka (Behind Pulsar)",
             'episode': 1,
             'map': 5,
             'index': 39,
             'doom_type': 2003,
             'region': "Cyber Circus (MAP05) Main"},
    365064: {'name': 'Cyber Circus (MAP05) - C-key (Erratic Room)',
             'episode': 1,
             'map': 5,
             'index': 41,
             'doom_type': 6,
             'region': "Cyber Circus (MAP05) Main"},
    365065: {'name': 'Cyber Circus (MAP05) - Super kevlar vest (Eastern Side Rooms)',
             'episode': 1,
             'map': 5,
             'index': 57,
             'doom_type': 2019,
             'region': "Cyber Circus (MAP05) Main"},
    365066: {'name': "Cyber Circus (MAP05) - Photon 'zooka (Eastern Side Rooms)",
             'episode': 1,
             'map': 5,
             'index': 60,
             'doom_type': 2003,
             'region': "Cyber Circus (MAP05) Main"},
    365067: {'name': 'Cyber Circus (MAP05) - SI array (Eastern Side Rooms)',
             'episode': 1,
             'map': 5,
             'index': 69,
             'doom_type': 2026,
             'region': "Cyber Circus (MAP05) Main"},
    365068: {'name': 'Cyber Circus (MAP05) - Tazer (Eastern Side Rooms)',
             'episode': 1,
             'map': 5,
             'index': 70,
             'doom_type': 2001,
             'region': "Cyber Circus (MAP05) Main"},
    365069: {'name': 'Cyber Circus (MAP05) - Super kevlar vest 2 (Eastern Side Rooms)',
             'episode': 1,
             'map': 5,
             'index': 73,
             'doom_type': 2019,
             'region': "Cyber Circus (MAP05) Main"},
    365070: {'name': 'Cyber Circus (MAP05) - 007Microtel (Eastern Side Rooms)',
             'episode': 1,
             'map': 5,
             'index': 74,
             'doom_type': 2023,
             'region': "Cyber Circus (MAP05) Main"},
    365071: {'name': 'Cyber Circus (MAP05) - EnK blinder (Cyberspace Entrance)',
             'episode': 1,
             'map': 5,
             'index': 75,
             'doom_type': 2024,
             'region': "Cyber Circus (MAP05) Main"},
    365072: {'name': 'Cyber Circus (MAP05) - 007Microtel (Erratic Room)',
             'episode': 1,
             'map': 5,
             'index': 81,
             'doom_type': 2023,
             'region': "Cyber Circus (MAP05) Main"},
    365073: {'name': 'Cyber Circus (MAP05) - 007Microtel 2 (Erratic Room)',
             'episode': 1,
             'map': 5,
             'index': 82,
             'doom_type': 2023,
             'region': "Cyber Circus (MAP05) Main"},
    365074: {'name': 'Cyber Circus (MAP05) - 007Microtel (Western Side Rooms)',
             'episode': 1,
             'map': 5,
             'index': 83,
             'doom_type': 2023,
             'region': "Cyber Circus (MAP05) Main"},
    365075: {'name': 'Cyber Circus (MAP05) - Exit',
             'episode': 1,
             'map': 5,
             'index': -1,
             'doom_type': -1,
             'region': "Cyber Circus (MAP05) Open Exit"},
    365076: {'name': 'Digi-Ota (MAP06) - Password (Shrine, Central Building)',
             'episode': 2,
             'map': 1,
             'index': 4,
             'doom_type': 13,
             'region': "Digi-Ota (MAP06) Main"},
    365077: {'name': 'Digi-Ota (MAP06) - Blue Z-key (Pit Trap)',
             'episode': 2,
             'map': 1,
             'index': 50,
             'doom_type': 40,
             'region': "Digi-Ota (MAP06) Password"},
    365078: {'name': 'Digi-Ota (MAP06) - Kevlar vest (Hallway to City, Hidden Room)',
             'episode': 2,
             'map': 1,
             'index': 51,
             'doom_type': 2018,
             'region': "Digi-Ota (MAP06) Password"},
    365079: {'name': 'Digi-Ota (MAP06) - Tazer (Entryway)',
             'episode': 2,
             'map': 1,
             'index': 88,
             'doom_type': 2001,
             'region': "Digi-Ota (MAP06) Start"},
    365080: {'name': "Digi-Ota (MAP06) - Photon 'zooka (Hallway to City)",
             'episode': 2,
             'map': 1,
             'index': 100,
             'doom_type': 2003,
             'region': "Digi-Ota (MAP06) Password"},
    365081: {'name': 'Digi-Ota (MAP06) - Super kevlar vest (Shrine, Outdoor Pedestal)',
             'episode': 2,
             'map': 1,
             'index': 135,
             'doom_type': 2019,
             'region': "Digi-Ota (MAP06) Main"},
    365082: {'name': 'Digi-Ota (MAP06) - 007Microtel (Hallway to City, Hidden Room)',
             'episode': 2,
             'map': 1,
             'index': 144,
             'doom_type': 2023,
             'region': "Digi-Ota (MAP06) Password"},
    365083: {'name': 'Digi-Ota (MAP06) - Valise (Shrine, Southwest Building)',
             'episode': 2,
             'map': 1,
             'index': 148,
             'doom_type': 8,
             'region': "Digi-Ota (MAP06) Main"},
    365084: {'name': 'Digi-Ota (MAP06) - Uzi (Shrine, Southwest Building)',
             'episode': 2,
             'map': 1,
             'index': 149,
             'doom_type': 2002,
             'region': "Digi-Ota (MAP06) Main"},
    365085: {'name': 'Digi-Ota (MAP06) - Exit',
             'episode': 2,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "Digi-Ota (MAP06) Z Blue"},
    365086: {'name': 'The Great Wall (MAP07) - Tazer (Atop Platform)',
             'episode': 2,
             'map': 2,
             'index': 1,
             'doom_type': 2001,
             'region': "The Great Wall (MAP07) Opening"},
    365087: {'name': 'The Great Wall (MAP07) - Uzi (North Hall, Secret Room)',
             'episode': 2,
             'map': 2,
             'index': 17,
             'doom_type': 2002,
             'region': "The Great Wall (MAP07) Main"},
    365088: {'name': 'The Great Wall (MAP07) - Password (East Side Room)',
             'episode': 2,
             'map': 2,
             'index': 41,
             'doom_type': 13,
             'region': "The Great Wall (MAP07) Main"},
    365089: {'name': 'The Great Wall (MAP07) - Kevlar vest (North Hall)',
             'episode': 2,
             'map': 2,
             'index': 119,
             'doom_type': 2018,
             'region': "The Great Wall (MAP07) Main"},
    365090: {'name': 'The Great Wall (MAP07) - Uzi (West Side Room)',
             'episode': 2,
             'map': 2,
             'index': 199,
             'doom_type': 2002,
             'region': "The Great Wall (MAP07) Main"},
    365091: {'name': 'The Great Wall (MAP07) - Centrophenoxine (East Side Room, Compartment)',
             'episode': 2,
             'map': 2,
             'index': 208,
             'doom_type': 2013,
             'region': "The Great Wall (MAP07) Main"},
    365092: {'name': "The Great Wall (MAP07) - Photon 'zooka (Main Hall)",
             'episode': 2,
             'map': 2,
             'index': 223,
             'doom_type': 2003,
             'region': "The Great Wall (MAP07) Password"},
    365093: {'name': 'The Great Wall (MAP07) - Centrophenoxine (Main Hall, Secret Closet)',
             'episode': 2,
             'map': 2,
             'index': 224,
             'doom_type': 2013,
             'region': "The Great Wall (MAP07) Password"},
    365094: {'name': 'The Great Wall (MAP07) - Kevlar vest (Main Hall)',
             'episode': 2,
             'map': 2,
             'index': 342,
             'doom_type': 2018,
             'region': "The Great Wall (MAP07) Password"},
    365095: {'name': 'The Great Wall (MAP07) - Exit',
             'episode': 2,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "The Great Wall (MAP07) Password"},
    365096: {'name': 'Garden of Delight (MAP08) - Kevlar vest (Southwest Hall)',
             'episode': 2,
             'map': 3,
             'index': 535,
             'doom_type': 2018,
             'region': "Garden of Delight (MAP08) Main"},
    365097: {'name': 'Garden of Delight (MAP08) - Kevlar vest (Front Garden)',
             'episode': 2,
             'map': 3,
             'index': 536,
             'doom_type': 2018,
             'region': "Garden of Delight (MAP08) Main"},
    365098: {'name': 'Garden of Delight (MAP08) - Super kevlar vest (Southwest Hall, Blind Shot)',
             'episode': 2,
             'map': 3,
             'index': 537,
             'doom_type': 2019,
             'region': "Garden of Delight (MAP08) Main"},
    365099: {'name': 'Garden of Delight (MAP08) - Super kevlar vest (Mansion Secret Exit, West)',
             'episode': 2,
             'map': 3,
             'index': 538,
             'doom_type': 2019,
             'region': "Garden of Delight (MAP08) Main"},
    365100: {'name': 'Garden of Delight (MAP08) - HOIG Reznator (Mansion Secret Exit, West)',
             'episode': 2,
             'map': 3,
             'index': 539,
             'doom_type': 2005,
             'region': "Garden of Delight (MAP08) Main"},
    365101: {'name': 'Garden of Delight (MAP08) - 007Microtel (Mansion Secret Exit, East)',
             'episode': 2,
             'map': 3,
             'index': 540,
             'doom_type': 2023,
             'region': "Garden of Delight (MAP08) Main"},
    365102: {'name': 'Garden of Delight (MAP08) - EnK blinder (Mansion Secret Exit, East)',
             'episode': 2,
             'map': 3,
             'index': 541,
             'doom_type': 2024,
             'region': "Garden of Delight (MAP08) Main"},
    365103: {'name': 'Garden of Delight (MAP08) - Force field (Southwest Hall, Blind Shot)',
             'episode': 2,
             'map': 3,
             'index': 579,
             'doom_type': 2022,
             'region': "Garden of Delight (MAP08) Main"},
    365104: {'name': 'Garden of Delight (MAP08) - SI array (Winding Caves)',
             'episode': 2,
             'map': 3,
             'index': 580,
             'doom_type': 2026,
             'region': "Garden of Delight (MAP08) Garden"},
    365105: {'name': "Garden of Delight (MAP08) - Photon 'zooka (Northeast Hall, Poison Pit Room)",
             'episode': 2,
             'map': 3,
             'index': 581,
             'doom_type': 2003,
             'region': "Garden of Delight (MAP08) Main"},
    365106: {'name': 'Garden of Delight (MAP08) - Valise (Northeast Hall, Small Compartment)',
             'episode': 2,
             'map': 3,
             'index': 583,
             'doom_type': 8,
             'region': "Garden of Delight (MAP08) Main"},
    365107: {'name': 'Garden of Delight (MAP08) - Super kevlar vest (Southeast Hall, Underground)',
             'episode': 2,
             'map': 3,
             'index': 714,
             'doom_type': 2019,
             'region': "Garden of Delight (MAP08) Main"},
    365108: {'name': 'Garden of Delight (MAP08) - Uzi (Northeast Hall)',
             'episode': 2,
             'map': 3,
             'index': 735,
             'doom_type': 2002,
             'region': "Garden of Delight (MAP08) Main"},
    365109: {'name': 'Garden of Delight (MAP08) - 007Microtel (Southeast Hall, In Compartment)',
             'episode': 2,
             'map': 3,
             'index': 776,
             'doom_type': 2023,
             'region': "Garden of Delight (MAP08) Main"},
    365110: {'name': 'Garden of Delight (MAP08) - Body armor (Underground Treasure Room)',
             'episode': 2,
             'map': 3,
             'index': 811,
             'doom_type': 83,
             'region': "Garden of Delight (MAP08) Garden"},
    365111: {'name': 'Garden of Delight (MAP08) - Uzi (Underground Treasure Room)',
             'episode': 2,
             'map': 3,
             'index': 812,
             'doom_type': 2002,
             'region': "Garden of Delight (MAP08) Garden"},
    365112: {'name': 'Garden of Delight (MAP08) - Valise (Underground Treasure Room)',
             'episode': 2,
             'map': 3,
             'index': 816,
             'doom_type': 8,
             'region': "Garden of Delight (MAP08) Garden"},
    365113: {'name': 'Garden of Delight (MAP08) - Exit',
             'episode': 2,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "Garden of Delight (MAP08) Garden"},
    365114: {'name': 'Hidden Fortress (MAP09) - Tazer (River Cave)',
             'episode': 2,
             'map': 4,
             'index': 14,
             'doom_type': 2001,
             'region': "Hidden Fortress (MAP09) Main"},
    365115: {'name': 'Hidden Fortress (MAP09) - Uzi (Path to Overpass)',
             'episode': 2,
             'map': 4,
             'index': 22,
             'doom_type': 2002,
             'region': "Hidden Fortress (MAP09) Main"},
    365116: {'name': 'Hidden Fortress (MAP09) - Blue Z-key (Fortress)',
             'episode': 2,
             'map': 4,
             'index': 56,
             'doom_type': 40,
             'region': "Hidden Fortress (MAP09) Fortress"},
    365117: {'name': 'Hidden Fortress (MAP09) - Super kevlar vest (Docks)',
             'episode': 2,
             'map': 4,
             'index': 74,
             'doom_type': 2019,
             'region': "Hidden Fortress (MAP09) Main"},
    365118: {'name': "Hidden Fortress (MAP09) - Photon 'zooka (Docks)",
             'episode': 2,
             'map': 4,
             'index': 77,
             'doom_type': 2003,
             'region': "Hidden Fortress (MAP09) Main"},
    365119: {'name': "Hidden Fortress (MAP09) - Photon 'zooka (River Overpass)",
             'episode': 2,
             'map': 4,
             'index': 82,
             'doom_type': 2003,
             'region': "Hidden Fortress (MAP09) Main"},
    365120: {'name': 'Hidden Fortress (MAP09) - Kevlar vest (River Overpass)',
             'episode': 2,
             'map': 4,
             'index': 95,
             'doom_type': 2018,
             'region': "Hidden Fortress (MAP09) Main"},
    365121: {'name': 'Hidden Fortress (MAP09) - Uzi (Fortress)',
             'episode': 2,
             'map': 4,
             'index': 126,
             'doom_type': 2002,
             'region': "Hidden Fortress (MAP09) Fortress"},
    365122: {'name': 'Hidden Fortress (MAP09) - HOIG Reznator (Drop-Down Room)',
             'episode': 2,
             'map': 4,
             'index': 127,
             'doom_type': 2005,
             'region': "Hidden Fortress (MAP09) Main"},
    365123: {'name': 'Hidden Fortress (MAP09) - Valise (Lava Garden)',
             'episode': 2,
             'map': 4,
             'index': 179,
             'doom_type': 8,
             'region': "Hidden Fortress (MAP09) Main"},
    365124: {'name': 'Hidden Fortress (MAP09) - Stick (Lava Garden)',
             'episode': 2,
             'map': 4,
             'index': 180,
             'doom_type': 2004,
             'region': "Hidden Fortress (MAP09) Main"},
    365125: {'name': 'Hidden Fortress (MAP09) - Body armor (Path to Overpass, From Fortress)',
             'episode': 2,
             'map': 4,
             'index': 215,
             'doom_type': 83,
             'region': "Hidden Fortress (MAP09) Fortress"},
    365126: {'name': 'Hidden Fortress (MAP09) - SI array (Path to Overpass, From Fortress)',
             'episode': 2,
             'map': 4,
             'index': 221,
             'doom_type': 2026,
             'region': "Hidden Fortress (MAP09) Fortress"},
    365127: {'name': 'Hidden Fortress (MAP09) - Cryogun (Guarded Switch Room)',
             'episode': 2,
             'map': 4,
             'index': 231,
             'doom_type': 82,
             'region': "Hidden Fortress (MAP09) Main"},
    365128: {'name': 'Hidden Fortress (MAP09) - Body armor (Docks)',
             'episode': 2,
             'map': 4,
             'index': 280,
             'doom_type': 83,
             'region': "Hidden Fortress (MAP09) Main"},
    365129: {'name': 'Hidden Fortress (MAP09) - Exit',
             'episode': 2,
             'map': 4,
             'index': -1,
             'doom_type': -1,
             'region': "Hidden Fortress (MAP09) Z-Blue"},
    365130: {'name': 'Anarchist Dream (MAP10) - Kevlar vest (East Chamber)',
             'episode': 2,
             'map': 5,
             'index': 83,
             'doom_type': 2018,
             'region': "Anarchist Dream (MAP10) Main"},
    365131: {'name': 'Anarchist Dream (MAP10) - Stick (East Chamber, Secret Room)',
             'episode': 2,
             'map': 5,
             'index': 374,
             'doom_type': 2004,
             'region': "Anarchist Dream (MAP10) Main"},
    365132: {'name': 'Anarchist Dream (MAP10) - Cryogun (Opening Hallway)',
             'episode': 2,
             'map': 5,
             'index': 388,
             'doom_type': 82,
             'region': "Anarchist Dream (MAP10) Main"},
    365133: {'name': 'Anarchist Dream (MAP10) - Tazer (Fifth Gate, Weapons Cache)',
             'episode': 2,
             'map': 5,
             'index': 422,
             'doom_type': 2001,
             'region': "Anarchist Dream (MAP10) Main"},
    365134: {'name': 'Anarchist Dream (MAP10) - HOIG Reznator (Fifth Gate, Weapons Cache)',
             'episode': 2,
             'map': 5,
             'index': 423,
             'doom_type': 2005,
             'region': "Anarchist Dream (MAP10) Main"},
    365135: {'name': 'Anarchist Dream (MAP10) - Uzi (Fifth Gate, Weapons Cache)',
             'episode': 2,
             'map': 5,
             'index': 424,
             'doom_type': 2002,
             'region': "Anarchist Dream (MAP10) Main"},
    365136: {'name': 'Anarchist Dream (MAP10) - Cryogun (Fifth Gate, Weapons Cache)',
             'episode': 2,
             'map': 5,
             'index': 425,
             'doom_type': 82,
             'region': "Anarchist Dream (MAP10) Main"},
    365137: {'name': "Anarchist Dream (MAP10) - Photon 'zooka (Fifth Gate, Weapons Cache)",
             'episode': 2,
             'map': 5,
             'index': 426,
             'doom_type': 2003,
             'region': "Anarchist Dream (MAP10) Main"},
    365138: {'name': 'Anarchist Dream (MAP10) - Stick (Fifth Gate, Weapons Cache)',
             'episode': 2,
             'map': 5,
             'index': 427,
             'doom_type': 2004,
             'region': "Anarchist Dream (MAP10) Main"},
    365139: {'name': 'Anarchist Dream (MAP10) - 007Microtel (Fifth Gate, Weapons Cache)',
             'episode': 2,
             'map': 5,
             'index': 432,
             'doom_type': 2023,
             'region': "Anarchist Dream (MAP10) Main"},
    365140: {'name': 'Anarchist Dream (MAP10) - EnK blinder (Second Gate, Secret Room)',
             'episode': 2,
             'map': 5,
             'index': 433,
             'doom_type': 2024,
             'region': "Anarchist Dream (MAP10) Main"},
    365141: {'name': 'Anarchist Dream (MAP10) - SI array (Second Gate, Secret Room)',
             'episode': 2,
             'map': 5,
             'index': 434,
             'doom_type': 2026,
             'region': "Anarchist Dream (MAP10) Main"},
    365142: {'name': 'Anarchist Dream (MAP10) - Super kevlar vest (Second Gate, Secret Room)',
             'episode': 2,
             'map': 5,
             'index': 435,
             'doom_type': 2019,
             'region': "Anarchist Dream (MAP10) Main"},
    365143: {'name': 'Anarchist Dream (MAP10) - Body armor (First Gate, Secret Drop)',
             'episode': 2,
             'map': 5,
             'index': 450,
             'doom_type': 83,
             'region': "Anarchist Dream (MAP10) Main"},
    365144: {'name': 'Anarchist Dream (MAP10) - Uzi (East Chamber)',
             'episode': 2,
             'map': 5,
             'index': 457,
             'doom_type': 2002,
             'region': "Anarchist Dream (MAP10) Main"},
    365145: {'name': 'Anarchist Dream (MAP10) - Exit',
             'episode': 2,
             'map': 5,
             'index': -1,
             'doom_type': -1,
             'region': "Anarchist Dream (MAP10) Main"},
    365146: {'name': "Notus Us! (MAP11) - Stick (Executive's Room)",
             'episode': 3,
             'map': 1,
             'index': 166,
             'doom_type': 2004,
             'region': "Notus Us! (MAP11) Keycard"},
    365147: {'name': 'Notus Us! (MAP11) - Password (West Basement)',
             'episode': 3,
             'map': 1,
             'index': 173,
             'doom_type': 13,
             'region': "Notus Us! (MAP11) Early"},
    365148: {'name': 'Notus Us! (MAP11) - Keycard (Meeting Room)',
             'episode': 3,
             'map': 1,
             'index': 174,
             'doom_type': 5,
             'region': "Notus Us! (MAP11) Password"},
    365149: {'name': 'Notus Us! (MAP11) - Tazer (Main Lobby)',
             'episode': 3,
             'map': 1,
             'index': 190,
             'doom_type': 2001,
             'region': "Notus Us! (MAP11) Early"},
    365150: {'name': "Notus Us! (MAP11) - Photon 'zooka (West Basement)",
             'episode': 3,
             'map': 1,
             'index': 246,
             'doom_type': 2003,
             'region': "Notus Us! (MAP11) Early"},
    365151: {'name': 'Notus Us! (MAP11) - Cryogun (East Balcony)',
             'episode': 3,
             'map': 1,
             'index': 247,
             'doom_type': 82,
             'region': "Notus Us! (MAP11) Main"},
    365152: {'name': 'Notus Us! (MAP11) - Uzi (Meeting Room)',
             'episode': 3,
             'map': 1,
             'index': 248,
             'doom_type': 2002,
             'region': "Notus Us! (MAP11) Password"},
    365153: {'name': 'Notus Us! (MAP11) - Kevlar vest (East Basement)',
             'episode': 3,
             'map': 1,
             'index': 249,
             'doom_type': 2018,
             'region': "Notus Us! (MAP11) Main"},
    365154: {'name': 'Notus Us! (MAP11) - Valise (East Entrance)',
             'episode': 3,
             'map': 1,
             'index': 251,
             'doom_type': 8,
             'region': "Notus Us! (MAP11) Main"},
    365155: {'name': 'Notus Us! (MAP11) - Kevlar vest (Cubicles)',
             'episode': 3,
             'map': 1,
             'index': 256,
             'doom_type': 2018,
             'region': "Notus Us! (MAP11) Password"},
    365156: {'name': 'Notus Us! (MAP11) - HOIG Reznator (Records Room, Behind Cabinet)',
             'episode': 3,
             'map': 1,
             'index': 258,
             'doom_type': 2005,
             'region': "Notus Us! (MAP11) Early"},
    365157: {'name': 'Notus Us! (MAP11) - Uzi (West Basement, Hidden Room)',
             'episode': 3,
             'map': 1,
             'index': 306,
             'doom_type': 2002,
             'region': "Notus Us! (MAP11) Early"},
    365158: {'name': 'Notus Us! (MAP11) - SI array (East Basement, Inside Pillar)',
             'episode': 3,
             'map': 1,
             'index': 316,
             'doom_type': 2026,
             'region': "Notus Us! (MAP11) Main"},
    365159: {'name': 'Notus Us! (MAP11) - Exit',
             'episode': 3,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "Notus Us! (MAP11) Keycard"},
    365160: {'name': 'Gothik Gauntlet (MAP12) - Keycard (West City, Plaza)',
             'episode': 3,
             'map': 2,
             'index': 0,
             'doom_type': 5,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365161: {'name': 'Gothik Gauntlet (MAP12) - Password (Two-Story Building)',
             'episode': 3,
             'map': 2,
             'index': 23,
             'doom_type': 13,
             'region': "Gothik Gauntlet (MAP12) Keycard"},
    365162: {'name': 'Gothik Gauntlet (MAP12) - Kevlar vest (Terminatrix Surprise)',
             'episode': 3,
             'map': 2,
             'index': 50,
             'doom_type': 2018,
             'region': "Gothik Gauntlet (MAP12) Start"},
    365163: {'name': 'Gothik Gauntlet (MAP12) - Valise (Two-Story Building)',
             'episode': 3,
             'map': 2,
             'index': 71,
             'doom_type': 8,
             'region': "Gothik Gauntlet (MAP12) Main"},
    365164: {'name': 'Gothik Gauntlet (MAP12) - 007Microtel (Two-Story Building, Trash Chute)',
             'episode': 3,
             'map': 2,
             'index': 95,
             'doom_type': 2023,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365165: {'name': 'Gothik Gauntlet (MAP12) - Kevlar vest (Jump Across Rooftops)',
             'episode': 3,
             'map': 2,
             'index': 124,
             'doom_type': 2018,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365166: {'name': 'Gothik Gauntlet (MAP12) - Centrophenoxine (Bridge to West City)',
             'episode': 3,
             'map': 2,
             'index': 135,
             'doom_type': 2013,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365167: {'name': 'Gothik Gauntlet (MAP12) - Centrophenoxine (West City)',
             'episode': 3,
             'map': 2,
             'index': 216,
             'doom_type': 2013,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365168: {'name': 'Gothik Gauntlet (MAP12) - Force field (West City, Plaza)',
             'episode': 3,
             'map': 2,
             'index': 235,
             'doom_type': 2022,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365169: {'name': 'Gothik Gauntlet (MAP12) - Super kevlar vest (Movie Theater)',
             'episode': 3,
             'map': 2,
             'index': 289,
             'doom_type': 2019,
             'region': "Gothik Gauntlet (MAP12) East City"},
    365170: {'name': 'Gothik Gauntlet (MAP12) - Force field (Sewers)',
             'episode': 3,
             'map': 2,
             'index': 338,
             'doom_type': 2022,
             'region': "Gothik Gauntlet (MAP12) Password"},
    365171: {'name': 'Gothik Gauntlet (MAP12) - Super kevlar vest (Sewers)',
             'episode': 3,
             'map': 2,
             'index': 363,
             'doom_type': 2019,
             'region': "Gothik Gauntlet (MAP12) Password"},
    365172: {'name': 'Gothik Gauntlet (MAP12) - Centrophenoxine (Sewers)',
             'episode': 3,
             'map': 2,
             'index': 364,
             'doom_type': 2013,
             'region': "Gothik Gauntlet (MAP12) Password"},
    365173: {'name': 'Gothik Gauntlet (MAP12) - Body armor (West City, Plaza)',
             'episode': 3,
             'map': 2,
             'index': 366,
             'doom_type': 83,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365174: {'name': 'Gothik Gauntlet (MAP12) - Kevlar vest (West City, Plaza Back Alley)',
             'episode': 3,
             'map': 2,
             'index': 378,
             'doom_type': 2018,
             'region': "Gothik Gauntlet (MAP12) West City"},
    365175: {'name': 'Gothik Gauntlet (MAP12) - Exit',
             'episode': 3,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "Gothik Gauntlet (MAP12) Password"},
    365176: {'name': 'The Sewers (MAP13) - Blue Z-key (Overpass Room)',
             'episode': 3,
             'map': 3,
             'index': 27,
             'doom_type': 40,
             'region': "The Sewers (MAP13) Main"},
    365177: {'name': 'The Sewers (MAP13) - Red Z-key (Blue Door Cave)',
             'episode': 3,
             'map': 3,
             'index': 28,
             'doom_type': 38,
             'region': "The Sewers (MAP13) Z Blue"},
    365178: {'name': 'The Sewers (MAP13) - Uzi (Entrance Corridor)',
             'episode': 3,
             'map': 3,
             'index': 36,
             'doom_type': 2002,
             'region': "The Sewers (MAP13) Main"},
    365179: {'name': 'The Sewers (MAP13) - Valise (Entrance Corridor)',
             'episode': 3,
             'map': 3,
             'index': 39,
             'doom_type': 8,
             'region': "The Sewers (MAP13) Main"},
    365180: {'name': 'The Sewers (MAP13) - Kevlar vest (Entrance Corridor)',
             'episode': 3,
             'map': 3,
             'index': 41,
             'doom_type': 2018,
             'region': "The Sewers (MAP13) Main"},
    365181: {'name': 'The Sewers (MAP13) - Cryogun (Stone Path)',
             'episode': 3,
             'map': 3,
             'index': 65,
             'doom_type': 82,
             'region': "The Sewers (MAP13) Main"},
    365182: {'name': "The Sewers (MAP13) - Photon 'zooka (Z-Chamber)",
             'episode': 3,
             'map': 3,
             'index': 70,
             'doom_type': 2003,
             'region': "The Sewers (MAP13) Main"},
    365183: {'name': 'The Sewers (MAP13) - Stick (Overpass Room)',
             'episode': 3,
             'map': 3,
             'index': 113,
             'doom_type': 2004,
             'region': "The Sewers (MAP13) Main"},
    365184: {'name': 'The Sewers (MAP13) - Nuker (Overpass Room, Balcony)',
             'episode': 3,
             'map': 3,
             'index': 114,
             'doom_type': 2006,
             'region': "The Sewers (MAP13) Main"},
    365185: {'name': 'The Sewers (MAP13) - Kevlar vest (Hallway to Gated Bridge)',
             'episode': 3,
             'map': 3,
             'index': 138,
             'doom_type': 2018,
             'region': "The Sewers (MAP13) Main"},
    365186: {'name': 'The Sewers (MAP13) - Valise (Gatehouse)',
             'episode': 3,
             'map': 3,
             'index': 178,
             'doom_type': 8,
             'region': "The Sewers (MAP13) Z Blue"},
    365187: {'name': 'The Sewers (MAP13) - Super kevlar vest (Terminatrix Room)',
             'episode': 3,
             'map': 3,
             'index': 182,
             'doom_type': 2019,
             'region': "The Sewers (MAP13) Main"},
    365188: {'name': 'The Sewers (MAP13) - SI array (Terminatrix Room)',
             'episode': 3,
             'map': 3,
             'index': 187,
             'doom_type': 2026,
             'region': "The Sewers (MAP13) Main"},
    365189: {'name': 'The Sewers (MAP13) - Body armor (Secret Lava Pool)',
             'episode': 3,
             'map': 3,
             'index': 208,
             'doom_type': 83,
             'region': "The Sewers (MAP13) Z Red"},
    365190: {'name': 'The Sewers (MAP13) - Tazer (Gated Bridge)',
             'episode': 3,
             'map': 3,
             'index': 245,
             'doom_type': 2001,
             'region': "The Sewers (MAP13) Main"},
    365191: {'name': 'The Sewers (MAP13) - Exit',
             'episode': 3,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "The Sewers (MAP13) Z Red"},
    365192: {'name': "'Trode Wars (MAP14) - C-key (Platforming Room)",
             'episode': 3,
             'map': 4,
             'index': 1,
             'doom_type': 6,
             'region': "'Trode Wars (MAP14) Main"},
    365193: {'name': "'Trode Wars (MAP14) - Valise (Platforming Room, False Wall)",
             'episode': 3,
             'map': 4,
             'index': 79,
             'doom_type': 8,
             'region': "'Trode Wars (MAP14) Main"},
    365194: {'name': "'Trode Wars (MAP14) - Super kevlar vest (Exit Hallway, Inside Pillar)",
             'episode': 3,
             'map': 4,
             'index': 80,
             'doom_type': 2019,
             'region': "'Trode Wars (MAP14) Sigma"},
    365195: {'name': "'Trode Wars (MAP14) - Tazer (Entrance)",
             'episode': 3,
             'map': 4,
             'index': 92,
             'doom_type': 2001,
             'region': "'Trode Wars (MAP14) Main"},
    365196: {'name': "'Trode Wars (MAP14) - Uzi (Teleporter Room, False Wall)",
             'episode': 3,
             'map': 4,
             'index': 93,
             'doom_type': 2002,
             'region': "'Trode Wars (MAP14) Sigma"},
    365197: {'name': "'Trode Wars (MAP14) - Photon 'zooka (Giant Switch Room)",
             'episode': 3,
             'map': 4,
             'index': 95,
             'doom_type': 2003,
             'region': "'Trode Wars (MAP14) Sigma"},
    365198: {'name': "'Trode Wars (MAP14) - Exit",
             'episode': 3,
             'map': 4,
             'index': -1,
             'doom_type': -1,
             'region': "'Trode Wars (MAP14) Sigma"},
    365199: {'name': 'Twilight of EnKs (MAP15) - Kevlar vest (Hidden Behind Start)',
             'episode': 3,
             'map': 5,
             'index': 2,
             'doom_type': 2018,
             'region': "Twilight of EnKs (MAP15) Main"},
    365200: {'name': 'Twilight of EnKs (MAP15) - Red Z-key (Pyramid)',
             'episode': 3,
             'map': 5,
             'index': 16,
             'doom_type': 38,
             'region': "Twilight of EnKs (MAP15) Z Blue"},
    365201: {'name': 'Twilight of EnKs (MAP15) - Body armor (Castle, In Window)',
             'episode': 3,
             'map': 5,
             'index': 19,
             'doom_type': 83,
             'region': "Twilight of EnKs (MAP15) Main"},
    365202: {'name': 'Twilight of EnKs (MAP15) - Stick (Pyramid, Inside)',
             'episode': 3,
             'map': 5,
             'index': 21,
             'doom_type': 2004,
             'region': "Twilight of EnKs (MAP15) Main"},
    365203: {'name': 'Twilight of EnKs (MAP15) - Blue Z-key (Castle)',
             'episode': 3,
             'map': 5,
             'index': 22,
             'doom_type': 40,
             'region': "Twilight of EnKs (MAP15) Main"},
    365204: {'name': 'Twilight of EnKs (MAP15) - Cryogun (Castle)',
             'episode': 3,
             'map': 5,
             'index': 25,
             'doom_type': 82,
             'region': "Twilight of EnKs (MAP15) Main"},
    365205: {'name': 'Twilight of EnKs (MAP15) - EnK blinder (Castle, In Water)',
             'episode': 3,
             'map': 5,
             'index': 26,
             'doom_type': 2024,
             'region': "Twilight of EnKs (MAP15) Main"},
    365206: {'name': 'Twilight of EnKs (MAP15) - Valise (Wooden Cross)',
             'episode': 3,
             'map': 5,
             'index': 40,
             'doom_type': 8,
             'region': "Twilight of EnKs (MAP15) Z Blue"},
    365207: {'name': 'Twilight of EnKs (MAP15) - Yellow Z-key (ICE Room)',
             'episode': 3,
             'map': 5,
             'index': 49,
             'doom_type': 39,
             'region': "Twilight of EnKs (MAP15) Main"},
    365208: {'name': 'Twilight of EnKs (MAP15) - Uzi (ICE Room)',
             'episode': 3,
             'map': 5,
             'index': 75,
             'doom_type': 2002,
             'region': "Twilight of EnKs (MAP15) Main"},
    365209: {'name': 'Twilight of EnKs (MAP15) - Centrophenoxine (Pyramid)',
             'episode': 3,
             'map': 5,
             'index': 76,
             'doom_type': 2013,
             'region': "Twilight of EnKs (MAP15) Main"},
    365210: {'name': 'Twilight of EnKs (MAP15) - Kevlar vest (Pyramid, Revealed Room)',
             'episode': 3,
             'map': 5,
             'index': 144,
             'doom_type': 2018,
             'region': "Twilight of EnKs (MAP15) Z Blue"},
    365211: {'name': 'Twilight of EnKs (MAP15) - HOIG Reznator (Hidden Behind Start)',
             'episode': 3,
             'map': 5,
             'index': 166,
             'doom_type': 2005,
             'region': "Twilight of EnKs (MAP15) Main"},
    365212: {'name': "Twilight of EnKs (MAP15) - Photon 'zooka (Dark Cross)",
             'episode': 3,
             'map': 5,
             'index': 170,
             'doom_type': 2003,
             'region': "Twilight of EnKs (MAP15) Main"},
    365213: {'name': 'Twilight of EnKs (MAP15) - Tazer (3-Way Fork)',
             'episode': 3,
             'map': 5,
             'index': 242,
             'doom_type': 2001,
             'region': "Twilight of EnKs (MAP15) Main"},
    365214: {'name': 'Twilight of EnKs (MAP15) - Exit',
             'episode': 3,
             'map': 5,
             'index': -1,
             'doom_type': -1,
             'region': "Twilight of EnKs (MAP15) Z Orange"},
    365215: {'name': 'Desiccant Room (MAP31) - Keycard (Central Halls)',
             'episode': 4,
             'map': 1,
             'index': 11,
             'doom_type': 5,
             'region': "Desiccant Room (MAP31) Main"},
    365216: {'name': 'Desiccant Room (MAP31) - Super kevlar vest (Watch Tower)',
             'episode': 4,
             'map': 1,
             'index': 59,
             'doom_type': 2019,
             'region': "Desiccant Room (MAP31) Outer"},
    365217: {'name': 'Desiccant Room (MAP31) - 007Microtel (Watch Tower)',
             'episode': 4,
             'map': 1,
             'index': 60,
             'doom_type': 2023,
             'region': "Desiccant Room (MAP31) Outer"},
    365218: {'name': "Desiccant Room (MAP31) - Photon 'zooka (Secret Bookshelf)",
             'episode': 4,
             'map': 1,
             'index': 69,
             'doom_type': 2003,
             'region': "Desiccant Room (MAP31) Keycard"},
    365219: {'name': 'Desiccant Room (MAP31) - Exit',
             'episode': 4,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "Desiccant Room (MAP31) Keycard"},
    365220: {'name': 'Protean Cybex (MAP16) - Uzi (Central Room)',
             'episode': 4,
             'map': 2,
             'index': 30,
             'doom_type': 2002,
             'region': "Protean Cybex (MAP16) Main"},
    365221: {'name': 'Protean Cybex (MAP16) - Exit',
             'episode': 4,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "Protean Cybex (MAP16) Main"},
    365222: {'name': 'River of Blood (MAP17) - SI array (Waterfall, Ascent)',
             'episode': 4,
             'map': 3,
             'index': 22,
             'doom_type': 2026,
             'region': "River of Blood (MAP17) Entry"},
    365223: {'name': 'River of Blood (MAP17) - Valise (Storage Room)',
             'episode': 4,
             'map': 3,
             'index': 40,
             'doom_type': 8,
             'region': "River of Blood (MAP17) Main"},
    365224: {'name': 'River of Blood (MAP17) - Uzi (Welcoming Party)',
             'episode': 4,
             'map': 3,
             'index': 68,
             'doom_type': 2002,
             'region': "River of Blood (MAP17) Main"},
    365225: {'name': 'River of Blood (MAP17) - Centrophenoxine (Monstruct Mine)',
             'episode': 4,
             'map': 3,
             'index': 125,
             'doom_type': 2013,
             'region': "River of Blood (MAP17) Main"},
    365226: {'name': 'River of Blood (MAP17) - Stick (West Cave, Side Area)',
             'episode': 4,
             'map': 3,
             'index': 133,
             'doom_type': 2004,
             'region': "River of Blood (MAP17) Main"},
    365227: {'name': "River of Blood (MAP17) - Photon 'zooka (Waterfall)",
             'episode': 4,
             'map': 3,
             'index': 150,
             'doom_type': 2003,
             'region': "River of Blood (MAP17) Entry"},
    365228: {'name': 'River of Blood (MAP17) - 007Microtel (West Cave)',
             'episode': 4,
             'map': 3,
             'index': 153,
             'doom_type': 2023,
             'region': "River of Blood (MAP17) Main"},
    365229: {'name': 'River of Blood (MAP17) - Body armor (Storage Room, Inside Crate)',
             'episode': 4,
             'map': 3,
             'index': 173,
             'doom_type': 83,
             'region': "River of Blood (MAP17) Main"},
    365230: {'name': 'River of Blood (MAP17) - HOIG Reznator (Storage Room)',
             'episode': 4,
             'map': 3,
             'index': 218,
             'doom_type': 2005,
             'region': "River of Blood (MAP17) Main"},
    365231: {'name': 'River of Blood (MAP17) - Nuker (Monstruct Mine)',
             'episode': 4,
             'map': 3,
             'index': 254,
             'doom_type': 2006,
             'region': "River of Blood (MAP17) Main"},
    365232: {'name': 'River of Blood (MAP17) - EnK blinder (Monstruct Mine)',
             'episode': 4,
             'map': 3,
             'index': 300,
             'doom_type': 2024,
             'region': "River of Blood (MAP17) Main"},
    365233: {'name': 'River of Blood (MAP17) - Cryogun (Monstruct Mine, Backtrack)',
             'episode': 4,
             'map': 3,
             'index': 337,
             'doom_type': 82,
             'region': "River of Blood (MAP17) Main"},
    365234: {'name': 'River of Blood (MAP17) - Exit',
             'episode': 4,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "River of Blood (MAP17) Main"},
    365235: {'name': 'Bizarro (MAP18) - Uzi (Southeast Walkway)',
             'episode': 4,
             'map': 4,
             'index': 1,
             'doom_type': 2002,
             'region': "Bizarro (MAP18) All"},
    365236: {'name': 'Bizarro (MAP18) - Uzi (Northwest Walkway)',
             'episode': 4,
             'map': 4,
             'index': 2,
             'doom_type': 2002,
             'region': "Bizarro (MAP18) All"},
    365237: {'name': 'Bizarro (MAP18) - Cryogun (Terminatrix Trap)',
             'episode': 4,
             'map': 4,
             'index': 3,
             'doom_type': 82,
             'region': "Bizarro (MAP18) Opening"},
    365238: {'name': 'Bizarro (MAP18) - Tazer (Monstruct Trap)',
             'episode': 4,
             'map': 4,
             'index': 7,
             'doom_type': 2001,
             'region': "Bizarro (MAP18) Opening"},
    365239: {'name': 'Bizarro (MAP18) - Tazer 2 (Monstruct Trap)',
             'episode': 4,
             'map': 4,
             'index': 8,
             'doom_type': 2001,
             'region': "Bizarro (MAP18) Opening"},
    365240: {'name': 'Bizarro (MAP18) - HOIG Reznator (Monstruct Trap)',
             'episode': 4,
             'map': 4,
             'index': 9,
             'doom_type': 2005,
             'region': "Bizarro (MAP18) Opening"},
    365241: {'name': 'Bizarro (MAP18) - Tazer 3 (Monstruct Trap)',
             'episode': 4,
             'map': 4,
             'index': 10,
             'doom_type': 2001,
             'region': "Bizarro (MAP18) Opening"},
    365242: {'name': "Bizarro (MAP18) - Photon 'zooka (Northwest Walkway)",
             'episode': 4,
             'map': 4,
             'index': 11,
             'doom_type': 2003,
             'region': "Bizarro (MAP18) All"},
    365243: {'name': "Bizarro (MAP18) - Photon 'zooka (Southeast Walkway)",
             'episode': 4,
             'map': 4,
             'index': 12,
             'doom_type': 2003,
             'region': "Bizarro (MAP18) All"},
    365244: {'name': 'Bizarro (MAP18) - Stick (Northwest Walkway)',
             'episode': 4,
             'map': 4,
             'index': 13,
             'doom_type': 2004,
             'region': "Bizarro (MAP18) All"},
    365245: {'name': 'Bizarro (MAP18) - Nuker (Southeast Walkway)',
             'episode': 4,
             'map': 4,
             'index': 14,
             'doom_type': 2006,
             'region': "Bizarro (MAP18) All"},
    365246: {'name': 'Bizarro (MAP18) - Kevlar vest (Monstruct Trap)',
             'episode': 4,
             'map': 4,
             'index': 55,
             'doom_type': 2018,
             'region': "Bizarro (MAP18) Opening"},
    365247: {'name': 'Bizarro (MAP18) - Valise (Northwest Walkway)',
             'episode': 4,
             'map': 4,
             'index': 64,
             'doom_type': 8,
             'region': "Bizarro (MAP18) All"},
    365248: {'name': 'Bizarro (MAP18) - EnK blinder (Southeast Walkway)',
             'episode': 4,
             'map': 4,
             'index': 65,
             'doom_type': 2024,
             'region': "Bizarro (MAP18) All"},
    365249: {'name': 'Bizarro (MAP18) - Blue Z-key (Northwest Walkway)',
             'episode': 4,
             'map': 4,
             'index': 86,
             'doom_type': 40,
             'region': "Bizarro (MAP18) All"},
    365250: {'name': 'Bizarro (MAP18) - EnK blinder (Monstruct Trap)',
             'episode': 4,
             'map': 4,
             'index': 91,
             'doom_type': 2024,
             'region': "Bizarro (MAP18) Opening"},
    365251: {'name': 'Bizarro (MAP18) - Exit',
             'episode': 4,
             'map': 4,
             'index': -1,
             'doom_type': -1,
             'region': "Bizarro (MAP18) All"},
    365252: {'name': 'The War Rooms (MAP19) - Tazer (Central Room)',
             'episode': 4,
             'map': 5,
             'index': 176,
             'doom_type': 2001,
             'region': "The War Rooms (MAP19) Main"},
    365253: {'name': 'The War Rooms (MAP19) - Uzi (Hallway to Outer Rooms)',
             'episode': 4,
             'map': 5,
             'index': 236,
             'doom_type': 2002,
             'region': "The War Rooms (MAP19) Main"},
    365254: {'name': "The War Rooms (MAP19) - Photon 'zooka (Outer Rooms, By Window)",
             'episode': 4,
             'map': 5,
             'index': 237,
             'doom_type': 2003,
             'region': "The War Rooms (MAP19) Main"},
    365255: {'name': 'The War Rooms (MAP19) - Stick (Outer Rooms)',
             'episode': 4,
             'map': 5,
             'index': 238,
             'doom_type': 2004,
             'region': "The War Rooms (MAP19) Main"},
    365256: {'name': 'The War Rooms (MAP19) - Nuker (Outer Rooms, Secret Compartment)',
             'episode': 4,
             'map': 5,
             'index': 239,
             'doom_type': 2006,
             'region': "The War Rooms (MAP19) Main"},
    365257: {'name': 'The War Rooms (MAP19) - Super kevlar vest (Central Room)',
             'episode': 4,
             'map': 5,
             'index': 294,
             'doom_type': 2019,
             'region': "The War Rooms (MAP19) Main"},
    365258: {'name': 'The War Rooms (MAP19) - Exit',
             'episode': 4,
             'map': 5,
             'index': -1,
             'doom_type': -1,
             'region': "The War Rooms (MAP19) Main"},
    365259: {'name': 'Intruder Alert! (MAP20) - Super kevlar vest (Cyberspace Welcome Room)',
             'episode': 4,
             'map': 6,
             'index': 12,
             'doom_type': 2019,
             'region': "Intruder Alert! (MAP20) Main"},
    365260: {'name': 'Intruder Alert! (MAP20) - C-key (Pillar Room)',
             'episode': 4,
             'map': 6,
             'index': 103,
             'doom_type': 6,
             'region': "Intruder Alert! (MAP20) Main"},
    365261: {'name': 'Intruder Alert! (MAP20) - Body armor (Pillar Room)',
             'episode': 4,
             'map': 6,
             'index': 104,
             'doom_type': 83,
             'region': "Intruder Alert! (MAP20) Main"},
    365262: {'name': 'Intruder Alert! (MAP20) - Nuker (Pillar Room)',
             'episode': 4,
             'map': 6,
             'index': 105,
             'doom_type': 2006,
             'region': "Intruder Alert! (MAP20) Main"},
    365263: {'name': 'Intruder Alert! (MAP20) - Cryogun (Pillar Room)',
             'episode': 4,
             'map': 6,
             'index': 106,
             'doom_type': 82,
             'region': "Intruder Alert! (MAP20) Main"},
    365264: {'name': 'Intruder Alert! (MAP20) - Stick (Teeth Room)',
             'episode': 4,
             'map': 6,
             'index': 155,
             'doom_type': 2004,
             'region': "Intruder Alert! (MAP20) Main"},
    365265: {'name': 'Intruder Alert! (MAP20) - Body armor (Teeth Room)',
             'episode': 4,
             'map': 6,
             'index': 162,
             'doom_type': 83,
             'region': "Intruder Alert! (MAP20) Main"},
    365266: {'name': 'Intruder Alert! (MAP20) - Body armor (Sigma Room)',
             'episode': 4,
             'map': 6,
             'index': 201,
             'doom_type': 83,
             'region': "Intruder Alert! (MAP20) Sigma"},
    365267: {'name': 'Intruder Alert! (MAP20) - Cryogun (Cyberspace Welcome Room)',
             'episode': 4,
             'map': 6,
             'index': 216,
             'doom_type': 82,
             'region': "Intruder Alert! (MAP20) Main"},
    365268: {'name': "Intruder Alert! (MAP20) - Photon 'zooka (Cyberspace Welcome Room)",
             'episode': 4,
             'map': 6,
             'index': 217,
             'doom_type': 2003,
             'region': "Intruder Alert! (MAP20) Main"},
    365269: {'name': 'Intruder Alert! (MAP20) - Uzi (Before Bridge, Trap Alcove)',
             'episode': 4,
             'map': 6,
             'index': 236,
             'doom_type': 2002,
             'region': "Intruder Alert! (MAP20) Main"},
    365270: {'name': 'Intruder Alert! (MAP20) - Valise (Before Bridge, Trap Alcove)',
             'episode': 4,
             'map': 6,
             'index': 237,
             'doom_type': 8,
             'region': "Intruder Alert! (MAP20) Main"},
    365271: {'name': 'Intruder Alert! (MAP20) - Super kevlar vest (Before Bridge)',
             'episode': 4,
             'map': 6,
             'index': 240,
             'doom_type': 2019,
             'region': "Intruder Alert! (MAP20) Main"},
    365272: {'name': 'Intruder Alert! (MAP20) - Body armor (Erratic Bridge)',
             'episode': 4,
             'map': 6,
             'index': 271,
             'doom_type': 83,
             'region': "Intruder Alert! (MAP20) Main"},
    365273: {'name': 'Intruder Alert! (MAP20) - Nuker (Erratic Bridge)',
             'episode': 4,
             'map': 6,
             'index': 272,
             'doom_type': 2006,
             'region': "Intruder Alert! (MAP20) Main"},
    365274: {'name': 'Intruder Alert! (MAP20) - Force field (Erratic Bridge)',
             'episode': 4,
             'map': 6,
             'index': 277,
             'doom_type': 2022,
             'region': "Intruder Alert! (MAP20) Main"},
    365275: {'name': 'Intruder Alert! (MAP20) - Exit',
             'episode': 4,
             'map': 6,
             'index': -1,
             'doom_type': -1,
             'region': "Intruder Alert! (MAP20) Sigma"},
}


location_name_groups: Dict[str, Set[str]] = {
    "'Trode Wars (MAP14)": {
        "'Trode Wars (MAP14) - C-key (Platforming Room)",
        "'Trode Wars (MAP14) - Exit",
        "'Trode Wars (MAP14) - Photon 'zooka (Giant Switch Room)",
        "'Trode Wars (MAP14) - Super kevlar vest (Exit Hallway, Inside Pillar)",
        "'Trode Wars (MAP14) - Tazer (Entrance)",
        "'Trode Wars (MAP14) - Uzi (Teleporter Room, False Wall)",
        "'Trode Wars (MAP14) - Valise (Platforming Room, False Wall)",
    },
    'Alcatraz (MAP04)': {
        'Alcatraz (MAP04) - 007Microtel (Atop the Wall)',
        'Alcatraz (MAP04) - 007Microtel (Hallway to Upper Cell Block)',
        'Alcatraz (MAP04) - 007Microtel (Lower Cell Block)',
        'Alcatraz (MAP04) - Exit',
        'Alcatraz (MAP04) - Force field (Mysterious Column, Hidden Switch)',
        'Alcatraz (MAP04) - HOIG Reznator (Mysterious Column)',
        "Alcatraz (MAP04) - Photon 'zooka (Elevator to the Wall)",
        "Alcatraz (MAP04) - Photon 'zooka (Hidden Entrance)",
        'Alcatraz (MAP04) - SI array (Lower Cell Block)',
        'Alcatraz (MAP04) - Super kevlar vest (Hallway to Upper Cell Block)',
        'Alcatraz (MAP04) - Super kevlar vest (Mysterious Column)',
        'Alcatraz (MAP04) - Super kevlar vest (Rock Climbing)',
        'Alcatraz (MAP04) - Tazer (Elevator to the Wall)',
    },
    'Anarchist Dream (MAP10)': {
        'Anarchist Dream (MAP10) - 007Microtel (Fifth Gate, Weapons Cache)',
        'Anarchist Dream (MAP10) - Body armor (First Gate, Secret Drop)',
        'Anarchist Dream (MAP10) - Cryogun (Fifth Gate, Weapons Cache)',
        'Anarchist Dream (MAP10) - Cryogun (Opening Hallway)',
        'Anarchist Dream (MAP10) - EnK blinder (Second Gate, Secret Room)',
        'Anarchist Dream (MAP10) - Exit',
        'Anarchist Dream (MAP10) - HOIG Reznator (Fifth Gate, Weapons Cache)',
        'Anarchist Dream (MAP10) - Kevlar vest (East Chamber)',
        "Anarchist Dream (MAP10) - Photon 'zooka (Fifth Gate, Weapons Cache)",
        'Anarchist Dream (MAP10) - SI array (Second Gate, Secret Room)',
        'Anarchist Dream (MAP10) - Stick (East Chamber, Secret Room)',
        'Anarchist Dream (MAP10) - Stick (Fifth Gate, Weapons Cache)',
        'Anarchist Dream (MAP10) - Super kevlar vest (Second Gate, Secret Room)',
        'Anarchist Dream (MAP10) - Tazer (Fifth Gate, Weapons Cache)',
        'Anarchist Dream (MAP10) - Uzi (East Chamber)',
        'Anarchist Dream (MAP10) - Uzi (Fifth Gate, Weapons Cache)',
    },
    'Bizarro (MAP18)': {
        'Bizarro (MAP18) - Blue Z-key (Northwest Walkway)',
        'Bizarro (MAP18) - Cryogun (Terminatrix Trap)',
        'Bizarro (MAP18) - EnK blinder (Monstruct Trap)',
        'Bizarro (MAP18) - EnK blinder (Southeast Walkway)',
        'Bizarro (MAP18) - Exit',
        'Bizarro (MAP18) - HOIG Reznator (Monstruct Trap)',
        'Bizarro (MAP18) - Kevlar vest (Monstruct Trap)',
        'Bizarro (MAP18) - Nuker (Southeast Walkway)',
        "Bizarro (MAP18) - Photon 'zooka (Northwest Walkway)",
        "Bizarro (MAP18) - Photon 'zooka (Southeast Walkway)",
        'Bizarro (MAP18) - Stick (Northwest Walkway)',
        'Bizarro (MAP18) - Tazer (Monstruct Trap)',
        'Bizarro (MAP18) - Tazer 2 (Monstruct Trap)',
        'Bizarro (MAP18) - Tazer 3 (Monstruct Trap)',
        'Bizarro (MAP18) - Uzi (Northwest Walkway)',
        'Bizarro (MAP18) - Uzi (Southeast Walkway)',
        'Bizarro (MAP18) - Valise (Northwest Walkway)',
    },
    'Cyber Circus (MAP05)': {
        'Cyber Circus (MAP05) - 007Microtel (Behind Pulsar)',
        'Cyber Circus (MAP05) - 007Microtel (Eastern Side Rooms)',
        'Cyber Circus (MAP05) - 007Microtel (Erratic Room)',
        'Cyber Circus (MAP05) - 007Microtel (Sigma Room)',
        'Cyber Circus (MAP05) - 007Microtel (Western Side Rooms)',
        'Cyber Circus (MAP05) - 007Microtel 2 (Erratic Room)',
        'Cyber Circus (MAP05) - C-key (Erratic Room)',
        'Cyber Circus (MAP05) - EnK blinder (Cyberspace Entrance)',
        'Cyber Circus (MAP05) - Exit',
        'Cyber Circus (MAP05) - HOIG Reznator (Western Side Rooms)',
        "Cyber Circus (MAP05) - Photon 'zooka (Behind Pulsar)",
        "Cyber Circus (MAP05) - Photon 'zooka (Eastern Side Rooms)",
        'Cyber Circus (MAP05) - SI array (Eastern Side Rooms)',
        'Cyber Circus (MAP05) - Super kevlar vest (Behind Pulsar)',
        'Cyber Circus (MAP05) - Super kevlar vest (Eastern Side Rooms)',
        'Cyber Circus (MAP05) - Super kevlar vest (Sigma Room)',
        'Cyber Circus (MAP05) - Super kevlar vest 2 (Eastern Side Rooms)',
        'Cyber Circus (MAP05) - Tazer (Eastern Side Rooms)',
        'Cyber Circus (MAP05) - Valise (Western Side Rooms, to Erratic Room)',
    },
    'Desiccant Room (MAP31)': {
        'Desiccant Room (MAP31) - 007Microtel (Watch Tower)',
        'Desiccant Room (MAP31) - Exit',
        'Desiccant Room (MAP31) - Keycard (Central Halls)',
        "Desiccant Room (MAP31) - Photon 'zooka (Secret Bookshelf)",
        'Desiccant Room (MAP31) - Super kevlar vest (Watch Tower)',
    },
    'Digi-Ota (MAP06)': {
        'Digi-Ota (MAP06) - 007Microtel (Hallway to City, Hidden Room)',
        'Digi-Ota (MAP06) - Blue Z-key (Pit Trap)',
        'Digi-Ota (MAP06) - Exit',
        'Digi-Ota (MAP06) - Kevlar vest (Hallway to City, Hidden Room)',
        'Digi-Ota (MAP06) - Password (Shrine, Central Building)',
        "Digi-Ota (MAP06) - Photon 'zooka (Hallway to City)",
        'Digi-Ota (MAP06) - Super kevlar vest (Shrine, Outdoor Pedestal)',
        'Digi-Ota (MAP06) - Tazer (Entryway)',
        'Digi-Ota (MAP06) - Uzi (Shrine, Southwest Building)',
        'Digi-Ota (MAP06) - Valise (Shrine, Southwest Building)',
    },
    'Garden of Delight (MAP08)': {
        'Garden of Delight (MAP08) - 007Microtel (Mansion Secret Exit, East)',
        'Garden of Delight (MAP08) - 007Microtel (Southeast Hall, In Compartment)',
        'Garden of Delight (MAP08) - Body armor (Underground Treasure Room)',
        'Garden of Delight (MAP08) - EnK blinder (Mansion Secret Exit, East)',
        'Garden of Delight (MAP08) - Exit',
        'Garden of Delight (MAP08) - Force field (Southwest Hall, Blind Shot)',
        'Garden of Delight (MAP08) - HOIG Reznator (Mansion Secret Exit, West)',
        'Garden of Delight (MAP08) - Kevlar vest (Front Garden)',
        'Garden of Delight (MAP08) - Kevlar vest (Southwest Hall)',
        "Garden of Delight (MAP08) - Photon 'zooka (Northeast Hall, Poison Pit Room)",
        'Garden of Delight (MAP08) - SI array (Winding Caves)',
        'Garden of Delight (MAP08) - Super kevlar vest (Mansion Secret Exit, West)',
        'Garden of Delight (MAP08) - Super kevlar vest (Southeast Hall, Underground)',
        'Garden of Delight (MAP08) - Super kevlar vest (Southwest Hall, Blind Shot)',
        'Garden of Delight (MAP08) - Uzi (Northeast Hall)',
        'Garden of Delight (MAP08) - Uzi (Underground Treasure Room)',
        'Garden of Delight (MAP08) - Valise (Northeast Hall, Small Compartment)',
        'Garden of Delight (MAP08) - Valise (Underground Treasure Room)',
    },
    'GenEmp Corp. (MAP01)': {
        'GenEmp Corp. (MAP01) - 007Microtel (Train Station)',
        'GenEmp Corp. (MAP01) - 007Microtel (Upper Floor, Office )',
        'GenEmp Corp. (MAP01) - 007Microtel 2 (Train Station)',
        'GenEmp Corp. (MAP01) - Centrophenoxine (Waste Treatment)',
        'GenEmp Corp. (MAP01) - Exit',
        'GenEmp Corp. (MAP01) - Force field (Foyer)',
        'GenEmp Corp. (MAP01) - Force field (Waste Treatment)',
        'GenEmp Corp. (MAP01) - Kevlar vest (Outside)',
        'GenEmp Corp. (MAP01) - Kevlar vest (Security Room, Desk Switch)',
        'GenEmp Corp. (MAP01) - Kevlar vest (Security Weapons Room)',
        'GenEmp Corp. (MAP01) - Kevlar vest (Upper Floor, Office)',
        'GenEmp Corp. (MAP01) - Kevlar vest (Waste Treatment)',
        'GenEmp Corp. (MAP01) - Kevlar vest (Waste Treatment, Ammo Room )',
        'GenEmp Corp. (MAP01) - Keycard (Security Room)',
        'GenEmp Corp. (MAP01) - Password (Upper Floor, Project Room)',
        'GenEmp Corp. (MAP01) - SI array (Security Room)',
        'GenEmp Corp. (MAP01) - Super kevlar vest (Train Station)',
        'GenEmp Corp. (MAP01) - Super kevlar vest (Waste Treatment)',
        'GenEmp Corp. (MAP01) - Tazer (Foyer)',
        'GenEmp Corp. (MAP01) - Valise (Security Weapons Room)',
    },
    'Gothik Gauntlet (MAP12)': {
        'Gothik Gauntlet (MAP12) - 007Microtel (Two-Story Building, Trash Chute)',
        'Gothik Gauntlet (MAP12) - Body armor (West City, Plaza)',
        'Gothik Gauntlet (MAP12) - Centrophenoxine (Bridge to West City)',
        'Gothik Gauntlet (MAP12) - Centrophenoxine (Sewers)',
        'Gothik Gauntlet (MAP12) - Centrophenoxine (West City)',
        'Gothik Gauntlet (MAP12) - Exit',
        'Gothik Gauntlet (MAP12) - Force field (Sewers)',
        'Gothik Gauntlet (MAP12) - Force field (West City, Plaza)',
        'Gothik Gauntlet (MAP12) - Kevlar vest (Jump Across Rooftops)',
        'Gothik Gauntlet (MAP12) - Kevlar vest (Terminatrix Surprise)',
        'Gothik Gauntlet (MAP12) - Kevlar vest (West City, Plaza Back Alley)',
        'Gothik Gauntlet (MAP12) - Keycard (West City, Plaza)',
        'Gothik Gauntlet (MAP12) - Password (Two-Story Building)',
        'Gothik Gauntlet (MAP12) - Super kevlar vest (Movie Theater)',
        'Gothik Gauntlet (MAP12) - Super kevlar vest (Sewers)',
        'Gothik Gauntlet (MAP12) - Valise (Two-Story Building)',
    },
    'Hidden Fortress (MAP09)': {
        'Hidden Fortress (MAP09) - Blue Z-key (Fortress)',
        'Hidden Fortress (MAP09) - Body armor (Docks)',
        'Hidden Fortress (MAP09) - Body armor (Path to Overpass, From Fortress)',
        'Hidden Fortress (MAP09) - Cryogun (Guarded Switch Room)',
        'Hidden Fortress (MAP09) - Exit',
        'Hidden Fortress (MAP09) - HOIG Reznator (Drop-Down Room)',
        'Hidden Fortress (MAP09) - Kevlar vest (River Overpass)',
        "Hidden Fortress (MAP09) - Photon 'zooka (Docks)",
        "Hidden Fortress (MAP09) - Photon 'zooka (River Overpass)",
        'Hidden Fortress (MAP09) - SI array (Path to Overpass, From Fortress)',
        'Hidden Fortress (MAP09) - Stick (Lava Garden)',
        'Hidden Fortress (MAP09) - Super kevlar vest (Docks)',
        'Hidden Fortress (MAP09) - Tazer (River Cave)',
        'Hidden Fortress (MAP09) - Uzi (Fortress)',
        'Hidden Fortress (MAP09) - Uzi (Path to Overpass)',
        'Hidden Fortress (MAP09) - Valise (Lava Garden)',
    },
    'Intruder Alert! (MAP20)': {
        'Intruder Alert! (MAP20) - Body armor (Erratic Bridge)',
        'Intruder Alert! (MAP20) - Body armor (Pillar Room)',
        'Intruder Alert! (MAP20) - Body armor (Sigma Room)',
        'Intruder Alert! (MAP20) - Body armor (Teeth Room)',
        'Intruder Alert! (MAP20) - C-key (Pillar Room)',
        'Intruder Alert! (MAP20) - Cryogun (Cyberspace Welcome Room)',
        'Intruder Alert! (MAP20) - Cryogun (Pillar Room)',
        'Intruder Alert! (MAP20) - Exit',
        'Intruder Alert! (MAP20) - Force field (Erratic Bridge)',
        'Intruder Alert! (MAP20) - Nuker (Erratic Bridge)',
        'Intruder Alert! (MAP20) - Nuker (Pillar Room)',
        "Intruder Alert! (MAP20) - Photon 'zooka (Cyberspace Welcome Room)",
        'Intruder Alert! (MAP20) - Stick (Teeth Room)',
        'Intruder Alert! (MAP20) - Super kevlar vest (Before Bridge)',
        'Intruder Alert! (MAP20) - Super kevlar vest (Cyberspace Welcome Room)',
        'Intruder Alert! (MAP20) - Uzi (Before Bridge, Trap Alcove)',
        'Intruder Alert! (MAP20) - Valise (Before Bridge, Trap Alcove)',
    },
    'Lava Annex (MAP03)': {
        'Lava Annex (MAP03) - 007Microtel (Elevator Room)',
        'Lava Annex (MAP03) - Blue Z-key (Elevator Room)',
        'Lava Annex (MAP03) - Body armor (Volcano, Side Rooms)',
        'Lava Annex (MAP03) - Centrophenoxine (Android Hallway)',
        'Lava Annex (MAP03) - Centrophenoxine (South Lava Cavern)',
        'Lava Annex (MAP03) - Centrophenoxine (Volcano)',
        'Lava Annex (MAP03) - Centrophenoxine (Volcano, Side Rooms)',
        'Lava Annex (MAP03) - Cryogun (Elevator Room)',
        'Lava Annex (MAP03) - Exit',
        'Lava Annex (MAP03) - HOIG Reznator (Volcano)',
        "Lava Annex (MAP03) - Photon 'zooka (Lift Shot Secret)",
        'Lava Annex (MAP03) - Red Z-key (Volcano)',
        'Lava Annex (MAP03) - SI array (Volcano)',
        'Lava Annex (MAP03) - Super kevlar vest (Cave Entrance)',
        'Lava Annex (MAP03) - Valise (Android Hallway)',
    },
    'Notus Us! (MAP11)': {
        'Notus Us! (MAP11) - Cryogun (East Balcony)',
        'Notus Us! (MAP11) - Exit',
        'Notus Us! (MAP11) - HOIG Reznator (Records Room, Behind Cabinet)',
        'Notus Us! (MAP11) - Kevlar vest (Cubicles)',
        'Notus Us! (MAP11) - Kevlar vest (East Basement)',
        'Notus Us! (MAP11) - Keycard (Meeting Room)',
        'Notus Us! (MAP11) - Password (West Basement)',
        "Notus Us! (MAP11) - Photon 'zooka (West Basement)",
        'Notus Us! (MAP11) - SI array (East Basement, Inside Pillar)',
        "Notus Us! (MAP11) - Stick (Executive's Room)",
        'Notus Us! (MAP11) - Tazer (Main Lobby)',
        'Notus Us! (MAP11) - Uzi (Meeting Room)',
        'Notus Us! (MAP11) - Uzi (West Basement, Hidden Room)',
        'Notus Us! (MAP11) - Valise (East Entrance)',
    },
    'Protean Cybex (MAP16)': {
        'Protean Cybex (MAP16) - Exit',
        'Protean Cybex (MAP16) - Uzi (Central Room)',
    },
    'River of Blood (MAP17)': {
        'River of Blood (MAP17) - 007Microtel (West Cave)',
        'River of Blood (MAP17) - Body armor (Storage Room, Inside Crate)',
        'River of Blood (MAP17) - Centrophenoxine (Monstruct Mine)',
        'River of Blood (MAP17) - Cryogun (Monstruct Mine, Backtrack)',
        'River of Blood (MAP17) - EnK blinder (Monstruct Mine)',
        'River of Blood (MAP17) - Exit',
        'River of Blood (MAP17) - HOIG Reznator (Storage Room)',
        'River of Blood (MAP17) - Nuker (Monstruct Mine)',
        "River of Blood (MAP17) - Photon 'zooka (Waterfall)",
        'River of Blood (MAP17) - SI array (Waterfall, Ascent)',
        'River of Blood (MAP17) - Stick (West Cave, Side Area)',
        'River of Blood (MAP17) - Uzi (Welcoming Party)',
        'River of Blood (MAP17) - Valise (Storage Room)',
    },
    'The Great Wall (MAP07)': {
        'The Great Wall (MAP07) - Centrophenoxine (East Side Room, Compartment)',
        'The Great Wall (MAP07) - Centrophenoxine (Main Hall, Secret Closet)',
        'The Great Wall (MAP07) - Exit',
        'The Great Wall (MAP07) - Kevlar vest (Main Hall)',
        'The Great Wall (MAP07) - Kevlar vest (North Hall)',
        'The Great Wall (MAP07) - Password (East Side Room)',
        "The Great Wall (MAP07) - Photon 'zooka (Main Hall)",
        'The Great Wall (MAP07) - Tazer (Atop Platform)',
        'The Great Wall (MAP07) - Uzi (North Hall, Secret Room)',
        'The Great Wall (MAP07) - Uzi (West Side Room)',
    },
    'The Sewers (MAP13)': {
        'The Sewers (MAP13) - Blue Z-key (Overpass Room)',
        'The Sewers (MAP13) - Body armor (Secret Lava Pool)',
        'The Sewers (MAP13) - Cryogun (Stone Path)',
        'The Sewers (MAP13) - Exit',
        'The Sewers (MAP13) - Kevlar vest (Entrance Corridor)',
        'The Sewers (MAP13) - Kevlar vest (Hallway to Gated Bridge)',
        'The Sewers (MAP13) - Nuker (Overpass Room, Balcony)',
        "The Sewers (MAP13) - Photon 'zooka (Z-Chamber)",
        'The Sewers (MAP13) - Red Z-key (Blue Door Cave)',
        'The Sewers (MAP13) - SI array (Terminatrix Room)',
        'The Sewers (MAP13) - Stick (Overpass Room)',
        'The Sewers (MAP13) - Super kevlar vest (Terminatrix Room)',
        'The Sewers (MAP13) - Tazer (Gated Bridge)',
        'The Sewers (MAP13) - Uzi (Entrance Corridor)',
        'The Sewers (MAP13) - Valise (Entrance Corridor)',
        'The Sewers (MAP13) - Valise (Gatehouse)',
    },
    'The War Rooms (MAP19)': {
        'The War Rooms (MAP19) - Exit',
        'The War Rooms (MAP19) - Nuker (Outer Rooms, Secret Compartment)',
        "The War Rooms (MAP19) - Photon 'zooka (Outer Rooms, By Window)",
        'The War Rooms (MAP19) - Stick (Outer Rooms)',
        'The War Rooms (MAP19) - Super kevlar vest (Central Room)',
        'The War Rooms (MAP19) - Tazer (Central Room)',
        'The War Rooms (MAP19) - Uzi (Hallway to Outer Rooms)',
    },
    'Tunnel Town (MAP02)': {
        'Tunnel Town (MAP02) - 007Microtel (Blackout Room)',
        'Tunnel Town (MAP02) - 007Microtel (Last Hall)',
        'Tunnel Town (MAP02) - Exit',
        'Tunnel Town (MAP02) - Kevlar vest (Blackout Room)',
        'Tunnel Town (MAP02) - Keycard (Bridge)',
        'Tunnel Town (MAP02) - Password (Assembly Room)',
        "Tunnel Town (MAP02) - Photon 'zooka (Curved Staircase)",
        'Tunnel Town (MAP02) - SI array (Assembly Room)',
        'Tunnel Town (MAP02) - Super kevlar vest (North Puzzle Area)',
    },
    'Twilight of EnKs (MAP15)': {
        'Twilight of EnKs (MAP15) - Blue Z-key (Castle)',
        'Twilight of EnKs (MAP15) - Body armor (Castle, In Window)',
        'Twilight of EnKs (MAP15) - Centrophenoxine (Pyramid)',
        'Twilight of EnKs (MAP15) - Cryogun (Castle)',
        'Twilight of EnKs (MAP15) - EnK blinder (Castle, In Water)',
        'Twilight of EnKs (MAP15) - Exit',
        'Twilight of EnKs (MAP15) - HOIG Reznator (Hidden Behind Start)',
        'Twilight of EnKs (MAP15) - Kevlar vest (Hidden Behind Start)',
        'Twilight of EnKs (MAP15) - Kevlar vest (Pyramid, Revealed Room)',
        "Twilight of EnKs (MAP15) - Photon 'zooka (Dark Cross)",
        'Twilight of EnKs (MAP15) - Red Z-key (Pyramid)',
        'Twilight of EnKs (MAP15) - Stick (Pyramid, Inside)',
        'Twilight of EnKs (MAP15) - Tazer (3-Way Fork)',
        'Twilight of EnKs (MAP15) - Uzi (ICE Room)',
        'Twilight of EnKs (MAP15) - Valise (Wooden Cross)',
        'Twilight of EnKs (MAP15) - Yellow Z-key (ICE Room)',
    },
}


death_logic_locations = [
    "Twilight of EnKs (MAP15) - Body armor (Castle, In Window)",
]
