# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from BaseClasses import ItemClassification
from typing import TypedDict, Dict, Set 


class ItemDict(TypedDict, total=False): 
    classification: ItemClassification 
    count: int 
    name: str 
    doom_type: int # Unique numerical id used to spawn the item. -1 is level item, -2 is level complete item. 
    episode: int # Relevant if that item targets a specific level, like keycard or map reveal pickup. 
    map: int 


item_table: Dict[int, ItemDict] = {
    362000: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sawed-off shotgun',
             'doom_type': 2001,
             'episode': -1,
             'map': -1},
    362001: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Rocket launcher',
             'doom_type': 2003,
             'episode': -1,
             'map': -1},
    362002: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'NFG',
             'doom_type': 2004,
             'episode': -1,
             'map': -1},
    362003: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Chainsaw',
             'doom_type': 2005,
             'episode': -1,
             'map': -1},
    362004: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Chaingun',
             'doom_type': 2002,
             'episode': -1,
             'map': -1},
    362005: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Psychic blaster',
             'doom_type': 2006,
             'episode': -1,
             'map': -1},
    362006: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Super shotgun',
             'doom_type': 82,
             'episode': -1,
             'map': -1},
    362007: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Backpack',
             'doom_type': 8,
             'episode': -1,
             'map': -1},
    362008: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Armor',
             'doom_type': 2018,
             'episode': -1,
             'map': -1},
    362009: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Mega Armor',
             'doom_type': 2019,
             'episode': -1,
             'map': -1},
    362010: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Berserk',
             'doom_type': 2023,
             'episode': -1,
             'map': -1},
    362011: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Invulnerability',
             'doom_type': 2022,
             'episode': -1,
             'map': -1},
    362012: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Partial invisibility',
             'doom_type': 2024,
             'episode': -1,
             'map': -1},
    362013: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Supercharge',
             'doom_type': 2013,
             'episode': -1,
             'map': -1},
    362014: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Megasphere',
             'doom_type': 83,
             'episode': -1,
             'map': -1},
    362015: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Medikit',
             'doom_type': 2012,
             'episode': -1,
             'map': -1},
    362016: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of bullets',
             'doom_type': 2048,
             'episode': -1,
             'map': -1},
    362017: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of rockets',
             'doom_type': 2046,
             'episode': -1,
             'map': -1},
    362018: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of shotgun shells',
             'doom_type': 2049,
             'episode': -1,
             'map': -1},
    362019: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Battery',
             'doom_type': 17,
             'episode': -1,
             'map': -1},
    362200: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Barracks (MAP01) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 1},
    362201: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Outskirts (MAP02) - Blue skull key',
             'doom_type': 40,
             'episode': 1,
             'map': 2},
    362202: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Outskirts (MAP02) - Red skull key',
             'doom_type': 38,
             'episode': 1,
             'map': 2},
    362203: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Downtown (MAP03) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 3},
    362204: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Downtown (MAP03) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 3},
    362205: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Industrial Zone (MAP04) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 4},
    362206: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Industrial Zone (MAP04) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 4},
    362207: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Depot (MAP05) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 5},
    362208: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Launch Control (MAP06) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 6},
    362209: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Launch Control (MAP06) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 6},
    362210: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'En Route (MAP07) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 7},
    362211: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'En Route (MAP07) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 7},
    362212: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hangar (MAP08) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 8},
    362213: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hangar (MAP08) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 8},
    362214: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hangar (MAP08) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 8},
    362215: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP09) - Red skull key',
             'doom_type': 38,
             'episode': 1,
             'map': 9},
    362216: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP09) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 9},
    362217: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP09) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 9},
    362218: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Entryway (MAP10) - Blue skull key',
             'doom_type': 40,
             'episode': 1,
             'map': 10},
    362219: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Entryway (MAP10) - Red skull key',
             'doom_type': 38,
             'episode': 1,
             'map': 10},
    362220: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (MAP11) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 11},
    362221: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (MAP11) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 11},
    362222: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (MAP11) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 11},
    362223: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Power Station (MAP12) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 1},
    362224: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Power Station (MAP12) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 1},
    362225: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Power Station (MAP12) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 1},
    362226: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Ruins (MAP13) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 2},
    362227: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Ruins (MAP13) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 2},
    362228: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Ruins (MAP13) - Blue skull key',
             'doom_type': 40,
             'episode': 2,
             'map': 2},
    362229: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Engineering (MAP14) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 3},
    362230: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Engineering (MAP14) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 3},
    362231: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Engineering (MAP14) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 3},
    362232: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Subsidiary Power (MAP15) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 4},
    362233: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Subsidiary Power (MAP15) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 4},
    362234: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Subsidiary Power (MAP15) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 4},
    362235: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Living Quarters (MAP16) - Blue skull key',
             'doom_type': 40,
             'episode': 2,
             'map': 5},
    362236: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Living Quarters (MAP16) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 5},
    362237: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Living Quarters (MAP16) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 5},
    362238: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Promenade (MAP17) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 6},
    362239: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Promenade (MAP17) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 6},
    362240: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Relay Station (MAP18) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 7},
    362241: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Relay Station (MAP18) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 7},
    362242: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Relay Station (MAP18) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 7},
    362243: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Processing (MAP19) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 8},
    362244: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Processing (MAP19) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 8},
    362245: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Processing (MAP19) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 8},
    362246: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Maintenance (MAP21) - Yellow keycard',
             'doom_type': 6,
             'episode': 3,
             'map': 1},
    362247: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Maintenance (MAP21) - Red keycard',
             'doom_type': 13,
             'episode': 3,
             'map': 1},
    362248: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Maintenance (MAP21) - Blue keycard',
             'doom_type': 5,
             'episode': 3,
             'map': 1},
    362249: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Specimen Storage (MAP22) - Yellow keycard',
             'doom_type': 6,
             'episode': 3,
             'map': 2},
    362250: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Specimen Storage (MAP22) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 2},
    362251: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Specimen Storage (MAP22) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 2},
    362252: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Alpha (MAP23) - Blue keycard',
             'doom_type': 5,
             'episode': 3,
             'map': 3},
    362253: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Alpha (MAP23) - Yellow keycard',
             'doom_type': 6,
             'episode': 3,
             'map': 3},
    362254: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Alpha (MAP23) - Red keycard',
             'doom_type': 13,
             'episode': 3,
             'map': 3},
    362255: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sub-Laboratory (MAP24) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 4},
    362256: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sub-Laboratory (MAP24) - Blue keycard',
             'doom_type': 5,
             'episode': 3,
             'map': 4},
    362257: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sub-Laboratory (MAP24) - Yellow keycard',
             'doom_type': 6,
             'episode': 3,
             'map': 4},
    362258: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory (MAP25) - Blue keycard',
             'doom_type': 5,
             'episode': 3,
             'map': 5},
    362259: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory (MAP25) - Red keycard',
             'doom_type': 13,
             'episode': 3,
             'map': 5},
    362260: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory (MAP25) - Yellow keycard',
             'doom_type': 6,
             'episode': 3,
             'map': 5},
    362261: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory II (MAP26) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 6},
    362262: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory II (MAP26) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 6},
    362263: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Beta (MAP27) - Blue keycard',
             'doom_type': 5,
             'episode': 3,
             'map': 7},
    362264: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Beta (MAP27) - Red keycard',
             'doom_type': 13,
             'episode': 3,
             'map': 7},
    362265: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Beta (MAP27) - Yellow keycard',
             'doom_type': 6,
             'episode': 3,
             'map': 7},
    362266: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unknown (MAP28) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 8},
    362267: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unknown (MAP28) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 8},
    362268: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Secret (MAP31) - Red keycard',
             'doom_type': 13,
             'episode': 4,
             'map': 1},
    362269: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Super-Secret (MAP32) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 2},
    362400: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Barracks (MAP01)',
             'doom_type': -1,
             'episode': 1,
             'map': 1},
    362401: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Barracks (MAP01) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 1},
    362402: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Barracks (MAP01) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 1},
    362403: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Outskirts (MAP02)',
             'doom_type': -1,
             'episode': 1,
             'map': 2},
    362404: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Outskirts (MAP02) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 2},
    362405: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Outskirts (MAP02) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 2},
    362406: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Downtown (MAP03)',
             'doom_type': -1,
             'episode': 1,
             'map': 3},
    362407: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Downtown (MAP03) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 3},
    362408: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Downtown (MAP03) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 3},
    362409: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Industrial Zone (MAP04)',
             'doom_type': -1,
             'episode': 1,
             'map': 4},
    362410: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Industrial Zone (MAP04) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 4},
    362411: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Industrial Zone (MAP04) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 4},
    362412: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Depot (MAP05)',
             'doom_type': -1,
             'episode': 1,
             'map': 5},
    362413: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Depot (MAP05) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 5},
    362414: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Depot (MAP05) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 5},
    362415: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Launch Control (MAP06)',
             'doom_type': -1,
             'episode': 1,
             'map': 6},
    362416: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Launch Control (MAP06) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 6},
    362417: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Launch Control (MAP06) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 6},
    362418: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'En Route (MAP07)',
             'doom_type': -1,
             'episode': 1,
             'map': 7},
    362419: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'En Route (MAP07) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 7},
    362420: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'En Route (MAP07) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 7},
    362421: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hangar (MAP08)',
             'doom_type': -1,
             'episode': 1,
             'map': 8},
    362422: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hangar (MAP08) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 8},
    362423: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Hangar (MAP08) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 8},
    362424: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP09)',
             'doom_type': -1,
             'episode': 1,
             'map': 9},
    362425: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP09) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 9},
    362426: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Cargo Bay (MAP09) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 9},
    362427: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Entryway (MAP10)',
             'doom_type': -1,
             'episode': 1,
             'map': 10},
    362428: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Entryway (MAP10) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 10},
    362429: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Entryway (MAP10) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 10},
    362430: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (MAP11)',
             'doom_type': -1,
             'episode': 1,
             'map': 11},
    362431: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (MAP11) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 11},
    362432: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Command Control (MAP11) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 11},
    362433: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Power Station (MAP12)',
             'doom_type': -1,
             'episode': 2,
             'map': 1},
    362434: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Power Station (MAP12) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 1},
    362435: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Power Station (MAP12) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 1},
    362436: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Ruins (MAP13)',
             'doom_type': -1,
             'episode': 2,
             'map': 2},
    362437: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Ruins (MAP13) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 2},
    362438: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Ruins (MAP13) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 2},
    362439: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Engineering (MAP14)',
             'doom_type': -1,
             'episode': 2,
             'map': 3},
    362440: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Engineering (MAP14) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 3},
    362441: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Engineering (MAP14) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 3},
    362442: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Subsidiary Power (MAP15)',
             'doom_type': -1,
             'episode': 2,
             'map': 4},
    362443: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Subsidiary Power (MAP15) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 4},
    362444: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Subsidiary Power (MAP15) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 4},
    362445: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Living Quarters (MAP16)',
             'doom_type': -1,
             'episode': 2,
             'map': 5},
    362446: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Living Quarters (MAP16) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 5},
    362447: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Living Quarters (MAP16) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 5},
    362448: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Promenade (MAP17)',
             'doom_type': -1,
             'episode': 2,
             'map': 6},
    362449: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Promenade (MAP17) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 6},
    362450: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Promenade (MAP17) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 6},
    362451: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Relay Station (MAP18)',
             'doom_type': -1,
             'episode': 2,
             'map': 7},
    362452: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Relay Station (MAP18) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 7},
    362453: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Relay Station (MAP18) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 7},
    362454: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Processing (MAP19)',
             'doom_type': -1,
             'episode': 2,
             'map': 8},
    362455: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Processing (MAP19) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 8},
    362456: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Waste Processing (MAP19) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 8},
    362457: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Reactor (MAP20)',
             'doom_type': -1,
             'episode': 2,
             'map': 9},
    362458: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Reactor (MAP20) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 9},
    362459: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Reactor (MAP20) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 9},
    362460: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Maintenance (MAP21)',
             'doom_type': -1,
             'episode': 3,
             'map': 1},
    362461: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Maintenance (MAP21) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 1},
    362462: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Maintenance (MAP21) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 1},
    362463: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Specimen Storage (MAP22)',
             'doom_type': -1,
             'episode': 3,
             'map': 2},
    362464: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Specimen Storage (MAP22) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 2},
    362465: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Specimen Storage (MAP22) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 2},
    362466: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Alpha (MAP23)',
             'doom_type': -1,
             'episode': 3,
             'map': 3},
    362467: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Alpha (MAP23) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 3},
    362468: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Dispensary Alpha (MAP23) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 3},
    362469: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sub-Laboratory (MAP24)',
             'doom_type': -1,
             'episode': 3,
             'map': 4},
    362470: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sub-Laboratory (MAP24) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 4},
    362471: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Sub-Laboratory (MAP24) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 4},
    362472: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory (MAP25)',
             'doom_type': -1,
             'episode': 3,
             'map': 5},
    362473: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory (MAP25) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 5},
    362474: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Main Laboratory (MAP25) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 5},
    362475: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory II (MAP26)',
             'doom_type': -1,
             'episode': 3,
             'map': 6},
    362476: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Main Laboratory II (MAP26) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 6},
    362477: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Main Laboratory II (MAP26) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 6},
    362478: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Beta (MAP27)',
             'doom_type': -1,
             'episode': 3,
             'map': 7},
    362479: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dispensary Beta (MAP27) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 7},
    362480: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Dispensary Beta (MAP27) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 7},
    362481: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unknown (MAP28)',
             'doom_type': -1,
             'episode': 3,
             'map': 8},
    362482: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unknown (MAP28) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 8},
    362483: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Unknown (MAP28) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 8},
    362484: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Self-Destruct (MAP29)',
             'doom_type': -1,
             'episode': 3,
             'map': 9},
    362485: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Self-Destruct (MAP29) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 9},
    362486: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Self-Destruct (MAP29) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 9},
    362487: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Boss (MAP30)',
             'doom_type': -1,
             'episode': 3,
             'map': 10},
    362488: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Boss (MAP30) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 10},
    362489: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Boss (MAP30) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 10},
    362490: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Secret (MAP31)',
             'doom_type': -1,
             'episode': 4,
             'map': 1},
    362491: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Secret (MAP31) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 1},
    362492: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Secret (MAP31) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 1},
    362493: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Super-Secret (MAP32)',
             'doom_type': -1,
             'episode': 4,
             'map': 2},
    362494: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Super-Secret (MAP32) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 2},
    362495: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Super-Secret (MAP32) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 2},
    362600: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Bullet capacity',
             'doom_type': 65001,
             'episode': -1,
             'map': -1},
    362601: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Shell capacity',
             'doom_type': 65002,
             'episode': -1,
             'map': -1},
    362602: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Battery capacity',
             'doom_type': 65003,
             'episode': -1,
             'map': -1},
    362603: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Rocket capacity',
             'doom_type': 65004,
             'episode': -1,
             'map': -1},
}


item_name_groups: Dict[str, Set[str]] = {
    'Ammos': {'Battery', 'Box of bullets', 'Box of rockets', 'Box of shotgun shells', },
    'Capacity upgrades': {'Backpack', 'Battery capacity', 'Bullet capacity', 'Rocket capacity', 'Shell capacity', },
    'Computer area maps': {'Barracks (MAP01) - Computer area map', 'Boss (MAP30) - Computer area map', 'Cargo Bay (MAP09) - Computer area map', 'Command Control (MAP11) - Computer area map', 'Depot (MAP05) - Computer area map', 'Dispensary Alpha (MAP23) - Computer area map', 'Dispensary Beta (MAP27) - Computer area map', 'Downtown (MAP03) - Computer area map', 'En Route (MAP07) - Computer area map', 'Engineering (MAP14) - Computer area map', 'Entryway (MAP10) - Computer area map', 'Hangar (MAP08) - Computer area map', 'Industrial Zone (MAP04) - Computer area map', 'Launch Control (MAP06) - Computer area map', 'Living Quarters (MAP16) - Computer area map', 'Main Laboratory (MAP25) - Computer area map', 'Main Laboratory II (MAP26) - Computer area map', 'Maintenance (MAP21) - Computer area map', 'Outskirts (MAP02) - Computer area map', 'Power Station (MAP12) - Computer area map', 'Promenade (MAP17) - Computer area map', 'Reactor (MAP20) - Computer area map', 'Relay Station (MAP18) - Computer area map', 'Ruins (MAP13) - Computer area map', 'Secret (MAP31) - Computer area map', 'Self-Destruct (MAP29) - Computer area map', 'Specimen Storage (MAP22) - Computer area map', 'Sub-Laboratory (MAP24) - Computer area map', 'Subsidiary Power (MAP15) - Computer area map', 'Super-Secret (MAP32) - Computer area map', 'Unknown (MAP28) - Computer area map', 'Waste Processing (MAP19) - Computer area map', },
    'Keys': {'Barracks (MAP01) - Red keycard', 'Cargo Bay (MAP09) - Blue keycard', 'Cargo Bay (MAP09) - Red skull key', 'Cargo Bay (MAP09) - Yellow keycard', 'Command Control (MAP11) - Blue keycard', 'Command Control (MAP11) - Red keycard', 'Command Control (MAP11) - Yellow keycard', 'Depot (MAP05) - Red keycard', 'Dispensary Alpha (MAP23) - Blue keycard', 'Dispensary Alpha (MAP23) - Red keycard', 'Dispensary Alpha (MAP23) - Yellow keycard', 'Dispensary Beta (MAP27) - Blue keycard', 'Dispensary Beta (MAP27) - Red keycard', 'Dispensary Beta (MAP27) - Yellow keycard', 'Downtown (MAP03) - Red keycard', 'Downtown (MAP03) - Yellow keycard', 'En Route (MAP07) - Blue keycard', 'En Route (MAP07) - Yellow keycard', 'Engineering (MAP14) - Blue keycard', 'Engineering (MAP14) - Red keycard', 'Engineering (MAP14) - Yellow keycard', 'Entryway (MAP10) - Blue skull key', 'Entryway (MAP10) - Red skull key', 'Hangar (MAP08) - Blue keycard', 'Hangar (MAP08) - Red keycard', 'Hangar (MAP08) - Yellow keycard', 'Industrial Zone (MAP04) - Blue keycard', 'Industrial Zone (MAP04) - Red keycard', 'Launch Control (MAP06) - Blue keycard', 'Launch Control (MAP06) - Red keycard', 'Living Quarters (MAP16) - Blue skull key', 'Living Quarters (MAP16) - Red skull key', 'Living Quarters (MAP16) - Yellow skull key', 'Main Laboratory (MAP25) - Blue keycard', 'Main Laboratory (MAP25) - Red keycard', 'Main Laboratory (MAP25) - Yellow keycard', 'Main Laboratory II (MAP26) - Blue skull key', 'Main Laboratory II (MAP26) - Yellow skull key', 'Maintenance (MAP21) - Blue keycard', 'Maintenance (MAP21) - Red keycard', 'Maintenance (MAP21) - Yellow keycard', 'Outskirts (MAP02) - Blue skull key', 'Outskirts (MAP02) - Red skull key', 'Power Station (MAP12) - Blue keycard', 'Power Station (MAP12) - Red keycard', 'Power Station (MAP12) - Yellow keycard', 'Promenade (MAP17) - Blue keycard', 'Promenade (MAP17) - Red keycard', 'Relay Station (MAP18) - Blue keycard', 'Relay Station (MAP18) - Red keycard', 'Relay Station (MAP18) - Yellow keycard', 'Ruins (MAP13) - Blue skull key', 'Ruins (MAP13) - Red skull key', 'Ruins (MAP13) - Yellow skull key', 'Secret (MAP31) - Red keycard', 'Specimen Storage (MAP22) - Blue skull key', 'Specimen Storage (MAP22) - Red skull key', 'Specimen Storage (MAP22) - Yellow keycard', 'Sub-Laboratory (MAP24) - Blue keycard', 'Sub-Laboratory (MAP24) - Red skull key', 'Sub-Laboratory (MAP24) - Yellow keycard', 'Subsidiary Power (MAP15) - Blue keycard', 'Subsidiary Power (MAP15) - Red keycard', 'Subsidiary Power (MAP15) - Yellow keycard', 'Super-Secret (MAP32) - Red skull key', 'Unknown (MAP28) - Red skull key', 'Unknown (MAP28) - Yellow skull key', 'Waste Processing (MAP19) - Blue keycard', 'Waste Processing (MAP19) - Red keycard', 'Waste Processing (MAP19) - Yellow keycard', },
    'Levels': {'Barracks (MAP01)', 'Boss (MAP30)', 'Cargo Bay (MAP09)', 'Command Control (MAP11)', 'Depot (MAP05)', 'Dispensary Alpha (MAP23)', 'Dispensary Beta (MAP27)', 'Downtown (MAP03)', 'En Route (MAP07)', 'Engineering (MAP14)', 'Entryway (MAP10)', 'Hangar (MAP08)', 'Industrial Zone (MAP04)', 'Launch Control (MAP06)', 'Living Quarters (MAP16)', 'Main Laboratory (MAP25)', 'Main Laboratory II (MAP26)', 'Maintenance (MAP21)', 'Outskirts (MAP02)', 'Power Station (MAP12)', 'Promenade (MAP17)', 'Reactor (MAP20)', 'Relay Station (MAP18)', 'Ruins (MAP13)', 'Secret (MAP31)', 'Self-Destruct (MAP29)', 'Specimen Storage (MAP22)', 'Sub-Laboratory (MAP24)', 'Subsidiary Power (MAP15)', 'Super-Secret (MAP32)', 'Unknown (MAP28)', 'Waste Processing (MAP19)', },
    'MAP01': {'Barracks (MAP01)', },
    'MAP01 Keys': {'Barracks (MAP01) - Red keycard', },
    'MAP01 Map': {'Barracks (MAP01) - Computer area map', },
    'MAP01 Red': {'Barracks (MAP01) - Red keycard', },
    'MAP02': {'Outskirts (MAP02)', },
    'MAP02 Blue': {'Outskirts (MAP02) - Blue skull key', },
    'MAP02 Keys': {'Outskirts (MAP02) - Blue skull key', 'Outskirts (MAP02) - Red skull key', },
    'MAP02 Map': {'Outskirts (MAP02) - Computer area map', },
    'MAP02 Red': {'Outskirts (MAP02) - Red skull key', },
    'MAP03': {'Downtown (MAP03)', },
    'MAP03 Keys': {'Downtown (MAP03) - Red keycard', 'Downtown (MAP03) - Yellow keycard', },
    'MAP03 Map': {'Downtown (MAP03) - Computer area map', },
    'MAP03 Red': {'Downtown (MAP03) - Red keycard', },
    'MAP03 Yellow': {'Downtown (MAP03) - Yellow keycard', },
    'MAP04': {'Industrial Zone (MAP04)', },
    'MAP04 Blue': {'Industrial Zone (MAP04) - Blue keycard', },
    'MAP04 Keys': {'Industrial Zone (MAP04) - Blue keycard', 'Industrial Zone (MAP04) - Red keycard', },
    'MAP04 Map': {'Industrial Zone (MAP04) - Computer area map', },
    'MAP04 Red': {'Industrial Zone (MAP04) - Red keycard', },
    'MAP05': {'Depot (MAP05)', },
    'MAP05 Keys': {'Depot (MAP05) - Red keycard', },
    'MAP05 Map': {'Depot (MAP05) - Computer area map', },
    'MAP05 Red': {'Depot (MAP05) - Red keycard', },
    'MAP06': {'Launch Control (MAP06)', },
    'MAP06 Blue': {'Launch Control (MAP06) - Blue keycard', },
    'MAP06 Keys': {'Launch Control (MAP06) - Blue keycard', 'Launch Control (MAP06) - Red keycard', },
    'MAP06 Map': {'Launch Control (MAP06) - Computer area map', },
    'MAP06 Red': {'Launch Control (MAP06) - Red keycard', },
    'MAP07': {'En Route (MAP07)', },
    'MAP07 Blue': {'En Route (MAP07) - Blue keycard', },
    'MAP07 Keys': {'En Route (MAP07) - Blue keycard', 'En Route (MAP07) - Yellow keycard', },
    'MAP07 Map': {'En Route (MAP07) - Computer area map', },
    'MAP07 Yellow': {'En Route (MAP07) - Yellow keycard', },
    'MAP08': {'Hangar (MAP08)', },
    'MAP08 Blue': {'Hangar (MAP08) - Blue keycard', },
    'MAP08 Keys': {'Hangar (MAP08) - Blue keycard', 'Hangar (MAP08) - Red keycard', 'Hangar (MAP08) - Yellow keycard', },
    'MAP08 Map': {'Hangar (MAP08) - Computer area map', },
    'MAP08 Red': {'Hangar (MAP08) - Red keycard', },
    'MAP08 Yellow': {'Hangar (MAP08) - Yellow keycard', },
    'MAP09': {'Cargo Bay (MAP09)', },
    'MAP09 Blue': {'Cargo Bay (MAP09) - Blue keycard', },
    'MAP09 Keys': {'Cargo Bay (MAP09) - Blue keycard', 'Cargo Bay (MAP09) - Red skull key', 'Cargo Bay (MAP09) - Yellow keycard', },
    'MAP09 Map': {'Cargo Bay (MAP09) - Computer area map', },
    'MAP09 Red': {'Cargo Bay (MAP09) - Red skull key', },
    'MAP09 Yellow': {'Cargo Bay (MAP09) - Yellow keycard', },
    'MAP10': {'Entryway (MAP10)', },
    'MAP10 Blue': {'Entryway (MAP10) - Blue skull key', },
    'MAP10 Keys': {'Entryway (MAP10) - Blue skull key', 'Entryway (MAP10) - Red skull key', },
    'MAP10 Map': {'Entryway (MAP10) - Computer area map', },
    'MAP10 Red': {'Entryway (MAP10) - Red skull key', },
    'MAP11': {'Command Control (MAP11)', },
    'MAP11 Blue': {'Command Control (MAP11) - Blue keycard', },
    'MAP11 Keys': {'Command Control (MAP11) - Blue keycard', 'Command Control (MAP11) - Red keycard', 'Command Control (MAP11) - Yellow keycard', },
    'MAP11 Map': {'Command Control (MAP11) - Computer area map', },
    'MAP11 Red': {'Command Control (MAP11) - Red keycard', },
    'MAP11 Yellow': {'Command Control (MAP11) - Yellow keycard', },
    'MAP12': {'Power Station (MAP12)', },
    'MAP12 Blue': {'Power Station (MAP12) - Blue keycard', },
    'MAP12 Keys': {'Power Station (MAP12) - Blue keycard', 'Power Station (MAP12) - Red keycard', 'Power Station (MAP12) - Yellow keycard', },
    'MAP12 Map': {'Power Station (MAP12) - Computer area map', },
    'MAP12 Red': {'Power Station (MAP12) - Red keycard', },
    'MAP12 Yellow': {'Power Station (MAP12) - Yellow keycard', },
    'MAP13': {'Ruins (MAP13)', },
    'MAP13 Blue': {'Ruins (MAP13) - Blue skull key', },
    'MAP13 Keys': {'Ruins (MAP13) - Blue skull key', 'Ruins (MAP13) - Red skull key', 'Ruins (MAP13) - Yellow skull key', },
    'MAP13 Map': {'Ruins (MAP13) - Computer area map', },
    'MAP13 Red': {'Ruins (MAP13) - Red skull key', },
    'MAP13 Yellow': {'Ruins (MAP13) - Yellow skull key', },
    'MAP14': {'Engineering (MAP14)', },
    'MAP14 Blue': {'Engineering (MAP14) - Blue keycard', },
    'MAP14 Keys': {'Engineering (MAP14) - Blue keycard', 'Engineering (MAP14) - Red keycard', 'Engineering (MAP14) - Yellow keycard', },
    'MAP14 Map': {'Engineering (MAP14) - Computer area map', },
    'MAP14 Red': {'Engineering (MAP14) - Red keycard', },
    'MAP14 Yellow': {'Engineering (MAP14) - Yellow keycard', },
    'MAP15': {'Subsidiary Power (MAP15)', },
    'MAP15 Blue': {'Subsidiary Power (MAP15) - Blue keycard', },
    'MAP15 Keys': {'Subsidiary Power (MAP15) - Blue keycard', 'Subsidiary Power (MAP15) - Red keycard', 'Subsidiary Power (MAP15) - Yellow keycard', },
    'MAP15 Map': {'Subsidiary Power (MAP15) - Computer area map', },
    'MAP15 Red': {'Subsidiary Power (MAP15) - Red keycard', },
    'MAP15 Yellow': {'Subsidiary Power (MAP15) - Yellow keycard', },
    'MAP16': {'Living Quarters (MAP16)', },
    'MAP16 Blue': {'Living Quarters (MAP16) - Blue skull key', },
    'MAP16 Keys': {'Living Quarters (MAP16) - Blue skull key', 'Living Quarters (MAP16) - Red skull key', 'Living Quarters (MAP16) - Yellow skull key', },
    'MAP16 Map': {'Living Quarters (MAP16) - Computer area map', },
    'MAP16 Red': {'Living Quarters (MAP16) - Red skull key', },
    'MAP16 Yellow': {'Living Quarters (MAP16) - Yellow skull key', },
    'MAP17': {'Promenade (MAP17)', },
    'MAP17 Blue': {'Promenade (MAP17) - Blue keycard', },
    'MAP17 Keys': {'Promenade (MAP17) - Blue keycard', 'Promenade (MAP17) - Red keycard', },
    'MAP17 Map': {'Promenade (MAP17) - Computer area map', },
    'MAP17 Red': {'Promenade (MAP17) - Red keycard', },
    'MAP18': {'Relay Station (MAP18)', },
    'MAP18 Blue': {'Relay Station (MAP18) - Blue keycard', },
    'MAP18 Keys': {'Relay Station (MAP18) - Blue keycard', 'Relay Station (MAP18) - Red keycard', 'Relay Station (MAP18) - Yellow keycard', },
    'MAP18 Map': {'Relay Station (MAP18) - Computer area map', },
    'MAP18 Red': {'Relay Station (MAP18) - Red keycard', },
    'MAP18 Yellow': {'Relay Station (MAP18) - Yellow keycard', },
    'MAP19': {'Waste Processing (MAP19)', },
    'MAP19 Blue': {'Waste Processing (MAP19) - Blue keycard', },
    'MAP19 Keys': {'Waste Processing (MAP19) - Blue keycard', 'Waste Processing (MAP19) - Red keycard', 'Waste Processing (MAP19) - Yellow keycard', },
    'MAP19 Map': {'Waste Processing (MAP19) - Computer area map', },
    'MAP19 Red': {'Waste Processing (MAP19) - Red keycard', },
    'MAP19 Yellow': {'Waste Processing (MAP19) - Yellow keycard', },
    'MAP20': {'Reactor (MAP20)', },
    'MAP20 Map': {'Reactor (MAP20) - Computer area map', },
    'MAP21': {'Maintenance (MAP21)', },
    'MAP21 Blue': {'Maintenance (MAP21) - Blue keycard', },
    'MAP21 Keys': {'Maintenance (MAP21) - Blue keycard', 'Maintenance (MAP21) - Red keycard', 'Maintenance (MAP21) - Yellow keycard', },
    'MAP21 Map': {'Maintenance (MAP21) - Computer area map', },
    'MAP21 Red': {'Maintenance (MAP21) - Red keycard', },
    'MAP21 Yellow': {'Maintenance (MAP21) - Yellow keycard', },
    'MAP22': {'Specimen Storage (MAP22)', },
    'MAP22 Blue': {'Specimen Storage (MAP22) - Blue skull key', },
    'MAP22 Keys': {'Specimen Storage (MAP22) - Blue skull key', 'Specimen Storage (MAP22) - Red skull key', 'Specimen Storage (MAP22) - Yellow keycard', },
    'MAP22 Map': {'Specimen Storage (MAP22) - Computer area map', },
    'MAP22 Red': {'Specimen Storage (MAP22) - Red skull key', },
    'MAP22 Yellow': {'Specimen Storage (MAP22) - Yellow keycard', },
    'MAP23': {'Dispensary Alpha (MAP23)', },
    'MAP23 Blue': {'Dispensary Alpha (MAP23) - Blue keycard', },
    'MAP23 Keys': {'Dispensary Alpha (MAP23) - Blue keycard', 'Dispensary Alpha (MAP23) - Red keycard', 'Dispensary Alpha (MAP23) - Yellow keycard', },
    'MAP23 Map': {'Dispensary Alpha (MAP23) - Computer area map', },
    'MAP23 Red': {'Dispensary Alpha (MAP23) - Red keycard', },
    'MAP23 Yellow': {'Dispensary Alpha (MAP23) - Yellow keycard', },
    'MAP24': {'Sub-Laboratory (MAP24)', },
    'MAP24 Blue': {'Sub-Laboratory (MAP24) - Blue keycard', },
    'MAP24 Keys': {'Sub-Laboratory (MAP24) - Blue keycard', 'Sub-Laboratory (MAP24) - Red skull key', 'Sub-Laboratory (MAP24) - Yellow keycard', },
    'MAP24 Map': {'Sub-Laboratory (MAP24) - Computer area map', },
    'MAP24 Red': {'Sub-Laboratory (MAP24) - Red skull key', },
    'MAP24 Yellow': {'Sub-Laboratory (MAP24) - Yellow keycard', },
    'MAP25': {'Main Laboratory (MAP25)', },
    'MAP25 Blue': {'Main Laboratory (MAP25) - Blue keycard', },
    'MAP25 Keys': {'Main Laboratory (MAP25) - Blue keycard', 'Main Laboratory (MAP25) - Red keycard', 'Main Laboratory (MAP25) - Yellow keycard', },
    'MAP25 Map': {'Main Laboratory (MAP25) - Computer area map', },
    'MAP25 Red': {'Main Laboratory (MAP25) - Red keycard', },
    'MAP25 Yellow': {'Main Laboratory (MAP25) - Yellow keycard', },
    'MAP26': {'Main Laboratory II (MAP26)', },
    'MAP26 Blue': {'Main Laboratory II (MAP26) - Blue skull key', },
    'MAP26 Keys': {'Main Laboratory II (MAP26) - Blue skull key', 'Main Laboratory II (MAP26) - Yellow skull key', },
    'MAP26 Map': {'Main Laboratory II (MAP26) - Computer area map', },
    'MAP26 Yellow': {'Main Laboratory II (MAP26) - Yellow skull key', },
    'MAP27': {'Dispensary Beta (MAP27)', },
    'MAP27 Blue': {'Dispensary Beta (MAP27) - Blue keycard', },
    'MAP27 Keys': {'Dispensary Beta (MAP27) - Blue keycard', 'Dispensary Beta (MAP27) - Red keycard', 'Dispensary Beta (MAP27) - Yellow keycard', },
    'MAP27 Map': {'Dispensary Beta (MAP27) - Computer area map', },
    'MAP27 Red': {'Dispensary Beta (MAP27) - Red keycard', },
    'MAP27 Yellow': {'Dispensary Beta (MAP27) - Yellow keycard', },
    'MAP28': {'Unknown (MAP28)', },
    'MAP28 Keys': {'Unknown (MAP28) - Red skull key', 'Unknown (MAP28) - Yellow skull key', },
    'MAP28 Map': {'Unknown (MAP28) - Computer area map', },
    'MAP28 Red': {'Unknown (MAP28) - Red skull key', },
    'MAP28 Yellow': {'Unknown (MAP28) - Yellow skull key', },
    'MAP29': {'Self-Destruct (MAP29)', },
    'MAP29 Map': {'Self-Destruct (MAP29) - Computer area map', },
    'MAP30': {'Boss (MAP30)', },
    'MAP30 Map': {'Boss (MAP30) - Computer area map', },
    'MAP31': {'Secret (MAP31)', },
    'MAP31 Keys': {'Secret (MAP31) - Red keycard', },
    'MAP31 Map': {'Secret (MAP31) - Computer area map', },
    'MAP31 Red': {'Secret (MAP31) - Red keycard', },
    'MAP32': {'Super-Secret (MAP32)', },
    'MAP32 Keys': {'Super-Secret (MAP32) - Red skull key', },
    'MAP32 Map': {'Super-Secret (MAP32) - Computer area map', },
    'MAP32 Red': {'Super-Secret (MAP32) - Red skull key', },
    'Powerups': {'Armor', 'Berserk', 'Invulnerability', 'Mega Armor', 'Megasphere', 'Partial invisibility', 'Supercharge', },
    'Weapons': {'Chaingun', 'Chainsaw', 'NFG', 'Psychic blaster', 'Rocket launcher', 'Sawed-off shotgun', 'Super shotgun', },
}
