# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from typing import List
from BaseClasses import TypedDict

class ConnectionDict(TypedDict, total=False):
    target: str
    pro: bool

class RegionDict(TypedDict, total=False):
    name: str
    connects_to_hub: bool
    episode: int
    connections: List[ConnectionDict]


regions:List[RegionDict] = [
    # Barracks (MAP01)
    {"name":"Barracks (MAP01) Main",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"Barracks (MAP01) Red","pro":False}]},
    {"name":"Barracks (MAP01) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Barracks (MAP01) Main","pro":False}]},

    # Outskirts (MAP02)
    {"name":"Outskirts (MAP02) Main",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"Outskirts (MAP02) Blue","pro":False}]},
    {"name":"Outskirts (MAP02) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Outskirts (MAP02) Main","pro":False},
        {"target":"Outskirts (MAP02) Red","pro":False}]},
    {"name":"Outskirts (MAP02) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Outskirts (MAP02) Blue","pro":False}]},

    # Downtown (MAP03)
    {"name":"Downtown (MAP03) Outside",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"Downtown (MAP03) Main","pro":False}]},
    {"name":"Downtown (MAP03) Main",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Downtown (MAP03) Outside","pro":False},
        {"target":"Downtown (MAP03) Yellow","pro":False}]},
    {"name":"Downtown (MAP03) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Downtown (MAP03) Yellow","pro":False}]},
    {"name":"Downtown (MAP03) Yellow",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Downtown (MAP03) Main","pro":False},
        {"target":"Downtown (MAP03) Red","pro":False}]},

    # Industrial Zone (MAP04)
    {"name":"Industrial Zone (MAP04) Main",
     "connects_to_hub":True,
     "episode":1,
     "connections":[
        {"target":"Industrial Zone (MAP04) Blue","pro":False},
        {"target":"Industrial Zone (MAP04) Red","pro":False}]},
    {"name":"Industrial Zone (MAP04) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Industrial Zone (MAP04) Main","pro":False}]},
    {"name":"Industrial Zone (MAP04) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[]},

    # Depot (MAP05)
    {"name":"Depot (MAP05) Main",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"Depot (MAP05) Red","pro":False}]},
    {"name":"Depot (MAP05) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Depot (MAP05) Main","pro":False}]},

    # Launch Control (MAP06)
    {"name":"Launch Control (MAP06) Main",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"Launch Control (MAP06) Blue","pro":False}]},
    {"name":"Launch Control (MAP06) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Launch Control (MAP06) Main","pro":False},
        {"target":"Launch Control (MAP06) Red","pro":False}]},
    {"name":"Launch Control (MAP06) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Launch Control (MAP06) Blue","pro":False}]},

    # En Route (MAP07)
    {"name":"En Route (MAP07) Main",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"En Route (MAP07) Blue","pro":False},
        {"target":"En Route (MAP07) Starting Room","pro":False},
        {"target":"En Route (MAP07) Yellow","pro":False}]},
    {"name":"En Route (MAP07) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"En Route (MAP07) Main","pro":False}]},
    {"name":"En Route (MAP07) Starting Room",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"En Route (MAP07) Main","pro":False}]},
    {"name":"En Route (MAP07) Yellow",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"En Route (MAP07) Main","pro":False}]},

    # Hangar (MAP08)
    {"name":"Hangar (MAP08) Start",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"Hangar (MAP08) Main","pro":False}]},
    {"name":"Hangar (MAP08) Main",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Hangar (MAP08) Start","pro":False},
        {"target":"Hangar (MAP08) Red","pro":False},
        {"target":"Hangar (MAP08) Blue","pro":False}]},
    {"name":"Hangar (MAP08) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Hangar (MAP08) Main","pro":False}]},
    {"name":"Hangar (MAP08) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Hangar (MAP08) Main","pro":False},
        {"target":"Hangar (MAP08) Yellow","pro":False}]},
    {"name":"Hangar (MAP08) Yellow",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Hangar (MAP08) Blue","pro":False}]},

    # Cargo Bay (MAP09)
    {"name":"Cargo Bay (MAP09) Start",
     "connects_to_hub":True,
     "episode":1,
     "connections":[{"target":"Cargo Bay (MAP09) Main","pro":False}]},
    {"name":"Cargo Bay (MAP09) Main",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Cargo Bay (MAP09) Start","pro":False},
        {"target":"Cargo Bay (MAP09) Red","pro":False},
        {"target":"Cargo Bay (MAP09) Yellow","pro":False},
        {"target":"Cargo Bay (MAP09) Blue","pro":False}]},
    {"name":"Cargo Bay (MAP09) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Cargo Bay (MAP09) Main","pro":False}]},
    {"name":"Cargo Bay (MAP09) Yellow",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Cargo Bay (MAP09) Main","pro":False}]},
    {"name":"Cargo Bay (MAP09) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Cargo Bay (MAP09) Main","pro":False}]},

    # Entryway (MAP10)
    {"name":"Entryway (MAP10) Main",
     "connects_to_hub":True,
     "episode":1,
     "connections":[
        {"target":"Entryway (MAP10) Baron Room","pro":False},
        {"target":"Entryway (MAP10) Blue","pro":False},
        {"target":"Entryway (MAP10) Linedef Skip","pro":True}]},
    {"name":"Entryway (MAP10) Baron Room",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Entryway (MAP10) Main","pro":False}]},
    {"name":"Entryway (MAP10) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Entryway (MAP10) Main","pro":False}]},
    {"name":"Entryway (MAP10) Linedef Skip",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Entryway (MAP10) Blue","pro":False}]},

    # Command Control (MAP11)
    {"name":"Command Control (MAP11) Main",
     "connects_to_hub":True,
     "episode":1,
     "connections":[
        {"target":"Command Control (MAP11) Blue","pro":False},
        {"target":"Command Control (MAP11) Yellow","pro":False}]},
    {"name":"Command Control (MAP11) Blue",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Command Control (MAP11) Main","pro":False}]},
    {"name":"Command Control (MAP11) Yellow",
     "connects_to_hub":False,
     "episode":1,
     "connections":[
        {"target":"Command Control (MAP11) Main","pro":False},
        {"target":"Command Control (MAP11) Red","pro":False}]},
    {"name":"Command Control (MAP11) Red",
     "connects_to_hub":False,
     "episode":1,
     "connections":[{"target":"Command Control (MAP11) Yellow","pro":False}]},

    # Power Station (MAP12)
    {"name":"Power Station (MAP12) Start",
     "connects_to_hub":True,
     "episode":2,
     "connections":[{"target":"Power Station (MAP12) Main","pro":False}]},
    {"name":"Power Station (MAP12) Main",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Power Station (MAP12) Start","pro":False},
        {"target":"Power Station (MAP12) Barons","pro":False},
        {"target":"Power Station (MAP12) Holobots","pro":False},
        {"target":"Power Station (MAP12) Blue","pro":False}]},
    {"name":"Power Station (MAP12) Holobots",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Power Station (MAP12) Main","pro":False},
        {"target":"Power Station (MAP12) Central","pro":False}]},
    {"name":"Power Station (MAP12) Barons",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Power Station (MAP12) Main","pro":False}]},
    {"name":"Power Station (MAP12) Yellow",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Power Station (MAP12) Central","pro":False}]},
    {"name":"Power Station (MAP12) Central",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Power Station (MAP12) Holobots","pro":False},
        {"target":"Power Station (MAP12) Yellow","pro":False}]},
    {"name":"Power Station (MAP12) Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Power Station (MAP12) Main","pro":False},
        {"target":"Power Station (MAP12) Red","pro":False}]},
    {"name":"Power Station (MAP12) Red",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Power Station (MAP12) Blue","pro":False}]},

    # Ruins (MAP13)
    {"name":"Ruins (MAP13) Entrance",
     "connects_to_hub":True,
     "episode":2,
     "connections":[{"target":"Ruins (MAP13) Main","pro":False}]},
    {"name":"Ruins (MAP13) Main",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Ruins (MAP13) All Keys","pro":False},
        {"target":"Ruins (MAP13) Entrance","pro":False}]},
    {"name":"Ruins (MAP13) All Keys",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Ruins (MAP13) Main","pro":False}]},

    # Engineering (MAP14)
    {"name":"Engineering (MAP14) Main",
     "connects_to_hub":True,
     "episode":2,
     "connections":[
        {"target":"Engineering (MAP14) Blue","pro":False},
        {"target":"Engineering (MAP14) Yellow","pro":False},
        {"target":"Engineering (MAP14) All Keys","pro":False}]},
    {"name":"Engineering (MAP14) Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Engineering (MAP14) Main","pro":False}]},
    {"name":"Engineering (MAP14) Yellow",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Engineering (MAP14) Main","pro":False}]},
    {"name":"Engineering (MAP14) All Keys",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Engineering (MAP14) Main","pro":False}]},

    # Subsidiary Power (MAP15)
    {"name":"Subsidiary Power (MAP15) Main",
     "connects_to_hub":True,
     "episode":2,
     "connections":[
        {"target":"Subsidiary Power (MAP15) Yellow","pro":False},
        {"target":"Subsidiary Power (MAP15) Blue","pro":False}]},
    {"name":"Subsidiary Power (MAP15) Yellow",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Subsidiary Power (MAP15) Main","pro":False}]},
    {"name":"Subsidiary Power (MAP15) Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Subsidiary Power (MAP15) Red","pro":False},
        {"target":"Subsidiary Power (MAP15) Main","pro":False}]},
    {"name":"Subsidiary Power (MAP15) Red",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Subsidiary Power (MAP15) Blue","pro":False}]},

    # Living Quarters (MAP16)
    {"name":"Living Quarters (MAP16) Main",
     "connects_to_hub":True,
     "episode":2,
     "connections":[
        {"target":"Living Quarters (MAP16) Red","pro":False},
        {"target":"Living Quarters (MAP16) Blue","pro":False},
        {"target":"Living Quarters (MAP16) Yellow","pro":False}]},
    {"name":"Living Quarters (MAP16) Red",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Living Quarters (MAP16) Main","pro":False}]},
    {"name":"Living Quarters (MAP16) Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Living Quarters (MAP16) Main","pro":False}]},
    {"name":"Living Quarters (MAP16) Yellow",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Living Quarters (MAP16) Main","pro":False}]},

    # Promenade (MAP17)
    {"name":"Promenade (MAP17) Main",
     "connects_to_hub":True,
     "episode":2,
     "connections":[{"target":"Promenade (MAP17) Blue","pro":False}]},
    {"name":"Promenade (MAP17) Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Promenade (MAP17) Main","pro":False},
        {"target":"Promenade (MAP17) Red","pro":False}]},
    {"name":"Promenade (MAP17) Red",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Promenade (MAP17) Blue","pro":False}]},

    # Relay Station (MAP18)
    {"name":"Relay Station (MAP18) Main",
     "connects_to_hub":True,
     "episode":2,
     "connections":[
        {"target":"Relay Station (MAP18) Blue","pro":False},
        {"target":"Relay Station (MAP18) Yellow Solo","pro":False},
        {"target":"Relay Station (MAP18) Red","pro":False}]},
    {"name":"Relay Station (MAP18) Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Relay Station (MAP18) Main","pro":False},
        {"target":"Relay Station (MAP18) Yellow from Blue","pro":False}]},
    {"name":"Relay Station (MAP18) Yellow Solo",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Relay Station (MAP18) Red","pro":False}]},
    {"name":"Relay Station (MAP18) Yellow from Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Relay Station (MAP18) Blue","pro":False}]},
    {"name":"Relay Station (MAP18) Red",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Relay Station (MAP18) Main","pro":False}]},

    # Waste Processing (MAP19)
    {"name":"Waste Processing (MAP19) Main",
     "connects_to_hub":True,
     "episode":2,
     "connections":[
        {"target":"Waste Processing (MAP19) Yellow","pro":False},
        {"target":"Waste Processing (MAP19) Blue","pro":False}]},
    {"name":"Waste Processing (MAP19) Yellow",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Waste Processing (MAP19) Main","pro":False},
        {"target":"Waste Processing (MAP19) Blue from Yellow","pro":False}]},
    {"name":"Waste Processing (MAP19) Blue",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Waste Processing (MAP19) Main","pro":False}]},
    {"name":"Waste Processing (MAP19) Blue from Yellow",
     "connects_to_hub":False,
     "episode":2,
     "connections":[
        {"target":"Waste Processing (MAP19) Yellow","pro":False},
        {"target":"Waste Processing (MAP19) Red","pro":False}]},
    {"name":"Waste Processing (MAP19) Red",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Waste Processing (MAP19) Blue from Yellow","pro":False}]},

    # Reactor (MAP20)
    {"name":"Reactor (MAP20) Start",
     "connects_to_hub":True,
     "episode":2,
     "connections":[{"target":"Reactor (MAP20) Main","pro":False}]},
    {"name":"Reactor (MAP20) Main",
     "connects_to_hub":False,
     "episode":2,
     "connections":[{"target":"Reactor (MAP20) Start","pro":False}]},

    # Maintenance (MAP21)
    {"name":"Maintenance (MAP21) Main",
     "connects_to_hub":True,
     "episode":3,
     "connections":[
        {"target":"Maintenance (MAP21) Reach Thru","pro":True},
        {"target":"Maintenance (MAP21) Yellow","pro":False},
        {"target":"Maintenance (MAP21) Blue","pro":False}]},
    {"name":"Maintenance (MAP21) Reach Thru",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Maintenance (MAP21) Yellow","pro":False},
        {"target":"Maintenance (MAP21) Blue","pro":False}]},
    {"name":"Maintenance (MAP21) Yellow",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Maintenance (MAP21) Red","pro":False},
        {"target":"Maintenance (MAP21) Main","pro":False}]},
    {"name":"Maintenance (MAP21) Blue",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Maintenance (MAP21) Cacodemons","pro":False},
        {"target":"Maintenance (MAP21) Main","pro":False}]},
    {"name":"Maintenance (MAP21) Red",
     "connects_to_hub":False,
     "episode":3,
     "connections":[]},
    {"name":"Maintenance (MAP21) Cacodemons",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Maintenance (MAP21) Blue","pro":False}]},

    # Specimen Storage (MAP22)
    {"name":"Specimen Storage (MAP22) Start",
     "connects_to_hub":True,
     "episode":3,
     "connections":[{"target":"Specimen Storage (MAP22) Main","pro":False}]},
    {"name":"Specimen Storage (MAP22) Main",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Specimen Storage (MAP22) Start","pro":False},
        {"target":"Specimen Storage (MAP22) Red","pro":False},
        {"target":"Specimen Storage (MAP22) Yellow and Blue","pro":False},
        {"target":"Specimen Storage (MAP22) Blue","pro":False},
        {"target":"Specimen Storage (MAP22) Danger SR40","pro":True}]},
    {"name":"Specimen Storage (MAP22) Red",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Specimen Storage (MAP22) Main","pro":False}]},
    {"name":"Specimen Storage (MAP22) Blue",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Specimen Storage (MAP22) Main","pro":False},
        {"target":"Specimen Storage (MAP22) Danger SR40","pro":False}]},
    {"name":"Specimen Storage (MAP22) Yellow and Blue",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Specimen Storage (MAP22) Main","pro":False}]},
    {"name":"Specimen Storage (MAP22) Danger SR40",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Specimen Storage (MAP22) Main","pro":False}]},

    # Dispensary Alpha (MAP23)
    {"name":"Dispensary Alpha (MAP23) Entry",
     "connects_to_hub":True,
     "episode":3,
     "connections":[{"target":"Dispensary Alpha (MAP23) Main","pro":False}]},
    {"name":"Dispensary Alpha (MAP23) Main",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Dispensary Alpha (MAP23) Entry","pro":False},
        {"target":"Dispensary Alpha (MAP23) Yellow","pro":False},
        {"target":"Dispensary Alpha (MAP23) Blue","pro":False}]},
    {"name":"Dispensary Alpha (MAP23) Yellow",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Dispensary Alpha (MAP23) Main","pro":False},
        {"target":"Dispensary Alpha (MAP23) Red","pro":False},
        {"target":"Dispensary Alpha (MAP23) Wallrun Access","pro":True}]},
    {"name":"Dispensary Alpha (MAP23) Blue",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Dispensary Alpha (MAP23) Main","pro":False}]},
    {"name":"Dispensary Alpha (MAP23) Red",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Dispensary Alpha (MAP23) Yellow","pro":False}]},
    {"name":"Dispensary Alpha (MAP23) Wallrun Access",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Dispensary Alpha (MAP23) Yellow","pro":False}]},

    # Sub-Laboratory (MAP24)
    {"name":"Sub-Laboratory (MAP24) Main",
     "connects_to_hub":True,
     "episode":3,
     "connections":[
        {"target":"Sub-Laboratory (MAP24) Blue","pro":False},
        {"target":"Sub-Laboratory (MAP24) Yellow","pro":False}]},
    {"name":"Sub-Laboratory (MAP24) Blue",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Sub-Laboratory (MAP24) Main","pro":False}]},
    {"name":"Sub-Laboratory (MAP24) Yellow",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Sub-Laboratory (MAP24) Main","pro":False},
        {"target":"Sub-Laboratory (MAP24) Red","pro":False}]},
    {"name":"Sub-Laboratory (MAP24) Red",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Sub-Laboratory (MAP24) Yellow","pro":False}]},

    # Main Laboratory (MAP25)
    {"name":"Main Laboratory (MAP25) Main",
     "connects_to_hub":True,
     "episode":3,
     "connections":[
        {"target":"Main Laboratory (MAP25) Blue","pro":False},
        {"target":"Main Laboratory (MAP25) Red","pro":False},
        {"target":"Main Laboratory (MAP25) Blue Armory","pro":False}]},
    {"name":"Main Laboratory (MAP25) Blue",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Main Laboratory (MAP25) Main","pro":False}]},
    {"name":"Main Laboratory (MAP25) Red",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Main Laboratory (MAP25) Main","pro":False},
        {"target":"Main Laboratory (MAP25) Yellow","pro":False}]},
    {"name":"Main Laboratory (MAP25) Yellow",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Main Laboratory (MAP25) Red","pro":False}]},
    {"name":"Main Laboratory (MAP25) Blue Armory",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Main Laboratory (MAP25) Main","pro":False}]},

    # Main Laboratory II (MAP26)
    {"name":"Main Laboratory II (MAP26) Main",
     "connects_to_hub":True,
     "episode":3,
     "connections":[{"target":"Main Laboratory II (MAP26) Yellow","pro":False}]},
    {"name":"Main Laboratory II (MAP26) Yellow",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Main Laboratory II (MAP26) Main","pro":False},
        {"target":"Main Laboratory II (MAP26) Blue","pro":False}]},
    {"name":"Main Laboratory II (MAP26) Blue",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Main Laboratory II (MAP26) Yellow","pro":False}]},

    # Dispensary Beta (MAP27)
    {"name":"Dispensary Beta (MAP27) Main",
     "connects_to_hub":True,
     "episode":3,
     "connections":[
        {"target":"Dispensary Beta (MAP27) Southern","pro":False},
        {"target":"Dispensary Beta (MAP27) Red","pro":False},
        {"target":"Dispensary Beta (MAP27) Yellow","pro":False}]},
    {"name":"Dispensary Beta (MAP27) Southern",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Dispensary Beta (MAP27) Main","pro":False},
        {"target":"Dispensary Beta (MAP27) Red","pro":False}]},
    {"name":"Dispensary Beta (MAP27) Red",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Dispensary Beta (MAP27) Main","pro":False},
        {"target":"Dispensary Beta (MAP27) Southern","pro":False}]},
    {"name":"Dispensary Beta (MAP27) Yellow",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Dispensary Beta (MAP27) Main","pro":False}]},

    # Unknown (MAP28)
    {"name":"Unknown (MAP28) Main",
     "connects_to_hub":True,
     "episode":3,
     "connections":[{"target":"Unknown (MAP28) Red","pro":False}]},
    {"name":"Unknown (MAP28) Red",
     "connects_to_hub":False,
     "episode":3,
     "connections":[
        {"target":"Unknown (MAP28) Main","pro":False},
        {"target":"Unknown (MAP28) Lords","pro":False}]},
    {"name":"Unknown (MAP28) Lords",
     "connects_to_hub":False,
     "episode":3,
     "connections":[{"target":"Unknown (MAP28) Red","pro":False}]},

    # Self-Destruct (MAP29)
    {"name":"Self-Destruct (MAP29) Main",
     "connects_to_hub":True,
     "episode":3,
     "connections":[]},

    # Boss (MAP30)
    {"name":"Boss (MAP30) Safe Area",
     "connects_to_hub":True,
     "episode":3,
     "connections":[{"target":"Boss (MAP30) Main","pro":False}]},
    {"name":"Boss (MAP30) Main",
     "connects_to_hub":False,
     "episode":3,
     "connections":[]},

    # Secret (MAP31)
    {"name":"Secret (MAP31) Main",
     "connects_to_hub":True,
     "episode":4,
     "connections":[{"target":"Secret (MAP31) Red","pro":False}]},
    {"name":"Secret (MAP31) Red",
     "connects_to_hub":False,
     "episode":4,
     "connections":[{"target":"Secret (MAP31) Main","pro":False}]},

    # Super-Secret (MAP32)
    {"name":"Super-Secret (MAP32) Main",
     "connects_to_hub":True,
     "episode":4,
     "connections":[{"target":"Super-Secret (MAP32) Red","pro":False}]},
    {"name":"Super-Secret (MAP32) Red",
     "connects_to_hub":False,
     "episode":4,
     "connections":[{"target":"Super-Secret (MAP32) Main","pro":False}]},
]
