# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from BaseClasses import ItemClassification
from typing import TypedDict, Dict, Set 


class ItemDict(TypedDict, total=False): 
    classification: ItemClassification 
    count: int 
    name: str 
    doom_type: int # Unique numerical id used to spawn the item. -1 is level item, -2 is level complete item. 
    episode: int # Relevant if that item targets a specific level, like keycard or map reveal pickup. 
    map: int 


item_table: Dict[int, ItemDict] = {
    360000: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shotgun',
             'doom_type': 2001,
             'episode': -1,
             'map': -1},
    360001: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Rocket launcher',
             'doom_type': 2003,
             'episode': -1,
             'map': -1},
    360002: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Plasma gun',
             'doom_type': 2004,
             'episode': -1,
             'map': -1},
    360003: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Chainsaw',
             'doom_type': 2005,
             'episode': -1,
             'map': -1},
    360004: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Chaingun',
             'doom_type': 2002,
             'episode': -1,
             'map': -1},
    360005: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'BFG9000',
             'doom_type': 2006,
             'episode': -1,
             'map': -1},
    360006: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Super Shotgun',
             'doom_type': 82,
             'episode': -1,
             'map': -1},
    360007: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Backpack',
             'doom_type': 8,
             'episode': -1,
             'map': -1},
    360008: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Armor',
             'doom_type': 2018,
             'episode': -1,
             'map': -1},
    360009: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Mega Armor',
             'doom_type': 2019,
             'episode': -1,
             'map': -1},
    360010: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Berserk',
             'doom_type': 2023,
             'episode': -1,
             'map': -1},
    360011: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Invulnerability',
             'doom_type': 2022,
             'episode': -1,
             'map': -1},
    360012: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Partial invisibility',
             'doom_type': 2024,
             'episode': -1,
             'map': -1},
    360013: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Supercharge',
             'doom_type': 2013,
             'episode': -1,
             'map': -1},
    360014: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Megasphere',
             'doom_type': 83,
             'episode': -1,
             'map': -1},
    360015: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Medikit',
             'doom_type': 2012,
             'episode': -1,
             'map': -1},
    360016: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of bullets',
             'doom_type': 2048,
             'episode': -1,
             'map': -1},
    360017: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of rockets',
             'doom_type': 2046,
             'episode': -1,
             'map': -1},
    360018: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of shotgun shells',
             'doom_type': 2049,
             'episode': -1,
             'map': -1},
    360019: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Energy cell pack',
             'doom_type': 17,
             'episode': -1,
             'map': -1},
    360200: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Control Facility (MAP02) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 2},
    360201: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Control Facility (MAP02) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 2},
    360202: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Control Facility (MAP02) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 2},
    360203: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Alleyway (MAP03) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 3},
    360204: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Canyon Hub (MAP04) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 4},
    360205: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Skybase 300 (MAP05) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 5},
    360206: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Skybase 300 (MAP05) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 5},
    360207: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Whispering Corridor (MAP06) - Blue skull key',
             'doom_type': 40,
             'episode': 1,
             'map': 6},
    360208: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Disposal Plant (MAP08) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 8},
    360209: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Disposal Plant (MAP08) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 8},
    360210: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Power Station (MAP09) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 9},
    360211: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Power Station (MAP09) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 9},
    360212: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Power Station (MAP09) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 9},
    360213: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP10) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 10},
    360214: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Simbattle (MAP11) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 1},
    360215: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Simbattle (MAP11) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 1},
    360216: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Simbattle (MAP11) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 1},
    360217: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Villa of Pain (MAP12) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 2},
    360218: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Villa of Pain (MAP12) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 2},
    360219: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dark Crypt (MAP13) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 3},
    360220: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dark Crypt (MAP13) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 3},
    360221: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Circle (MAP14) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 4},
    360222: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Circle (MAP14) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 4},
    360223: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Trouble Town (MAP15) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 5},
    360224: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Trouble Town (MAP15) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 5},
    360225: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Trouble Town (MAP15) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 5},
    360226: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Bruiser Fortress (MAP16) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 6},
    360227: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Constriction (MAP17) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 7},
    360228: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Constriction (MAP17) - Blue skull key',
             'doom_type': 40,
             'episode': 2,
             'map': 7},
    360229: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zombie Hideout (MAP18) - Blue skull key',
             'doom_type': 40,
             'episode': 2,
             'map': 8},
    360230: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zombie Hideout (MAP18) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 8},
    360231: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Invasion (MAP19) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 9},
    360232: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Invasion (MAP19) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 9},
    360233: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Death Row (MAP20) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 10},
    360234: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Death Row (MAP20) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 10},
    360235: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Blood Lust (MAP21) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 1},
    360236: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Firestorm Tomb (MAP22) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 2},
    360237: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Firestorm Tomb (MAP22) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 2},
    360238: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dungeon of Inferno (MAP23) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 3},
    360239: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dungeon of Inferno (MAP23) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 3},
    360240: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cavern of the Evil Spirit (MAP24) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 4},
    360241: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cavern of the Evil Spirit (MAP24) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 4},
    360242: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hellucination (MAP25) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 5},
    360243: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hellucination (MAP25) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 5},
    360244: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hellucination (MAP25) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 5},
    360245: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Valley of Brimstone (MAP26) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 6},
    360246: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dissect (MAP27) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 7},
    360247: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Demise (MAP28) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 8},
    360248: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Demise (MAP28) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 8},
    360249: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Den of Torture (MAP29) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 9},
    360250: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Creepy (MAP31) - Red keycard',
             'doom_type': 13,
             'episode': 4,
             'map': 1},
    360251: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Creepy (MAP31) - Yellow keycard',
             'doom_type': 6,
             'episode': 4,
             'map': 1},
    360252: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Creepy (MAP31) - Blue keycard',
             'doom_type': 5,
             'episode': 4,
             'map': 1},
    360253: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Condemnation (MAP32) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 2},
    360254: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Condemnation (MAP32) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 2},
    360255: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Condemnation (MAP32) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 2},
    360256: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zerstorung (MAP33) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 3},
    360257: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zerstorung (MAP33) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 3},
    360258: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zerstorung (MAP33) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 3},
    360400: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Spaceport (MAP01)',
             'doom_type': -1,
             'episode': 1,
             'map': 1},
    360401: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Spaceport (MAP01) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 1},
    360402: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'The Spaceport (MAP01) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 1},
    360403: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Control Facility (MAP02)',
             'doom_type': -1,
             'episode': 1,
             'map': 2},
    360404: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Control Facility (MAP02) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 2},
    360405: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Control Facility (MAP02) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 2},
    360406: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Alleyway (MAP03)',
             'doom_type': -1,
             'episode': 1,
             'map': 3},
    360407: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Alleyway (MAP03) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 3},
    360408: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'The Alleyway (MAP03) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 3},
    360409: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Canyon Hub (MAP04)',
             'doom_type': -1,
             'episode': 1,
             'map': 4},
    360410: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Canyon Hub (MAP04) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 4},
    360411: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Canyon Hub (MAP04) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 4},
    360412: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Skybase 300 (MAP05)',
             'doom_type': -1,
             'episode': 1,
             'map': 5},
    360413: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Skybase 300 (MAP05) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 5},
    360414: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Skybase 300 (MAP05) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 5},
    360415: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Whispering Corridor (MAP06)',
             'doom_type': -1,
             'episode': 1,
             'map': 6},
    360416: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Whispering Corridor (MAP06) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 6},
    360417: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Whispering Corridor (MAP06) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 6},
    360418: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heavyweight (MAP07)',
             'doom_type': -1,
             'episode': 1,
             'map': 7},
    360419: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Heavyweight (MAP07) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 7},
    360420: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Heavyweight (MAP07) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 7},
    360421: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Disposal Plant (MAP08)',
             'doom_type': -1,
             'episode': 1,
             'map': 8},
    360422: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Waste Disposal Plant (MAP08) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 8},
    360423: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Waste Disposal Plant (MAP08) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 8},
    360424: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Power Station (MAP09)',
             'doom_type': -1,
             'episode': 1,
             'map': 9},
    360425: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Power Station (MAP09) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 9},
    360426: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Nuclear Power Station (MAP09) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 9},
    360427: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP10)',
             'doom_type': -1,
             'episode': 1,
             'map': 10},
    360428: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cargo Bay (MAP10) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 10},
    360429: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Cargo Bay (MAP10) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 10},
    360430: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Simbattle (MAP11)',
             'doom_type': -1,
             'episode': 2,
             'map': 1},
    360431: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Simbattle (MAP11) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 1},
    360432: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Simbattle (MAP11) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 1},
    360433: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Villa of Pain (MAP12)',
             'doom_type': -1,
             'episode': 2,
             'map': 2},
    360434: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Villa of Pain (MAP12) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 2},
    360435: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Villa of Pain (MAP12) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 2},
    360436: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dark Crypt (MAP13)',
             'doom_type': -1,
             'episode': 2,
             'map': 3},
    360437: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dark Crypt (MAP13) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 3},
    360438: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Dark Crypt (MAP13) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 3},
    360439: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Circle (MAP14)',
             'doom_type': -1,
             'episode': 2,
             'map': 4},
    360440: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Circle (MAP14) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 4},
    360441: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'The Circle (MAP14) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 4},
    360442: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Trouble Town (MAP15)',
             'doom_type': -1,
             'episode': 2,
             'map': 5},
    360443: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Trouble Town (MAP15) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 5},
    360444: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Trouble Town (MAP15) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 5},
    360445: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Bruiser Fortress (MAP16)',
             'doom_type': -1,
             'episode': 2,
             'map': 6},
    360446: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Bruiser Fortress (MAP16) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 6},
    360447: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Bruiser Fortress (MAP16) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 6},
    360448: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Constriction (MAP17)',
             'doom_type': -1,
             'episode': 2,
             'map': 7},
    360449: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Constriction (MAP17) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 7},
    360450: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Constriction (MAP17) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 7},
    360451: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zombie Hideout (MAP18)',
             'doom_type': -1,
             'episode': 2,
             'map': 8},
    360452: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zombie Hideout (MAP18) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 8},
    360453: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Zombie Hideout (MAP18) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 8},
    360454: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Invasion (MAP19)',
             'doom_type': -1,
             'episode': 2,
             'map': 9},
    360455: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'The Invasion (MAP19) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 9},
    360456: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'The Invasion (MAP19) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 9},
    360457: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Death Row (MAP20)',
             'doom_type': -1,
             'episode': 2,
             'map': 10},
    360458: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Death Row (MAP20) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 10},
    360459: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Death Row (MAP20) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 10},
    360460: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Blood Lust (MAP21)',
             'doom_type': -1,
             'episode': 3,
             'map': 1},
    360461: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Blood Lust (MAP21) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 1},
    360462: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Blood Lust (MAP21) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 1},
    360463: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Firestorm Tomb (MAP22)',
             'doom_type': -1,
             'episode': 3,
             'map': 2},
    360464: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Firestorm Tomb (MAP22) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 2},
    360465: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Firestorm Tomb (MAP22) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 2},
    360466: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dungeon of Inferno (MAP23)',
             'doom_type': -1,
             'episode': 3,
             'map': 3},
    360467: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dungeon of Inferno (MAP23) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 3},
    360468: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Dungeon of Inferno (MAP23) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 3},
    360469: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cavern of the Evil Spirit (MAP24)',
             'doom_type': -1,
             'episode': 3,
             'map': 4},
    360470: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Cavern of the Evil Spirit (MAP24) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 4},
    360471: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Cavern of the Evil Spirit (MAP24) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 4},
    360472: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hellucination (MAP25)',
             'doom_type': -1,
             'episode': 3,
             'map': 5},
    360473: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hellucination (MAP25) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 5},
    360474: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Hellucination (MAP25) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 5},
    360475: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Valley of Brimstone (MAP26)',
             'doom_type': -1,
             'episode': 3,
             'map': 6},
    360476: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Valley of Brimstone (MAP26) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 6},
    360477: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Valley of Brimstone (MAP26) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 6},
    360478: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dissect (MAP27)',
             'doom_type': -1,
             'episode': 3,
             'map': 7},
    360479: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dissect (MAP27) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 7},
    360480: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Dissect (MAP27) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 7},
    360481: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Demise (MAP28)',
             'doom_type': -1,
             'episode': 3,
             'map': 8},
    360482: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Demise (MAP28) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 8},
    360483: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Unholy Demise (MAP28) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 8},
    360484: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Den of Torture (MAP29)',
             'doom_type': -1,
             'episode': 3,
             'map': 9},
    360485: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Den of Torture (MAP29) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 9},
    360486: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Den of Torture (MAP29) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 9},
    360487: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Eternal Core (MAP30)',
             'doom_type': -1,
             'episode': 3,
             'map': 10},
    360488: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Eternal Core (MAP30) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 10},
    360489: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Eternal Core (MAP30) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 10},
    360490: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Creepy (MAP31)',
             'doom_type': -1,
             'episode': 4,
             'map': 1},
    360491: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Creepy (MAP31) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 1},
    360492: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Creepy (MAP31) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 1},
    360493: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Condemnation (MAP32)',
             'doom_type': -1,
             'episode': 4,
             'map': 2},
    360494: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Condemnation (MAP32) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 2},
    360495: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Condemnation (MAP32) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 2},
    360496: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zerstorung (MAP33)',
             'doom_type': -1,
             'episode': 4,
             'map': 3},
    360497: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Zerstorung (MAP33) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 3},
    360498: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Zerstorung (MAP33) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 3},
    360600: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Bullet capacity',
             'doom_type': 65001,
             'episode': -1,
             'map': -1},
    360601: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Shell capacity',
             'doom_type': 65002,
             'episode': -1,
             'map': -1},
    360602: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Energy cell capacity',
             'doom_type': 65003,
             'episode': -1,
             'map': -1},
    360603: {'classification': ItemClassification.useful,
             'count': 0,
             'name': 'Rocket capacity',
             'doom_type': 65004,
             'episode': -1,
             'map': -1},
}


item_name_groups: Dict[str, Set[str]] = {
    'Ammos': {'Box of bullets', 'Box of rockets', 'Box of shotgun shells', 'Energy cell pack', },
    'Computer area maps': {'Blood Lust (MAP21) - Computer area map', 'Bruiser Fortress (MAP16) - Computer area map', 'Canyon Hub (MAP04) - Computer area map', 'Cargo Bay (MAP10) - Computer area map', 'Cavern of the Evil Spirit (MAP24) - Computer area map', 'Condemnation (MAP32) - Computer area map', 'Constriction (MAP17) - Computer area map', 'Control Facility (MAP02) - Computer area map', 'Creepy (MAP31) - Computer area map', 'Dark Crypt (MAP13) - Computer area map', 'Death Row (MAP20) - Computer area map', 'Den of Torture (MAP29) - Computer area map', 'Dissect (MAP27) - Computer area map', 'Dungeon of Inferno (MAP23) - Computer area map', 'Eternal Core (MAP30) - Computer area map', 'Firestorm Tomb (MAP22) - Computer area map', 'Heavyweight (MAP07) - Computer area map', 'Hellucination (MAP25) - Computer area map', 'Nuclear Power Station (MAP09) - Computer area map', 'Simbattle (MAP11) - Computer area map', 'Skybase 300 (MAP05) - Computer area map', 'The Alleyway (MAP03) - Computer area map', 'The Circle (MAP14) - Computer area map', 'The Invasion (MAP19) - Computer area map', 'The Spaceport (MAP01) - Computer area map', 'Trouble Town (MAP15) - Computer area map', 'Unholy Demise (MAP28) - Computer area map', 'Valley of Brimstone (MAP26) - Computer area map', 'Villa of Pain (MAP12) - Computer area map', 'Waste Disposal Plant (MAP08) - Computer area map', 'Whispering Corridor (MAP06) - Computer area map', 'Zerstorung (MAP33) - Computer area map', 'Zombie Hideout (MAP18) - Computer area map', },
    'Keys': {'Blood Lust (MAP21) - Red skull key', 'Bruiser Fortress (MAP16) - Yellow skull key', 'Canyon Hub (MAP04) - Yellow keycard', 'Cargo Bay (MAP10) - Red keycard', 'Cavern of the Evil Spirit (MAP24) - Blue skull key', 'Cavern of the Evil Spirit (MAP24) - Red skull key', 'Condemnation (MAP32) - Blue skull key', 'Condemnation (MAP32) - Red skull key', 'Condemnation (MAP32) - Yellow skull key', 'Constriction (MAP17) - Blue skull key', 'Constriction (MAP17) - Red skull key', 'Control Facility (MAP02) - Blue keycard', 'Control Facility (MAP02) - Red keycard', 'Control Facility (MAP02) - Yellow keycard', 'Creepy (MAP31) - Blue keycard', 'Creepy (MAP31) - Red keycard', 'Creepy (MAP31) - Yellow keycard', 'Dark Crypt (MAP13) - Blue keycard', 'Dark Crypt (MAP13) - Yellow keycard', 'Death Row (MAP20) - Blue keycard', 'Death Row (MAP20) - Red keycard', 'Den of Torture (MAP29) - Blue skull key', 'Dissect (MAP27) - Red skull key', 'Dungeon of Inferno (MAP23) - Blue skull key', 'Dungeon of Inferno (MAP23) - Red skull key', 'Firestorm Tomb (MAP22) - Red skull key', 'Firestorm Tomb (MAP22) - Yellow skull key', 'Hellucination (MAP25) - Blue skull key', 'Hellucination (MAP25) - Red skull key', 'Hellucination (MAP25) - Yellow skull key', 'Nuclear Power Station (MAP09) - Blue keycard', 'Nuclear Power Station (MAP09) - Red keycard', 'Nuclear Power Station (MAP09) - Yellow keycard', 'Simbattle (MAP11) - Blue keycard', 'Simbattle (MAP11) - Red keycard', 'Simbattle (MAP11) - Yellow keycard', 'Skybase 300 (MAP05) - Blue keycard', 'Skybase 300 (MAP05) - Yellow keycard', 'The Alleyway (MAP03) - Blue keycard', 'The Circle (MAP14) - Red skull key', 'The Circle (MAP14) - Yellow skull key', 'The Invasion (MAP19) - Red skull key', 'The Invasion (MAP19) - Yellow skull key', 'Trouble Town (MAP15) - Blue keycard', 'Trouble Town (MAP15) - Red keycard', 'Trouble Town (MAP15) - Yellow keycard', 'Unholy Demise (MAP28) - Red skull key', 'Unholy Demise (MAP28) - Yellow skull key', 'Valley of Brimstone (MAP26) - Yellow skull key', 'Villa of Pain (MAP12) - Red skull key', 'Villa of Pain (MAP12) - Yellow skull key', 'Waste Disposal Plant (MAP08) - Blue keycard', 'Waste Disposal Plant (MAP08) - Red keycard', 'Whispering Corridor (MAP06) - Blue skull key', 'Zerstorung (MAP33) - Blue skull key', 'Zerstorung (MAP33) - Red skull key', 'Zerstorung (MAP33) - Yellow skull key', 'Zombie Hideout (MAP18) - Blue skull key', 'Zombie Hideout (MAP18) - Yellow skull key', },
    'Levels': {'Blood Lust (MAP21)', 'Bruiser Fortress (MAP16)', 'Canyon Hub (MAP04)', 'Cargo Bay (MAP10)', 'Cavern of the Evil Spirit (MAP24)', 'Condemnation (MAP32)', 'Constriction (MAP17)', 'Control Facility (MAP02)', 'Creepy (MAP31)', 'Dark Crypt (MAP13)', 'Death Row (MAP20)', 'Den of Torture (MAP29)', 'Dissect (MAP27)', 'Dungeon of Inferno (MAP23)', 'Eternal Core (MAP30)', 'Firestorm Tomb (MAP22)', 'Heavyweight (MAP07)', 'Hellucination (MAP25)', 'Nuclear Power Station (MAP09)', 'Simbattle (MAP11)', 'Skybase 300 (MAP05)', 'The Alleyway (MAP03)', 'The Circle (MAP14)', 'The Invasion (MAP19)', 'The Spaceport (MAP01)', 'Trouble Town (MAP15)', 'Unholy Demise (MAP28)', 'Valley of Brimstone (MAP26)', 'Villa of Pain (MAP12)', 'Waste Disposal Plant (MAP08)', 'Whispering Corridor (MAP06)', 'Zerstorung (MAP33)', 'Zombie Hideout (MAP18)', },
    'Powerups': {'Armor', 'Berserk', 'Invulnerability', 'Mega Armor', 'Megasphere', 'Partial invisibility', 'Supercharge', },
    'Weapons': {'BFG9000', 'Chaingun', 'Chainsaw', 'Plasma gun', 'Rocket launcher', 'Shotgun', 'Super Shotgun', },
}
