# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from typing import Dict, TypedDict, List, Set 


class LocationDict(TypedDict, total=False): 
    name: str 
    episode: int 
    map: int 
    index: int # Thing index as it is stored in the wad file. 
    doom_type: int # In case index end up unreliable, we can use doom type. Maps have often only one of each important things. 
    region: str 


location_table: Dict[int, LocationDict] = {
    361000: {'name': 'The Spaceport (MAP01) - Shotgun',
             'episode': 1,
             'map': 1,
             'index': 4,
             'doom_type': 2001,
             'region': "The Spaceport (MAP01) Main"},
    361001: {'name': 'The Spaceport (MAP01) - Chaingun',
             'episode': 1,
             'map': 1,
             'index': 7,
             'doom_type': 2002,
             'region': "The Spaceport (MAP01) Main"},
    361002: {'name': 'The Spaceport (MAP01) - Armor',
             'episode': 1,
             'map': 1,
             'index': 37,
             'doom_type': 2018,
             'region': "The Spaceport (MAP01) Main"},
    361003: {'name': 'The Spaceport (MAP01) - Exit',
             'episode': 1,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "The Spaceport (MAP01) Main"},
    361004: {'name': 'Control Facility (MAP02) - Yellow keycard',
             'episode': 1,
             'map': 2,
             'index': 4,
             'doom_type': 6,
             'region': "Control Facility (MAP02) Main"},
    361005: {'name': 'Control Facility (MAP02) - Berserk',
             'episode': 1,
             'map': 2,
             'index': 5,
             'doom_type': 2023,
             'region': "Control Facility (MAP02) Main"},
    361006: {'name': 'Control Facility (MAP02) - Blue keycard',
             'episode': 1,
             'map': 2,
             'index': 7,
             'doom_type': 5,
             'region': "Control Facility (MAP02) Yellow"},
    361007: {'name': 'Control Facility (MAP02) - Red keycard',
             'episode': 1,
             'map': 2,
             'index': 8,
             'doom_type': 13,
             'region': "Control Facility (MAP02) Blue"},
    361008: {'name': 'Control Facility (MAP02) - Super Shotgun',
             'episode': 1,
             'map': 2,
             'index': 9,
             'doom_type': 82,
             'region': "Control Facility (MAP02) Yellow"},
    361009: {'name': 'Control Facility (MAP02) - Mega Armor',
             'episode': 1,
             'map': 2,
             'index': 77,
             'doom_type': 2019,
             'region': "Control Facility (MAP02) Yellow"},
    361010: {'name': 'Control Facility (MAP02) - Chaingun',
             'episode': 1,
             'map': 2,
             'index': 79,
             'doom_type': 2002,
             'region': "Control Facility (MAP02) Blue"},
    361011: {'name': 'Control Facility (MAP02) - Rocket launcher',
             'episode': 1,
             'map': 2,
             'index': 80,
             'doom_type': 2003,
             'region': "Control Facility (MAP02) Main"},
    361012: {'name': 'Control Facility (MAP02) - Shotgun',
             'episode': 1,
             'map': 2,
             'index': 228,
             'doom_type': 2001,
             'region': "Control Facility (MAP02) Blue"},
    361013: {'name': 'Control Facility (MAP02) - Exit',
             'episode': 1,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "Control Facility (MAP02) Red"},
    361014: {'name': 'The Alleyway (MAP03) - Supercharge',
             'episode': 1,
             'map': 3,
             'index': 14,
             'doom_type': 2013,
             'region': "The Alleyway (MAP03) Main"},
    361015: {'name': 'The Alleyway (MAP03) - Blue keycard',
             'episode': 1,
             'map': 3,
             'index': 18,
             'doom_type': 5,
             'region': "The Alleyway (MAP03) Main"},
    361016: {'name': 'The Alleyway (MAP03) - Berserk',
             'episode': 1,
             'map': 3,
             'index': 20,
             'doom_type': 2023,
             'region': "The Alleyway (MAP03) Main"},
    361017: {'name': 'The Alleyway (MAP03) - Chaingun',
             'episode': 1,
             'map': 3,
             'index': 40,
             'doom_type': 2002,
             'region': "The Alleyway (MAP03) Main"},
    361018: {'name': 'The Alleyway (MAP03) - Backpack',
             'episode': 1,
             'map': 3,
             'index': 139,
             'doom_type': 8,
             'region': "The Alleyway (MAP03) Main"},
    361019: {'name': 'The Alleyway (MAP03) - Exit',
             'episode': 1,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "The Alleyway (MAP03) Blue"},
    361020: {'name': 'Canyon Hub (MAP04) - Yellow keycard',
             'episode': 1,
             'map': 4,
             'index': 3,
             'doom_type': 6,
             'region': "Canyon Hub (MAP04) Main"},
    361021: {'name': 'Canyon Hub (MAP04) - Supercharge',
             'episode': 1,
             'map': 4,
             'index': 4,
             'doom_type': 2013,
             'region': "Canyon Hub (MAP04) Main"},
    361022: {'name': 'Canyon Hub (MAP04) - Backpack',
             'episode': 1,
             'map': 4,
             'index': 38,
             'doom_type': 8,
             'region': "Canyon Hub (MAP04) Main"},
    361023: {'name': 'Canyon Hub (MAP04) - Berserk',
             'episode': 1,
             'map': 4,
             'index': 102,
             'doom_type': 2023,
             'region': "Canyon Hub (MAP04) Main"},
    361024: {'name': 'Canyon Hub (MAP04) - Armor',
             'episode': 1,
             'map': 4,
             'index': 103,
             'doom_type': 2018,
             'region': "Canyon Hub (MAP04) Main"},
    361025: {'name': 'Canyon Hub (MAP04) - Super Shotgun',
             'episode': 1,
             'map': 4,
             'index': 131,
             'doom_type': 82,
             'region': "Canyon Hub (MAP04) Yellow"},
    361026: {'name': 'Canyon Hub (MAP04) - Shotgun',
             'episode': 1,
             'map': 4,
             'index': 175,
             'doom_type': 2001,
             'region': "Canyon Hub (MAP04) Yellow"},
    361027: {'name': 'Canyon Hub (MAP04) - Exit',
             'episode': 1,
             'map': 4,
             'index': -1,
             'doom_type': -1,
             'region': "Canyon Hub (MAP04) Yellow"},
    361028: {'name': 'Skybase 300 (MAP05) - Blue keycard',
             'episode': 1,
             'map': 5,
             'index': 4,
             'doom_type': 5,
             'region': "Skybase 300 (MAP05) Main"},
    361029: {'name': 'Skybase 300 (MAP05) - Shotgun',
             'episode': 1,
             'map': 5,
             'index': 35,
             'doom_type': 2001,
             'region': "Skybase 300 (MAP05) Main"},
    361030: {'name': 'Skybase 300 (MAP05) - Rocket launcher',
             'episode': 1,
             'map': 5,
             'index': 40,
             'doom_type': 2003,
             'region': "Skybase 300 (MAP05) Main"},
    361031: {'name': 'Skybase 300 (MAP05) - Yellow keycard',
             'episode': 1,
             'map': 5,
             'index': 58,
             'doom_type': 6,
             'region': "Skybase 300 (MAP05) Blue"},
    361032: {'name': 'Skybase 300 (MAP05) - Super Shotgun',
             'episode': 1,
             'map': 5,
             'index': 62,
             'doom_type': 82,
             'region': "Skybase 300 (MAP05) Blue"},
    361033: {'name': 'Skybase 300 (MAP05) - Armor',
             'episode': 1,
             'map': 5,
             'index': 108,
             'doom_type': 2018,
             'region': "Skybase 300 (MAP05) Blue"},
    361034: {'name': 'Skybase 300 (MAP05) - Exit',
             'episode': 1,
             'map': 5,
             'index': -1,
             'doom_type': -1,
             'region': "Skybase 300 (MAP05) Yellow"},
    361035: {'name': 'Whispering Corridor (MAP06) - Blue skull key',
             'episode': 1,
             'map': 6,
             'index': 15,
             'doom_type': 40,
             'region': "Whispering Corridor (MAP06) Main"},
    361036: {'name': 'Whispering Corridor (MAP06) - Super Shotgun',
             'episode': 1,
             'map': 6,
             'index': 76,
             'doom_type': 82,
             'region': "Whispering Corridor (MAP06) Main"},
    361037: {'name': 'Whispering Corridor (MAP06) - Rocket launcher',
             'episode': 1,
             'map': 6,
             'index': 86,
             'doom_type': 2003,
             'region': "Whispering Corridor (MAP06) Main"},
    361038: {'name': 'Whispering Corridor (MAP06) - Armor',
             'episode': 1,
             'map': 6,
             'index': 123,
             'doom_type': 2018,
             'region': "Whispering Corridor (MAP06) Main"},
    361039: {'name': 'Whispering Corridor (MAP06) - Chainsaw',
             'episode': 1,
             'map': 6,
             'index': 225,
             'doom_type': 2005,
             'region': "Whispering Corridor (MAP06) Main"},
    361040: {'name': 'Whispering Corridor (MAP06) - Exit',
             'episode': 1,
             'map': 6,
             'index': -1,
             'doom_type': -1,
             'region': "Whispering Corridor (MAP06) Blue"},
    361041: {'name': 'Heavyweight (MAP07) - Super Shotgun',
             'episode': 1,
             'map': 7,
             'index': 8,
             'doom_type': 82,
             'region': "Heavyweight (MAP07) Main"},
    361042: {'name': 'Heavyweight (MAP07) - Chaingun',
             'episode': 1,
             'map': 7,
             'index': 9,
             'doom_type': 2002,
             'region': "Heavyweight (MAP07) Main"},
    361043: {'name': 'Heavyweight (MAP07) - Rocket launcher',
             'episode': 1,
             'map': 7,
             'index': 10,
             'doom_type': 2003,
             'region': "Heavyweight (MAP07) Main"},
    361044: {'name': 'Heavyweight (MAP07) - Plasma gun',
             'episode': 1,
             'map': 7,
             'index': 11,
             'doom_type': 2004,
             'region': "Heavyweight (MAP07) Main"},
    361045: {'name': 'Heavyweight (MAP07) - Shotgun',
             'episode': 1,
             'map': 7,
             'index': 12,
             'doom_type': 2001,
             'region': "Heavyweight (MAP07) Main"},
    361046: {'name': 'Heavyweight (MAP07) - Backpack',
             'episode': 1,
             'map': 7,
             'index': 41,
             'doom_type': 8,
             'region': "Heavyweight (MAP07) Main"},
    361047: {'name': 'Heavyweight (MAP07) - Backpack 2',
             'episode': 1,
             'map': 7,
             'index': 42,
             'doom_type': 8,
             'region': "Heavyweight (MAP07) Main"},
    361048: {'name': 'Heavyweight (MAP07) - Partial invisibility',
             'episode': 1,
             'map': 7,
             'index': 55,
             'doom_type': 2024,
             'region': "Heavyweight (MAP07) Main"},
    361049: {'name': 'Heavyweight (MAP07) - Mega Armor',
             'episode': 1,
             'map': 7,
             'index': 56,
             'doom_type': 2019,
             'region': "Heavyweight (MAP07) Main"},
    361050: {'name': 'Heavyweight (MAP07) - Backpack 3',
             'episode': 1,
             'map': 7,
             'index': 137,
             'doom_type': 8,
             'region': "Heavyweight (MAP07) Main"},
    361051: {'name': 'Heavyweight (MAP07) - Backpack 4',
             'episode': 1,
             'map': 7,
             'index': 138,
             'doom_type': 8,
             'region': "Heavyweight (MAP07) Main"},
    361052: {'name': 'Heavyweight (MAP07) - Berserk',
             'episode': 1,
             'map': 7,
             'index': 140,
             'doom_type': 2023,
             'region': "Heavyweight (MAP07) Main"},
    361053: {'name': 'Heavyweight (MAP07) - Exit',
             'episode': 1,
             'map': 7,
             'index': -1,
             'doom_type': -1,
             'region': "Heavyweight (MAP07) Main"},
    361054: {'name': 'Waste Disposal Plant (MAP08) - Red keycard',
             'episode': 1,
             'map': 8,
             'index': 2,
             'doom_type': 13,
             'region': "Waste Disposal Plant (MAP08) Main"},
    361055: {'name': 'Waste Disposal Plant (MAP08) - Blue keycard',
             'episode': 1,
             'map': 8,
             'index': 19,
             'doom_type': 5,
             'region': "Waste Disposal Plant (MAP08) Red"},
    361056: {'name': 'Waste Disposal Plant (MAP08) - Supercharge',
             'episode': 1,
             'map': 8,
             'index': 20,
             'doom_type': 2013,
             'region': "Waste Disposal Plant (MAP08) Main"},
    361057: {'name': 'Waste Disposal Plant (MAP08) - Plasma gun',
             'episode': 1,
             'map': 8,
             'index': 65,
             'doom_type': 2004,
             'region': "Waste Disposal Plant (MAP08) Main"},
    361058: {'name': 'Waste Disposal Plant (MAP08) - Super Shotgun',
             'episode': 1,
             'map': 8,
             'index': 98,
             'doom_type': 82,
             'region': "Waste Disposal Plant (MAP08) Red"},
    361059: {'name': 'Waste Disposal Plant (MAP08) - Rocket launcher',
             'episode': 1,
             'map': 8,
             'index': 124,
             'doom_type': 2003,
             'region': "Waste Disposal Plant (MAP08) Red"},
    361060: {'name': 'Waste Disposal Plant (MAP08) - Backpack',
             'episode': 1,
             'map': 8,
             'index': 134,
             'doom_type': 8,
             'region': "Waste Disposal Plant (MAP08) Red"},
    361061: {'name': 'Waste Disposal Plant (MAP08) - Armor',
             'episode': 1,
             'map': 8,
             'index': 139,
             'doom_type': 2018,
             'region': "Waste Disposal Plant (MAP08) Red"},
    361062: {'name': 'Waste Disposal Plant (MAP08) - Exit',
             'episode': 1,
             'map': 8,
             'index': -1,
             'doom_type': -1,
             'region': "Waste Disposal Plant (MAP08) Blue"},
    361063: {'name': 'Nuclear Power Station (MAP09) - Red keycard',
             'episode': 1,
             'map': 9,
             'index': 0,
             'doom_type': 13,
             'region': "Nuclear Power Station (MAP09) Yellow"},
    361064: {'name': 'Nuclear Power Station (MAP09) - Blue keycard',
             'episode': 1,
             'map': 9,
             'index': 1,
             'doom_type': 5,
             'region': "Nuclear Power Station (MAP09) Red"},
    361065: {'name': 'Nuclear Power Station (MAP09) - Yellow keycard',
             'episode': 1,
             'map': 9,
             'index': 2,
             'doom_type': 6,
             'region': "Nuclear Power Station (MAP09) Main"},
    361066: {'name': 'Nuclear Power Station (MAP09) - Chaingun',
             'episode': 1,
             'map': 9,
             'index': 26,
             'doom_type': 2002,
             'region': "Nuclear Power Station (MAP09) Main"},
    361067: {'name': 'Nuclear Power Station (MAP09) - Chainsaw',
             'episode': 1,
             'map': 9,
             'index': 56,
             'doom_type': 2005,
             'region': "Nuclear Power Station (MAP09) Red"},
    361068: {'name': 'Nuclear Power Station (MAP09) - Super Shotgun',
             'episode': 1,
             'map': 9,
             'index': 94,
             'doom_type': 82,
             'region': "Nuclear Power Station (MAP09) Yellow"},
    361069: {'name': 'Nuclear Power Station (MAP09) - Berserk',
             'episode': 1,
             'map': 9,
             'index': 189,
             'doom_type': 2023,
             'region': "Nuclear Power Station (MAP09) Main"},
    361070: {'name': 'Nuclear Power Station (MAP09) - Rocket launcher',
             'episode': 1,
             'map': 9,
             'index': 192,
             'doom_type': 2003,
             'region': "Nuclear Power Station (MAP09) Red"},
    361071: {'name': 'Nuclear Power Station (MAP09) - Armor',
             'episode': 1,
             'map': 9,
             'index': 209,
             'doom_type': 2018,
             'region': "Nuclear Power Station (MAP09) Yellow"},
    361072: {'name': 'Nuclear Power Station (MAP09) - Exit',
             'episode': 1,
             'map': 9,
             'index': -1,
             'doom_type': -1,
             'region': "Nuclear Power Station (MAP09) Blue"},
    361073: {'name': 'Cargo Bay (MAP10) - Red keycard',
             'episode': 1,
             'map': 10,
             'index': 4,
             'doom_type': 13,
             'region': "Cargo Bay (MAP10) Main"},
    361074: {'name': 'Cargo Bay (MAP10) - Supercharge',
             'episode': 1,
             'map': 10,
             'index': 5,
             'doom_type': 2013,
             'region': "Cargo Bay (MAP10) Main"},
    361075: {'name': 'Cargo Bay (MAP10) - Berserk',
             'episode': 1,
             'map': 10,
             'index': 7,
             'doom_type': 2023,
             'region': "Cargo Bay (MAP10) Main"},
    361076: {'name': 'Cargo Bay (MAP10) - Mega Armor',
             'episode': 1,
             'map': 10,
             'index': 8,
             'doom_type': 2019,
             'region': "Cargo Bay (MAP10) Main"},
    361077: {'name': 'Cargo Bay (MAP10) - Plasma gun',
             'episode': 1,
             'map': 10,
             'index': 9,
             'doom_type': 2004,
             'region': "Cargo Bay (MAP10) Main"},
    361078: {'name': 'Cargo Bay (MAP10) - Backpack',
             'episode': 1,
             'map': 10,
             'index': 10,
             'doom_type': 8,
             'region': "Cargo Bay (MAP10) Main"},
    361079: {'name': 'Cargo Bay (MAP10) - Super Shotgun',
             'episode': 1,
             'map': 10,
             'index': 73,
             'doom_type': 82,
             'region': "Cargo Bay (MAP10) Main"},
    361080: {'name': 'Cargo Bay (MAP10) - Backpack 2',
             'episode': 1,
             'map': 10,
             'index': 127,
             'doom_type': 8,
             'region': "Cargo Bay (MAP10) Main"},
    361081: {'name': 'Cargo Bay (MAP10) - Exit',
             'episode': 1,
             'map': 10,
             'index': -1,
             'doom_type': -1,
             'region': "Cargo Bay (MAP10) Red"},
    361082: {'name': 'Simbattle (MAP11) - Backpack',
             'episode': 2,
             'map': 1,
             'index': 145,
             'doom_type': 8,
             'region': "Simbattle (MAP11) Yellow"},
    361083: {'name': 'Simbattle (MAP11) - Chaingun',
             'episode': 2,
             'map': 1,
             'index': 155,
             'doom_type': 2002,
             'region': "Simbattle (MAP11) Yellow"},
    361084: {'name': 'Simbattle (MAP11) - Rocket launcher',
             'episode': 2,
             'map': 1,
             'index': 156,
             'doom_type': 2003,
             'region': "Simbattle (MAP11) Yellow"},
    361085: {'name': 'Simbattle (MAP11) - Plasma gun',
             'episode': 2,
             'map': 1,
             'index': 157,
             'doom_type': 2004,
             'region': "Simbattle (MAP11) Yellow"},
    361086: {'name': 'Simbattle (MAP11) - Mega Armor',
             'episode': 2,
             'map': 1,
             'index': 158,
             'doom_type': 2019,
             'region': "Simbattle (MAP11) Yellow"},
    361087: {'name': 'Simbattle (MAP11) - Partial invisibility',
             'episode': 2,
             'map': 1,
             'index': 159,
             'doom_type': 2024,
             'region': "Simbattle (MAP11) Yellow"},
    361088: {'name': 'Simbattle (MAP11) - Berserk',
             'episode': 2,
             'map': 1,
             'index': 160,
             'doom_type': 2023,
             'region': "Simbattle (MAP11) Yellow"},
    361089: {'name': 'Simbattle (MAP11) - Supercharge',
             'episode': 2,
             'map': 1,
             'index': 161,
             'doom_type': 2013,
             'region': "Simbattle (MAP11) Yellow"},
    361090: {'name': 'Simbattle (MAP11) - Blue keycard',
             'episode': 2,
             'map': 1,
             'index': 221,
             'doom_type': 5,
             'region': "Simbattle (MAP11) Main"},
    361091: {'name': 'Simbattle (MAP11) - Red keycard',
             'episode': 2,
             'map': 1,
             'index': 222,
             'doom_type': 13,
             'region': "Simbattle (MAP11) Blue"},
    361092: {'name': 'Simbattle (MAP11) - Yellow keycard',
             'episode': 2,
             'map': 1,
             'index': 223,
             'doom_type': 6,
             'region': "Simbattle (MAP11) Red"},
    361093: {'name': 'Simbattle (MAP11) - BFG9000',
             'episode': 2,
             'map': 1,
             'index': 224,
             'doom_type': 2006,
             'region': "Simbattle (MAP11) Yellow"},
    361094: {'name': 'Simbattle (MAP11) - Super Shotgun',
             'episode': 2,
             'map': 1,
             'index': 225,
             'doom_type': 82,
             'region': "Simbattle (MAP11) Start"},
    361095: {'name': 'Simbattle (MAP11) - Megasphere',
             'episode': 2,
             'map': 1,
             'index': 277,
             'doom_type': 83,
             'region': "Simbattle (MAP11) Yellow"},
    361096: {'name': 'Simbattle (MAP11) - Invulnerability',
             'episode': 2,
             'map': 1,
             'index': 278,
             'doom_type': 2022,
             'region': "Simbattle (MAP11) Yellow"},
    361097: {'name': 'Simbattle (MAP11) - Exit',
             'episode': 2,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "Simbattle (MAP11) Yellow"},
    361098: {'name': 'Villa of Pain (MAP12) - Red skull key',
             'episode': 2,
             'map': 2,
             'index': 12,
             'doom_type': 38,
             'region': "Villa of Pain (MAP12) Yellow"},
    361099: {'name': 'Villa of Pain (MAP12) - Yellow skull key',
             'episode': 2,
             'map': 2,
             'index': 78,
             'doom_type': 39,
             'region': "Villa of Pain (MAP12) Main"},
    361100: {'name': 'Villa of Pain (MAP12) - Berserk',
             'episode': 2,
             'map': 2,
             'index': 96,
             'doom_type': 2023,
             'region': "Villa of Pain (MAP12) Main"},
    361101: {'name': 'Villa of Pain (MAP12) - Armor',
             'episode': 2,
             'map': 2,
             'index': 140,
             'doom_type': 2018,
             'region': "Villa of Pain (MAP12) Yellow"},
    361102: {'name': 'Villa of Pain (MAP12) - Super Shotgun',
             'episode': 2,
             'map': 2,
             'index': 156,
             'doom_type': 82,
             'region': "Villa of Pain (MAP12) Yellow"},
    361103: {'name': 'Villa of Pain (MAP12) - Exit',
             'episode': 2,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "Villa of Pain (MAP12) Red"},
    361104: {'name': 'Dark Crypt (MAP13) - Blue keycard',
             'episode': 2,
             'map': 3,
             'index': 1,
             'doom_type': 5,
             'region': "Dark Crypt (MAP13) Yellow"},
    361105: {'name': 'Dark Crypt (MAP13) - Yellow keycard',
             'episode': 2,
             'map': 3,
             'index': 12,
             'doom_type': 6,
             'region': "Dark Crypt (MAP13) Main"},
    361106: {'name': 'Dark Crypt (MAP13) - Megasphere',
             'episode': 2,
             'map': 3,
             'index': 18,
             'doom_type': 83,
             'region': "Dark Crypt (MAP13) Main"},
    361107: {'name': 'Dark Crypt (MAP13) - Plasma gun',
             'episode': 2,
             'map': 3,
             'index': 22,
             'doom_type': 2004,
             'region': "Dark Crypt (MAP13) Yellow"},
    361108: {'name': 'Dark Crypt (MAP13) - Backpack',
             'episode': 2,
             'map': 3,
             'index': 29,
             'doom_type': 8,
             'region': "Dark Crypt (MAP13) Yellow"},
    361109: {'name': 'Dark Crypt (MAP13) - Super Shotgun',
             'episode': 2,
             'map': 3,
             'index': 56,
             'doom_type': 82,
             'region': "Dark Crypt (MAP13) Main"},
    361110: {'name': 'Dark Crypt (MAP13) - Chainsaw',
             'episode': 2,
             'map': 3,
             'index': 160,
             'doom_type': 2005,
             'region': "Dark Crypt (MAP13) Main"},
    361111: {'name': 'Dark Crypt (MAP13) - Exit',
             'episode': 2,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "Dark Crypt (MAP13) Blue"},
    361112: {'name': 'The Circle (MAP14) - Yellow skull key',
             'episode': 2,
             'map': 4,
             'index': 1,
             'doom_type': 39,
             'region': "The Circle (MAP14) Main"},
    361113: {'name': 'The Circle (MAP14) - Red skull key',
             'episode': 2,
             'map': 4,
             'index': 10,
             'doom_type': 38,
             'region': "The Circle (MAP14) Yellow"},
    361114: {'name': 'The Circle (MAP14) - Super Shotgun',
             'episode': 2,
             'map': 4,
             'index': 31,
             'doom_type': 82,
             'region': "The Circle (MAP14) Main"},
    361115: {'name': 'The Circle (MAP14) - Berserk',
             'episode': 2,
             'map': 4,
             'index': 56,
             'doom_type': 2023,
             'region': "The Circle (MAP14) Main"},
    361116: {'name': 'The Circle (MAP14) - Armor',
             'episode': 2,
             'map': 4,
             'index': 74,
             'doom_type': 2018,
             'region': "The Circle (MAP14) Main"},
    361117: {'name': 'The Circle (MAP14) - Rocket launcher',
             'episode': 2,
             'map': 4,
             'index': 94,
             'doom_type': 2003,
             'region': "The Circle (MAP14) Main"},
    361118: {'name': 'The Circle (MAP14) - Exit',
             'episode': 2,
             'map': 4,
             'index': -1,
             'doom_type': -1,
             'region': "The Circle (MAP14) Red"},
    361119: {'name': 'Trouble Town (MAP15) - Yellow keycard',
             'episode': 2,
             'map': 5,
             'index': 2,
             'doom_type': 6,
             'region': "Trouble Town (MAP15) Main"},
    361120: {'name': 'Trouble Town (MAP15) - Blue keycard',
             'episode': 2,
             'map': 5,
             'index': 5,
             'doom_type': 5,
             'region': "Trouble Town (MAP15) Main"},
    361121: {'name': 'Trouble Town (MAP15) - Red keycard',
             'episode': 2,
             'map': 5,
             'index': 6,
             'doom_type': 13,
             'region': "Trouble Town (MAP15) Main"},
    361122: {'name': 'Trouble Town (MAP15) - Shotgun',
             'episode': 2,
             'map': 5,
             'index': 70,
             'doom_type': 2001,
             'region': "Trouble Town (MAP15) Start"},
    361123: {'name': 'Trouble Town (MAP15) - Supercharge',
             'episode': 2,
             'map': 5,
             'index': 71,
             'doom_type': 2013,
             'region': "Trouble Town (MAP15) All Keys"},
    361124: {'name': 'Trouble Town (MAP15) - Rocket launcher',
             'episode': 2,
             'map': 5,
             'index': 80,
             'doom_type': 2003,
             'region': "Trouble Town (MAP15) Main"},
    361125: {'name': 'Trouble Town (MAP15) - Berserk',
             'episode': 2,
             'map': 5,
             'index': 94,
             'doom_type': 2023,
             'region': "Trouble Town (MAP15) Main"},
    361126: {'name': 'Trouble Town (MAP15) - Mega Armor',
             'episode': 2,
             'map': 5,
             'index': 95,
             'doom_type': 2019,
             'region': "Trouble Town (MAP15) Main"},
    361127: {'name': 'Trouble Town (MAP15) - Super Shotgun',
             'episode': 2,
             'map': 5,
             'index': 102,
             'doom_type': 82,
             'region': "Trouble Town (MAP15) Main"},
    361128: {'name': 'Trouble Town (MAP15) - BFG9000',
             'episode': 2,
             'map': 5,
             'index': 107,
             'doom_type': 2006,
             'region': "Trouble Town (MAP15) Main"},
    361129: {'name': 'Trouble Town (MAP15) - Plasma gun',
             'episode': 2,
             'map': 5,
             'index': 110,
             'doom_type': 2004,
             'region': "Trouble Town (MAP15) Main"},
    361130: {'name': 'Trouble Town (MAP15) - Backpack',
             'episode': 2,
             'map': 5,
             'index': 140,
             'doom_type': 8,
             'region': "Trouble Town (MAP15) Main"},
    361131: {'name': 'Trouble Town (MAP15) - Exit',
             'episode': 2,
             'map': 5,
             'index': -1,
             'doom_type': -1,
             'region': "Trouble Town (MAP15) All Keys"},
    361132: {'name': 'Bruiser Fortress (MAP16) - Yellow skull key',
             'episode': 2,
             'map': 6,
             'index': 1,
             'doom_type': 39,
             'region': "Bruiser Fortress (MAP16) Main"},
    361133: {'name': 'Bruiser Fortress (MAP16) - Supercharge',
             'episode': 2,
             'map': 6,
             'index': 2,
             'doom_type': 2013,
             'region': "Bruiser Fortress (MAP16) Main"},
    361134: {'name': 'Bruiser Fortress (MAP16) - Super Shotgun',
             'episode': 2,
             'map': 6,
             'index': 39,
             'doom_type': 82,
             'region': "Bruiser Fortress (MAP16) Main"},
    361135: {'name': 'Bruiser Fortress (MAP16) - Rocket launcher',
             'episode': 2,
             'map': 6,
             'index': 40,
             'doom_type': 2003,
             'region': "Bruiser Fortress (MAP16) Main"},
    361136: {'name': 'Bruiser Fortress (MAP16) - Armor',
             'episode': 2,
             'map': 6,
             'index': 98,
             'doom_type': 2018,
             'region': "Bruiser Fortress (MAP16) Main"},
    361137: {'name': 'Bruiser Fortress (MAP16) - Shotgun',
             'episode': 2,
             'map': 6,
             'index': 115,
             'doom_type': 2001,
             'region': "Bruiser Fortress (MAP16) Main"},
    361138: {'name': 'Bruiser Fortress (MAP16) - Backpack',
             'episode': 2,
             'map': 6,
             'index': 157,
             'doom_type': 8,
             'region': "Bruiser Fortress (MAP16) Main"},
    361139: {'name': 'Bruiser Fortress (MAP16) - Exit',
             'episode': 2,
             'map': 6,
             'index': -1,
             'doom_type': -1,
             'region': "Bruiser Fortress (MAP16) Yellow"},
    361140: {'name': 'Constriction (MAP17) - Red skull key',
             'episode': 2,
             'map': 7,
             'index': 0,
             'doom_type': 38,
             'region': "Constriction (MAP17) Blue"},
    361141: {'name': 'Constriction (MAP17) - Blue skull key',
             'episode': 2,
             'map': 7,
             'index': 9,
             'doom_type': 40,
             'region': "Constriction (MAP17) Main"},
    361142: {'name': 'Constriction (MAP17) - Super Shotgun',
             'episode': 2,
             'map': 7,
             'index': 40,
             'doom_type': 82,
             'region': "Constriction (MAP17) Main"},
    361143: {'name': 'Constriction (MAP17) - Berserk',
             'episode': 2,
             'map': 7,
             'index': 71,
             'doom_type': 2023,
             'region': "Constriction (MAP17) Blue"},
    361144: {'name': 'Constriction (MAP17) - Chainsaw',
             'episode': 2,
             'map': 7,
             'index': 72,
             'doom_type': 2005,
             'region': "Constriction (MAP17) Blue"},
    361145: {'name': 'Constriction (MAP17) - Shotgun',
             'episode': 2,
             'map': 7,
             'index': 188,
             'doom_type': 2001,
             'region': "Constriction (MAP17) Main"},
    361146: {'name': 'Constriction (MAP17) - Exit',
             'episode': 2,
             'map': 7,
             'index': -1,
             'doom_type': -1,
             'region': "Constriction (MAP17) Red"},
    361147: {'name': 'Zombie Hideout (MAP18) - Blue skull key',
             'episode': 2,
             'map': 8,
             'index': 1,
             'doom_type': 40,
             'region': "Zombie Hideout (MAP18) Main"},
    361148: {'name': 'Zombie Hideout (MAP18) - Yellow skull key',
             'episode': 2,
             'map': 8,
             'index': 4,
             'doom_type': 39,
             'region': "Zombie Hideout (MAP18) Blue"},
    361149: {'name': 'Zombie Hideout (MAP18) - Super Shotgun',
             'episode': 2,
             'map': 8,
             'index': 25,
             'doom_type': 82,
             'region': "Zombie Hideout (MAP18) Main"},
    361150: {'name': 'Zombie Hideout (MAP18) - Berserk',
             'episode': 2,
             'map': 8,
             'index': 49,
             'doom_type': 2023,
             'region': "Zombie Hideout (MAP18) Blue"},
    361151: {'name': 'Zombie Hideout (MAP18) - Exit',
             'episode': 2,
             'map': 8,
             'index': -1,
             'doom_type': -1,
             'region': "Zombie Hideout (MAP18) Yellow"},
    361152: {'name': 'The Invasion (MAP19) - Red skull key',
             'episode': 2,
             'map': 9,
             'index': 4,
             'doom_type': 38,
             'region': "The Invasion (MAP19) Main"},
    361153: {'name': 'The Invasion (MAP19) - Yellow skull key',
             'episode': 2,
             'map': 9,
             'index': 5,
             'doom_type': 39,
             'region': "The Invasion (MAP19) Red"},
    361154: {'name': 'The Invasion (MAP19) - Supercharge',
             'episode': 2,
             'map': 9,
             'index': 28,
             'doom_type': 2013,
             'region': "The Invasion (MAP19) Main"},
    361155: {'name': 'The Invasion (MAP19) - Rocket launcher',
             'episode': 2,
             'map': 9,
             'index': 29,
             'doom_type': 2003,
             'region': "The Invasion (MAP19) Main"},
    361156: {'name': 'The Invasion (MAP19) - Super Shotgun',
             'episode': 2,
             'map': 9,
             'index': 33,
             'doom_type': 82,
             'region': "The Invasion (MAP19) Main"},
    361157: {'name': 'The Invasion (MAP19) - Chaingun',
             'episode': 2,
             'map': 9,
             'index': 34,
             'doom_type': 2002,
             'region': "The Invasion (MAP19) Main"},
    361158: {'name': 'The Invasion (MAP19) - Mega Armor',
             'episode': 2,
             'map': 9,
             'index': 56,
             'doom_type': 2019,
             'region': "The Invasion (MAP19) Main"},
    361159: {'name': 'The Invasion (MAP19) - Plasma gun',
             'episode': 2,
             'map': 9,
             'index': 153,
             'doom_type': 2004,
             'region': "The Invasion (MAP19) Yellow"},
    361160: {'name': 'The Invasion (MAP19) - Berserk',
             'episode': 2,
             'map': 9,
             'index': 188,
             'doom_type': 2023,
             'region': "The Invasion (MAP19) Main"},
    361161: {'name': 'The Invasion (MAP19) - Exit',
             'episode': 2,
             'map': 9,
             'index': -1,
             'doom_type': -1,
             'region': "The Invasion (MAP19) Yellow"},
    361162: {'name': 'Death Row (MAP20) - Red keycard',
             'episode': 2,
             'map': 10,
             'index': 1,
             'doom_type': 13,
             'region': "Death Row (MAP20) Blue Ledge"},
    361163: {'name': 'Death Row (MAP20) - BFG9000',
             'episode': 2,
             'map': 10,
             'index': 2,
             'doom_type': 2006,
             'region': "Death Row (MAP20) Main"},
    361164: {'name': 'Death Row (MAP20) - Super Shotgun',
             'episode': 2,
             'map': 10,
             'index': 8,
             'doom_type': 82,
             'region': "Death Row (MAP20) Main"},
    361165: {'name': 'Death Row (MAP20) - Blue keycard',
             'episode': 2,
             'map': 10,
             'index': 17,
             'doom_type': 5,
             'region': "Death Row (MAP20) Main"},
    361166: {'name': 'Death Row (MAP20) - Chaingun',
             'episode': 2,
             'map': 10,
             'index': 89,
             'doom_type': 2002,
             'region': "Death Row (MAP20) Main"},
    361167: {'name': 'Death Row (MAP20) - Armor',
             'episode': 2,
             'map': 10,
             'index': 109,
             'doom_type': 2018,
             'region': "Death Row (MAP20) Main"},
    361168: {'name': 'Death Row (MAP20) - Rocket launcher',
             'episode': 2,
             'map': 10,
             'index': 110,
             'doom_type': 2003,
             'region': "Death Row (MAP20) Blue"},
    361169: {'name': 'Death Row (MAP20) - Backpack',
             'episode': 2,
             'map': 10,
             'index': 161,
             'doom_type': 8,
             'region': "Death Row (MAP20) Blue"},
    361170: {'name': 'Death Row (MAP20) - Backpack 2',
             'episode': 2,
             'map': 10,
             'index': 162,
             'doom_type': 8,
             'region': "Death Row (MAP20) Blue"},
    361171: {'name': 'Death Row (MAP20) - Backpack 3',
             'episode': 2,
             'map': 10,
             'index': 163,
             'doom_type': 8,
             'region': "Death Row (MAP20) Blue"},
    361172: {'name': 'Death Row (MAP20) - Supercharge',
             'episode': 2,
             'map': 10,
             'index': 164,
             'doom_type': 2013,
             'region': "Death Row (MAP20) Blue"},
    361173: {'name': 'Death Row (MAP20) - Berserk',
             'episode': 2,
             'map': 10,
             'index': 165,
             'doom_type': 2023,
             'region': "Death Row (MAP20) Blue"},
    361174: {'name': 'Death Row (MAP20) - Armor 2',
             'episode': 2,
             'map': 10,
             'index': 212,
             'doom_type': 2018,
             'region': "Death Row (MAP20) Red"},
    361175: {'name': 'Death Row (MAP20) - Invulnerability',
             'episode': 2,
             'map': 10,
             'index': 213,
             'doom_type': 2022,
             'region': "Death Row (MAP20) Red"},
    361176: {'name': 'Death Row (MAP20) - Computer area map',
             'episode': 2,
             'map': 10,
             'index': 214,
             'doom_type': 2026,
             'region': "Death Row (MAP20) Red"},
    361177: {'name': 'Death Row (MAP20) - Rocket launcher 2',
             'episode': 2,
             'map': 10,
             'index': 246,
             'doom_type': 2003,
             'region': "Death Row (MAP20) Red"},
    361178: {'name': 'Death Row (MAP20) - Exit',
             'episode': 2,
             'map': 10,
             'index': -1,
             'doom_type': -1,
             'region': "Death Row (MAP20) Red"},
    361179: {'name': 'Blood Lust (MAP21) - Red skull key',
             'episode': 3,
             'map': 1,
             'index': 1,
             'doom_type': 38,
             'region': "Blood Lust (MAP21) Main"},
    361180: {'name': 'Blood Lust (MAP21) - Shotgun',
             'episode': 3,
             'map': 1,
             'index': 36,
             'doom_type': 2001,
             'region': "Blood Lust (MAP21) Start"},
    361181: {'name': 'Blood Lust (MAP21) - Super Shotgun',
             'episode': 3,
             'map': 1,
             'index': 44,
             'doom_type': 82,
             'region': "Blood Lust (MAP21) Main"},
    361182: {'name': 'Blood Lust (MAP21) - Berserk',
             'episode': 3,
             'map': 1,
             'index': 59,
             'doom_type': 2023,
             'region': "Blood Lust (MAP21) Main"},
    361183: {'name': 'Blood Lust (MAP21) - Rocket launcher',
             'episode': 3,
             'map': 1,
             'index': 117,
             'doom_type': 2003,
             'region': "Blood Lust (MAP21) Red"},
    361184: {'name': 'Blood Lust (MAP21) - Exit',
             'episode': 3,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "Blood Lust (MAP21) Red Exit"},
    361185: {'name': 'Firestorm Tomb (MAP22) - Yellow skull key',
             'episode': 3,
             'map': 2,
             'index': 20,
             'doom_type': 39,
             'region': "Firestorm Tomb (MAP22) Main"},
    361186: {'name': 'Firestorm Tomb (MAP22) - Red skull key',
             'episode': 3,
             'map': 2,
             'index': 21,
             'doom_type': 38,
             'region': "Firestorm Tomb (MAP22) Yellow"},
    361187: {'name': 'Firestorm Tomb (MAP22) - Supercharge',
             'episode': 3,
             'map': 2,
             'index': 22,
             'doom_type': 2013,
             'region': "Firestorm Tomb (MAP22) Main"},
    361188: {'name': 'Firestorm Tomb (MAP22) - Berserk',
             'episode': 3,
             'map': 2,
             'index': 50,
             'doom_type': 2023,
             'region': "Firestorm Tomb (MAP22) Main"},
    361189: {'name': 'Firestorm Tomb (MAP22) - Super Shotgun',
             'episode': 3,
             'map': 2,
             'index': 63,
             'doom_type': 82,
             'region': "Firestorm Tomb (MAP22) Main"},
    361190: {'name': 'Firestorm Tomb (MAP22) - Rocket launcher',
             'episode': 3,
             'map': 2,
             'index': 179,
             'doom_type': 2003,
             'region': "Firestorm Tomb (MAP22) Main"},
    361191: {'name': 'Firestorm Tomb (MAP22) - Mega Armor',
             'episode': 3,
             'map': 2,
             'index': 209,
             'doom_type': 2019,
             'region': "Firestorm Tomb (MAP22) Main"},
    361192: {'name': 'Firestorm Tomb (MAP22) - Exit',
             'episode': 3,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "Firestorm Tomb (MAP22) Red"},
    361193: {'name': 'Dungeon of Inferno (MAP23) - Red skull key',
             'episode': 3,
             'map': 3,
             'index': 2,
             'doom_type': 38,
             'region': "Dungeon of Inferno (MAP23) Main"},
    361194: {'name': 'Dungeon of Inferno (MAP23) - Blue skull key',
             'episode': 3,
             'map': 3,
             'index': 3,
             'doom_type': 40,
             'region': "Dungeon of Inferno (MAP23) Red"},
    361195: {'name': 'Dungeon of Inferno (MAP23) - Supercharge',
             'episode': 3,
             'map': 3,
             'index': 5,
             'doom_type': 2013,
             'region': "Dungeon of Inferno (MAP23) Main"},
    361196: {'name': 'Dungeon of Inferno (MAP23) - Super Shotgun',
             'episode': 3,
             'map': 3,
             'index': 108,
             'doom_type': 82,
             'region': "Dungeon of Inferno (MAP23) Main"},
    361197: {'name': 'Dungeon of Inferno (MAP23) - Rocket launcher',
             'episode': 3,
             'map': 3,
             'index': 113,
             'doom_type': 2003,
             'region': "Dungeon of Inferno (MAP23) Red"},
    361198: {'name': 'Dungeon of Inferno (MAP23) - Armor',
             'episode': 3,
             'map': 3,
             'index': 130,
             'doom_type': 2018,
             'region': "Dungeon of Inferno (MAP23) Main"},
    361199: {'name': 'Dungeon of Inferno (MAP23) - Exit',
             'episode': 3,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "Dungeon of Inferno (MAP23) Blue"},
    361200: {'name': 'Cavern of the Evil Spirit (MAP24) - Blue skull key',
             'episode': 3,
             'map': 4,
             'index': 6,
             'doom_type': 40,
             'region': "Cavern of the Evil Spirit (MAP24) Main"},
    361201: {'name': 'Cavern of the Evil Spirit (MAP24) - Red skull key',
             'episode': 3,
             'map': 4,
             'index': 26,
             'doom_type': 38,
             'region': "Cavern of the Evil Spirit (MAP24) Blue"},
    361202: {'name': 'Cavern of the Evil Spirit (MAP24) - Super Shotgun',
             'episode': 3,
             'map': 4,
             'index': 49,
             'doom_type': 82,
             'region': "Cavern of the Evil Spirit (MAP24) Main"},
    361203: {'name': 'Cavern of the Evil Spirit (MAP24) - Chaingun',
             'episode': 3,
             'map': 4,
             'index': 62,
             'doom_type': 2002,
             'region': "Cavern of the Evil Spirit (MAP24) Main"},
    361204: {'name': 'Cavern of the Evil Spirit (MAP24) - Armor',
             'episode': 3,
             'map': 4,
             'index': 67,
             'doom_type': 2018,
             'region': "Cavern of the Evil Spirit (MAP24) Main"},
    361205: {'name': 'Cavern of the Evil Spirit (MAP24) - Backpack',
             'episode': 3,
             'map': 4,
             'index': 68,
             'doom_type': 8,
             'region': "Cavern of the Evil Spirit (MAP24) Main"},
    361206: {'name': 'Cavern of the Evil Spirit (MAP24) - Berserk',
             'episode': 3,
             'map': 4,
             'index': 111,
             'doom_type': 2023,
             'region': "Cavern of the Evil Spirit (MAP24) Main"},
    361207: {'name': 'Cavern of the Evil Spirit (MAP24) - Exit',
             'episode': 3,
             'map': 4,
             'index': -1,
             'doom_type': -1,
             'region': "Cavern of the Evil Spirit (MAP24) Red"},
    361208: {'name': 'Hellucination (MAP25) - Blue skull key',
             'episode': 3,
             'map': 5,
             'index': 8,
             'doom_type': 40,
             'region': "Hellucination (MAP25) Main"},
    361209: {'name': 'Hellucination (MAP25) - Yellow skull key',
             'episode': 3,
             'map': 5,
             'index': 10,
             'doom_type': 39,
             'region': "Hellucination (MAP25) Red"},
    361210: {'name': 'Hellucination (MAP25) - Red skull key',
             'episode': 3,
             'map': 5,
             'index': 11,
             'doom_type': 38,
             'region': "Hellucination (MAP25) Blue"},
    361211: {'name': 'Hellucination (MAP25) - Super Shotgun',
             'episode': 3,
             'map': 5,
             'index': 41,
             'doom_type': 82,
             'region': "Hellucination (MAP25) Main"},
    361212: {'name': 'Hellucination (MAP25) - Chainsaw',
             'episode': 3,
             'map': 5,
             'index': 42,
             'doom_type': 2005,
             'region': "Hellucination (MAP25) Main"},
    361213: {'name': 'Hellucination (MAP25) - Armor',
             'episode': 3,
             'map': 5,
             'index': 82,
             'doom_type': 2018,
             'region': "Hellucination (MAP25) Blue"},
    361214: {'name': 'Hellucination (MAP25) - Berserk',
             'episode': 3,
             'map': 5,
             'index': 87,
             'doom_type': 2023,
             'region': "Hellucination (MAP25) Blue"},
    361215: {'name': 'Hellucination (MAP25) - Plasma gun',
             'episode': 3,
             'map': 5,
             'index': 162,
             'doom_type': 2004,
             'region': "Hellucination (MAP25) Red"},
    361216: {'name': 'Hellucination (MAP25) - Exit',
             'episode': 3,
             'map': 5,
             'index': -1,
             'doom_type': -1,
             'region': "Hellucination (MAP25) Yellow"},
    361217: {'name': 'Valley of Brimstone (MAP26) - Yellow skull key',
             'episode': 3,
             'map': 6,
             'index': 8,
             'doom_type': 39,
             'region': "Valley of Brimstone (MAP26) Main"},
    361218: {'name': 'Valley of Brimstone (MAP26) - Super Shotgun',
             'episode': 3,
             'map': 6,
             'index': 30,
             'doom_type': 82,
             'region': "Valley of Brimstone (MAP26) Main"},
    361219: {'name': 'Valley of Brimstone (MAP26) - Supercharge',
             'episode': 3,
             'map': 6,
             'index': 44,
             'doom_type': 2013,
             'region': "Valley of Brimstone (MAP26) Main"},
    361220: {'name': 'Valley of Brimstone (MAP26) - Rocket launcher',
             'episode': 3,
             'map': 6,
             'index': 73,
             'doom_type': 2003,
             'region': "Valley of Brimstone (MAP26) Main"},
    361221: {'name': 'Valley of Brimstone (MAP26) - Armor',
             'episode': 3,
             'map': 6,
             'index': 95,
             'doom_type': 2018,
             'region': "Valley of Brimstone (MAP26) Main"},
    361222: {'name': 'Valley of Brimstone (MAP26) - Plasma gun',
             'episode': 3,
             'map': 6,
             'index': 97,
             'doom_type': 2004,
             'region': "Valley of Brimstone (MAP26) Main"},
    361223: {'name': 'Valley of Brimstone (MAP26) - Exit',
             'episode': 3,
             'map': 6,
             'index': -1,
             'doom_type': -1,
             'region': "Valley of Brimstone (MAP26) Yellow"},
    361224: {'name': 'Dissect (MAP27) - Red skull key',
             'episode': 3,
             'map': 7,
             'index': 9,
             'doom_type': 38,
             'region': "Dissect (MAP27) Main"},
    361225: {'name': 'Dissect (MAP27) - Super Shotgun',
             'episode': 3,
             'map': 7,
             'index': 18,
             'doom_type': 82,
             'region': "Dissect (MAP27) Start"},
    361226: {'name': 'Dissect (MAP27) - Shotgun',
             'episode': 3,
             'map': 7,
             'index': 34,
             'doom_type': 2001,
             'region': "Dissect (MAP27) Start"},
    361227: {'name': 'Dissect (MAP27) - Chaingun',
             'episode': 3,
             'map': 7,
             'index': 35,
             'doom_type': 2002,
             'region': "Dissect (MAP27) Start"},
    361228: {'name': 'Dissect (MAP27) - Berserk',
             'episode': 3,
             'map': 7,
             'index': 88,
             'doom_type': 2023,
             'region': "Dissect (MAP27) Main"},
    361229: {'name': 'Dissect (MAP27) - Shotgun 2',
             'episode': 3,
             'map': 7,
             'index': 215,
             'doom_type': 2001,
             'region': "Dissect (MAP27) Start"},
    361230: {'name': 'Dissect (MAP27) - Shotgun 3',
             'episode': 3,
             'map': 7,
             'index': 217,
             'doom_type': 2001,
             'region': "Dissect (MAP27) Main"},
    361231: {'name': 'Dissect (MAP27) - Shotgun 4',
             'episode': 3,
             'map': 7,
             'index': 219,
             'doom_type': 2001,
             'region': "Dissect (MAP27) Main"},
    361232: {'name': 'Dissect (MAP27) - Exit',
             'episode': 3,
             'map': 7,
             'index': -1,
             'doom_type': -1,
             'region': "Dissect (MAP27) Red"},
    361233: {'name': 'Unholy Demise (MAP28) - Chaingun',
             'episode': 3,
             'map': 8,
             'index': 4,
             'doom_type': 2002,
             'region': "Unholy Demise (MAP28) Main"},
    361234: {'name': 'Unholy Demise (MAP28) - Red skull key',
             'episode': 3,
             'map': 8,
             'index': 28,
             'doom_type': 38,
             'region': "Unholy Demise (MAP28) Main"},
    361235: {'name': 'Unholy Demise (MAP28) - Super Shotgun',
             'episode': 3,
             'map': 8,
             'index': 71,
             'doom_type': 82,
             'region': "Unholy Demise (MAP28) Main"},
    361236: {'name': 'Unholy Demise (MAP28) - Backpack',
             'episode': 3,
             'map': 8,
             'index': 106,
             'doom_type': 8,
             'region': "Unholy Demise (MAP28) Main"},
    361237: {'name': 'Unholy Demise (MAP28) - Yellow skull key',
             'episode': 3,
             'map': 8,
             'index': 152,
             'doom_type': 39,
             'region': "Unholy Demise (MAP28) Red"},
    361238: {'name': 'Unholy Demise (MAP28) - Rocket launcher',
             'episode': 3,
             'map': 8,
             'index': 184,
             'doom_type': 2003,
             'region': "Unholy Demise (MAP28) Red"},
    361239: {'name': 'Unholy Demise (MAP28) - Supercharge',
             'episode': 3,
             'map': 8,
             'index': 193,
             'doom_type': 2013,
             'region': "Unholy Demise (MAP28) Red"},
    361240: {'name': 'Unholy Demise (MAP28) - Armor',
             'episode': 3,
             'map': 8,
             'index': 228,
             'doom_type': 2018,
             'region': "Unholy Demise (MAP28) Main"},
    361241: {'name': 'Unholy Demise (MAP28) - Shotgun',
             'episode': 3,
             'map': 8,
             'index': 283,
             'doom_type': 2001,
             'region': "Unholy Demise (MAP28) Main"},
    361242: {'name': 'Unholy Demise (MAP28) - Exit',
             'episode': 3,
             'map': 8,
             'index': -1,
             'doom_type': -1,
             'region': "Unholy Demise (MAP28) Yellow"},
    361243: {'name': 'Den of Torture (MAP29) - Rocket launcher',
             'episode': 3,
             'map': 9,
             'index': 25,
             'doom_type': 2003,
             'region': "Den of Torture (MAP29) Main"},
    361244: {'name': 'Den of Torture (MAP29) - Blue skull key',
             'episode': 3,
             'map': 9,
             'index': 35,
             'doom_type': 40,
             'region': "Den of Torture (MAP29) Main"},
    361245: {'name': 'Den of Torture (MAP29) - Super Shotgun',
             'episode': 3,
             'map': 9,
             'index': 76,
             'doom_type': 82,
             'region': "Den of Torture (MAP29) Main"},
    361246: {'name': 'Den of Torture (MAP29) - Backpack',
             'episode': 3,
             'map': 9,
             'index': 81,
             'doom_type': 8,
             'region': "Den of Torture (MAP29) Main"},
    361247: {'name': 'Den of Torture (MAP29) - Chaingun',
             'episode': 3,
             'map': 9,
             'index': 87,
             'doom_type': 2002,
             'region': "Den of Torture (MAP29) Main"},
    361248: {'name': 'Den of Torture (MAP29) - Mega Armor',
             'episode': 3,
             'map': 9,
             'index': 93,
             'doom_type': 2019,
             'region': "Den of Torture (MAP29) Main"},
    361249: {'name': 'Den of Torture (MAP29) - Backpack 2',
             'episode': 3,
             'map': 9,
             'index': 121,
             'doom_type': 8,
             'region': "Den of Torture (MAP29) Main"},
    361250: {'name': 'Den of Torture (MAP29) - Exit',
             'episode': 3,
             'map': 9,
             'index': -1,
             'doom_type': -1,
             'region': "Den of Torture (MAP29) Blue"},
    361251: {'name': 'Eternal Core (MAP30) - Chainsaw',
             'episode': 3,
             'map': 10,
             'index': 46,
             'doom_type': 2005,
             'region': "Eternal Core (MAP30) Safe Area"},
    361252: {'name': 'Eternal Core (MAP30) - Shotgun',
             'episode': 3,
             'map': 10,
             'index': 47,
             'doom_type': 2001,
             'region': "Eternal Core (MAP30) Safe Area"},
    361253: {'name': 'Eternal Core (MAP30) - Super Shotgun',
             'episode': 3,
             'map': 10,
             'index': 48,
             'doom_type': 82,
             'region': "Eternal Core (MAP30) Safe Area"},
    361254: {'name': 'Eternal Core (MAP30) - Chaingun',
             'episode': 3,
             'map': 10,
             'index': 49,
             'doom_type': 2002,
             'region': "Eternal Core (MAP30) Safe Area"},
    361255: {'name': 'Eternal Core (MAP30) - Rocket launcher',
             'episode': 3,
             'map': 10,
             'index': 50,
             'doom_type': 2003,
             'region': "Eternal Core (MAP30) Safe Area"},
    361256: {'name': 'Eternal Core (MAP30) - Plasma gun',
             'episode': 3,
             'map': 10,
             'index': 51,
             'doom_type': 2004,
             'region': "Eternal Core (MAP30) Safe Area"},
    361257: {'name': 'Eternal Core (MAP30) - BFG9000',
             'episode': 3,
             'map': 10,
             'index': 52,
             'doom_type': 2006,
             'region': "Eternal Core (MAP30) Safe Area"},
    361258: {'name': 'Eternal Core (MAP30) - Backpack',
             'episode': 3,
             'map': 10,
             'index': 53,
             'doom_type': 8,
             'region': "Eternal Core (MAP30) Safe Area"},
    361259: {'name': 'Eternal Core (MAP30) - Supercharge',
             'episode': 3,
             'map': 10,
             'index': 54,
             'doom_type': 2013,
             'region': "Eternal Core (MAP30) Safe Area"},
    361260: {'name': 'Eternal Core (MAP30) - Mega Armor',
             'episode': 3,
             'map': 10,
             'index': 105,
             'doom_type': 2019,
             'region': "Eternal Core (MAP30) Main"},
    361261: {'name': 'Eternal Core (MAP30) - Backpack 2',
             'episode': 3,
             'map': 10,
             'index': 158,
             'doom_type': 8,
             'region': "Eternal Core (MAP30) Main"},
    361262: {'name': 'Eternal Core (MAP30) - Backpack 3',
             'episode': 3,
             'map': 10,
             'index': 159,
             'doom_type': 8,
             'region': "Eternal Core (MAP30) Main"},
    361263: {'name': 'Eternal Core (MAP30) - Backpack 4',
             'episode': 3,
             'map': 10,
             'index': 160,
             'doom_type': 8,
             'region': "Eternal Core (MAP30) Main"},
    361264: {'name': 'Eternal Core (MAP30) - Invulnerability',
             'episode': 3,
             'map': 10,
             'index': 202,
             'doom_type': 2022,
             'region': "Eternal Core (MAP30) Main"},
    361265: {'name': 'Eternal Core (MAP30) - Exit',
             'episode': 3,
             'map': 10,
             'index': -1,
             'doom_type': -1,
             'region': "Eternal Core (MAP30) Main"},
    361266: {'name': 'Creepy (MAP31) - Megasphere',
             'episode': 4,
             'map': 1,
             'index': 6,
             'doom_type': 83,
             'region': "Creepy (MAP31) Main"},
    361267: {'name': 'Creepy (MAP31) - Red keycard',
             'episode': 4,
             'map': 1,
             'index': 7,
             'doom_type': 13,
             'region': "Creepy (MAP31) Main"},
    361268: {'name': 'Creepy (MAP31) - Yellow keycard',
             'episode': 4,
             'map': 1,
             'index': 8,
             'doom_type': 6,
             'region': "Creepy (MAP31) Main"},
    361269: {'name': 'Creepy (MAP31) - Blue keycard',
             'episode': 4,
             'map': 1,
             'index': 9,
             'doom_type': 5,
             'region': "Creepy (MAP31) Main"},
    361270: {'name': 'Creepy (MAP31) - Super Shotgun',
             'episode': 4,
             'map': 1,
             'index': 11,
             'doom_type': 82,
             'region': "Creepy (MAP31) Main"},
    361271: {'name': 'Creepy (MAP31) - Shotgun',
             'episode': 4,
             'map': 1,
             'index': 163,
             'doom_type': 2001,
             'region': "Creepy (MAP31) Main"},
    361272: {'name': 'Creepy (MAP31) - Shotgun 2',
             'episode': 4,
             'map': 1,
             'index': 167,
             'doom_type': 2001,
             'region': "Creepy (MAP31) Main"},
    361273: {'name': 'Creepy (MAP31) - Berserk',
             'episode': 4,
             'map': 1,
             'index': 203,
             'doom_type': 2023,
             'region': "Creepy (MAP31) Main"},
    361274: {'name': 'Creepy (MAP31) - Computer area map',
             'episode': 4,
             'map': 1,
             'index': 281,
             'doom_type': 2026,
             'region': "Creepy (MAP31) Main"},
    361275: {'name': 'Creepy (MAP31) - Exit',
             'episode': 4,
             'map': 1,
             'index': -1,
             'doom_type': -1,
             'region': "Creepy (MAP31) All Keys"},
    361276: {'name': 'Condemnation (MAP32) - Blue skull key',
             'episode': 4,
             'map': 2,
             'index': 13,
             'doom_type': 40,
             'region': "Condemnation (MAP32) Main"},
    361277: {'name': 'Condemnation (MAP32) - Supercharge',
             'episode': 4,
             'map': 2,
             'index': 30,
             'doom_type': 2013,
             'region': "Condemnation (MAP32) Main"},
    361278: {'name': 'Condemnation (MAP32) - Yellow skull key',
             'episode': 4,
             'map': 2,
             'index': 31,
             'doom_type': 39,
             'region': "Condemnation (MAP32) Red"},
    361279: {'name': 'Condemnation (MAP32) - Red skull key',
             'episode': 4,
             'map': 2,
             'index': 40,
             'doom_type': 38,
             'region': "Condemnation (MAP32) Blue"},
    361280: {'name': 'Condemnation (MAP32) - BFG9000',
             'episode': 4,
             'map': 2,
             'index': 84,
             'doom_type': 2006,
             'region': "Condemnation (MAP32) Yellow"},
    361281: {'name': 'Condemnation (MAP32) - Chainsaw',
             'episode': 4,
             'map': 2,
             'index': 91,
             'doom_type': 2005,
             'region': "Condemnation (MAP32) Main"},
    361282: {'name': 'Condemnation (MAP32) - Plasma gun',
             'episode': 4,
             'map': 2,
             'index': 102,
             'doom_type': 2004,
             'region': "Condemnation (MAP32) Main"},
    361283: {'name': 'Condemnation (MAP32) - Super Shotgun',
             'episode': 4,
             'map': 2,
             'index': 123,
             'doom_type': 82,
             'region': "Condemnation (MAP32) Main"},
    361284: {'name': 'Condemnation (MAP32) - Mega Armor',
             'episode': 4,
             'map': 2,
             'index': 261,
             'doom_type': 2019,
             'region': "Condemnation (MAP32) Main"},
    361285: {'name': 'Condemnation (MAP32) - Berserk',
             'episode': 4,
             'map': 2,
             'index': 303,
             'doom_type': 2023,
             'region': "Condemnation (MAP32) Main"},
    361286: {'name': 'Condemnation (MAP32) - Berserk 2',
             'episode': 4,
             'map': 2,
             'index': 335,
             'doom_type': 2023,
             'region': "Condemnation (MAP32) Red"},
    361287: {'name': 'Condemnation (MAP32) - Rocket launcher',
             'episode': 4,
             'map': 2,
             'index': 336,
             'doom_type': 2003,
             'region': "Condemnation (MAP32) Red"},
    361288: {'name': 'Condemnation (MAP32) - Megasphere',
             'episode': 4,
             'map': 2,
             'index': 424,
             'doom_type': 83,
             'region': "Condemnation (MAP32) Main"},
    361289: {'name': 'Condemnation (MAP32) - Backpack',
             'episode': 4,
             'map': 2,
             'index': 425,
             'doom_type': 8,
             'region': "Condemnation (MAP32) Main"},
    361290: {'name': 'Condemnation (MAP32) - Backpack 2',
             'episode': 4,
             'map': 2,
             'index': 426,
             'doom_type': 8,
             'region': "Condemnation (MAP32) Main"},
    361291: {'name': 'Condemnation (MAP32) - Backpack 3',
             'episode': 4,
             'map': 2,
             'index': 427,
             'doom_type': 8,
             'region': "Condemnation (MAP32) Main"},
    361292: {'name': 'Condemnation (MAP32) - Chaingun',
             'episode': 4,
             'map': 2,
             'index': 447,
             'doom_type': 2002,
             'region': "Condemnation (MAP32) Blue"},
    361293: {'name': 'Condemnation (MAP32) - Computer area map',
             'episode': 4,
             'map': 2,
             'index': 475,
             'doom_type': 2026,
             'region': "Condemnation (MAP32) Blue"},
    361294: {'name': 'Condemnation (MAP32) - Exit',
             'episode': 4,
             'map': 2,
             'index': -1,
             'doom_type': -1,
             'region': "Condemnation (MAP32) Red"},
    361295: {'name': 'Zerstorung (MAP33) - Blue skull key',
             'episode': 4,
             'map': 3,
             'index': 4,
             'doom_type': 40,
             'region': "Zerstorung (MAP33) Main"},
    361296: {'name': 'Zerstorung (MAP33) - Yellow skull key',
             'episode': 4,
             'map': 3,
             'index': 10,
             'doom_type': 39,
             'region': "Zerstorung (MAP33) Bosses"},
    361297: {'name': 'Zerstorung (MAP33) - Red skull key',
             'episode': 4,
             'map': 3,
             'index': 11,
             'doom_type': 38,
             'region': "Zerstorung (MAP33) Bosses"},
    361298: {'name': 'Zerstorung (MAP33) - Super Shotgun',
             'episode': 4,
             'map': 3,
             'index': 173,
             'doom_type': 82,
             'region': "Zerstorung (MAP33) Bosses"},
    361299: {'name': 'Zerstorung (MAP33) - BFG9000',
             'episode': 4,
             'map': 3,
             'index': 174,
             'doom_type': 2006,
             'region': "Zerstorung (MAP33) Bosses"},
    361300: {'name': 'Zerstorung (MAP33) - Megasphere',
             'episode': 4,
             'map': 3,
             'index': 177,
             'doom_type': 83,
             'region': "Zerstorung (MAP33) Bosses"},
    361301: {'name': 'Zerstorung (MAP33) - Chaingun',
             'episode': 4,
             'map': 3,
             'index': 178,
             'doom_type': 2002,
             'region': "Zerstorung (MAP33) Bosses"},
    361302: {'name': 'Zerstorung (MAP33) - Chaingun 2',
             'episode': 4,
             'map': 3,
             'index': 179,
             'doom_type': 2002,
             'region': "Zerstorung (MAP33) Bosses"},
    361303: {'name': 'Zerstorung (MAP33) - Chaingun 3',
             'episode': 4,
             'map': 3,
             'index': 180,
             'doom_type': 2002,
             'region': "Zerstorung (MAP33) Bosses"},
    361304: {'name': 'Zerstorung (MAP33) - Shotgun',
             'episode': 4,
             'map': 3,
             'index': 197,
             'doom_type': 2001,
             'region': "Zerstorung (MAP33) Main"},
    361305: {'name': 'Zerstorung (MAP33) - Berserk',
             'episode': 4,
             'map': 3,
             'index': 286,
             'doom_type': 2023,
             'region': "Zerstorung (MAP33) Main"},
    361306: {'name': 'Zerstorung (MAP33) - Supercharge',
             'episode': 4,
             'map': 3,
             'index': 288,
             'doom_type': 2013,
             'region': "Zerstorung (MAP33) Blue"},
    361307: {'name': 'Zerstorung (MAP33) - Rocket launcher',
             'episode': 4,
             'map': 3,
             'index': 299,
             'doom_type': 2003,
             'region': "Zerstorung (MAP33) Blue"},
    361308: {'name': 'Zerstorung (MAP33) - Chaingun 4',
             'episode': 4,
             'map': 3,
             'index': 312,
             'doom_type': 2002,
             'region': "Zerstorung (MAP33) Start"},
    361309: {'name': 'Zerstorung (MAP33) - Supercharge 2',
             'episode': 4,
             'map': 3,
             'index': 357,
             'doom_type': 2013,
             'region': "Zerstorung (MAP33) Bosses"},
    361310: {'name': 'Zerstorung (MAP33) - Armor',
             'episode': 4,
             'map': 3,
             'index': 363,
             'doom_type': 2018,
             'region': "Zerstorung (MAP33) Blue"},
    361311: {'name': 'Zerstorung (MAP33) - Invulnerability',
             'episode': 4,
             'map': 3,
             'index': 379,
             'doom_type': 2022,
             'region': "Zerstorung (MAP33) Bosses"},
    361312: {'name': 'Zerstorung (MAP33) - Plasma gun',
             'episode': 4,
             'map': 3,
             'index': 380,
             'doom_type': 2004,
             'region': "Zerstorung (MAP33) Bosses"},
    361313: {'name': 'Zerstorung (MAP33) - Backpack',
             'episode': 4,
             'map': 3,
             'index': 397,
             'doom_type': 8,
             'region': "Zerstorung (MAP33) Bosses"},
    361314: {'name': 'Zerstorung (MAP33) - Super Shotgun 2',
             'episode': 4,
             'map': 3,
             'index': 416,
             'doom_type': 82,
             'region': "Zerstorung (MAP33) Blue"},
    361315: {'name': 'Zerstorung (MAP33) - Partial invisibility',
             'episode': 4,
             'map': 3,
             'index': 446,
             'doom_type': 2024,
             'region': "Zerstorung (MAP33) Blue"},
    361316: {'name': 'Zerstorung (MAP33) - Exit',
             'episode': 4,
             'map': 3,
             'index': -1,
             'doom_type': -1,
             'region': "Zerstorung (MAP33) All Keys"},
}


location_name_groups: Dict[str, Set[str]] = {
    'Blood Lust (MAP21)': {
        'Blood Lust (MAP21) - Berserk',
        'Blood Lust (MAP21) - Exit',
        'Blood Lust (MAP21) - Red skull key',
        'Blood Lust (MAP21) - Rocket launcher',
        'Blood Lust (MAP21) - Shotgun',
        'Blood Lust (MAP21) - Super Shotgun',
    },
    'Bruiser Fortress (MAP16)': {
        'Bruiser Fortress (MAP16) - Armor',
        'Bruiser Fortress (MAP16) - Backpack',
        'Bruiser Fortress (MAP16) - Exit',
        'Bruiser Fortress (MAP16) - Rocket launcher',
        'Bruiser Fortress (MAP16) - Shotgun',
        'Bruiser Fortress (MAP16) - Super Shotgun',
        'Bruiser Fortress (MAP16) - Supercharge',
        'Bruiser Fortress (MAP16) - Yellow skull key',
    },
    'Canyon Hub (MAP04)': {
        'Canyon Hub (MAP04) - Armor',
        'Canyon Hub (MAP04) - Backpack',
        'Canyon Hub (MAP04) - Berserk',
        'Canyon Hub (MAP04) - Exit',
        'Canyon Hub (MAP04) - Shotgun',
        'Canyon Hub (MAP04) - Super Shotgun',
        'Canyon Hub (MAP04) - Supercharge',
        'Canyon Hub (MAP04) - Yellow keycard',
    },
    'Cargo Bay (MAP10)': {
        'Cargo Bay (MAP10) - Backpack',
        'Cargo Bay (MAP10) - Backpack 2',
        'Cargo Bay (MAP10) - Berserk',
        'Cargo Bay (MAP10) - Exit',
        'Cargo Bay (MAP10) - Mega Armor',
        'Cargo Bay (MAP10) - Plasma gun',
        'Cargo Bay (MAP10) - Red keycard',
        'Cargo Bay (MAP10) - Super Shotgun',
        'Cargo Bay (MAP10) - Supercharge',
    },
    'Cavern of the Evil Spirit (MAP24)': {
        'Cavern of the Evil Spirit (MAP24) - Armor',
        'Cavern of the Evil Spirit (MAP24) - Backpack',
        'Cavern of the Evil Spirit (MAP24) - Berserk',
        'Cavern of the Evil Spirit (MAP24) - Blue skull key',
        'Cavern of the Evil Spirit (MAP24) - Chaingun',
        'Cavern of the Evil Spirit (MAP24) - Exit',
        'Cavern of the Evil Spirit (MAP24) - Red skull key',
        'Cavern of the Evil Spirit (MAP24) - Super Shotgun',
    },
    'Condemnation (MAP32)': {
        'Condemnation (MAP32) - BFG9000',
        'Condemnation (MAP32) - Backpack',
        'Condemnation (MAP32) - Backpack 2',
        'Condemnation (MAP32) - Backpack 3',
        'Condemnation (MAP32) - Berserk',
        'Condemnation (MAP32) - Berserk 2',
        'Condemnation (MAP32) - Blue skull key',
        'Condemnation (MAP32) - Chaingun',
        'Condemnation (MAP32) - Chainsaw',
        'Condemnation (MAP32) - Computer area map',
        'Condemnation (MAP32) - Exit',
        'Condemnation (MAP32) - Mega Armor',
        'Condemnation (MAP32) - Megasphere',
        'Condemnation (MAP32) - Plasma gun',
        'Condemnation (MAP32) - Red skull key',
        'Condemnation (MAP32) - Rocket launcher',
        'Condemnation (MAP32) - Super Shotgun',
        'Condemnation (MAP32) - Supercharge',
        'Condemnation (MAP32) - Yellow skull key',
    },
    'Constriction (MAP17)': {
        'Constriction (MAP17) - Berserk',
        'Constriction (MAP17) - Blue skull key',
        'Constriction (MAP17) - Chainsaw',
        'Constriction (MAP17) - Exit',
        'Constriction (MAP17) - Red skull key',
        'Constriction (MAP17) - Shotgun',
        'Constriction (MAP17) - Super Shotgun',
    },
    'Control Facility (MAP02)': {
        'Control Facility (MAP02) - Berserk',
        'Control Facility (MAP02) - Blue keycard',
        'Control Facility (MAP02) - Chaingun',
        'Control Facility (MAP02) - Exit',
        'Control Facility (MAP02) - Mega Armor',
        'Control Facility (MAP02) - Red keycard',
        'Control Facility (MAP02) - Rocket launcher',
        'Control Facility (MAP02) - Shotgun',
        'Control Facility (MAP02) - Super Shotgun',
        'Control Facility (MAP02) - Yellow keycard',
    },
    'Creepy (MAP31)': {
        'Creepy (MAP31) - Berserk',
        'Creepy (MAP31) - Blue keycard',
        'Creepy (MAP31) - Computer area map',
        'Creepy (MAP31) - Exit',
        'Creepy (MAP31) - Megasphere',
        'Creepy (MAP31) - Red keycard',
        'Creepy (MAP31) - Shotgun',
        'Creepy (MAP31) - Shotgun 2',
        'Creepy (MAP31) - Super Shotgun',
        'Creepy (MAP31) - Yellow keycard',
    },
    'Dark Crypt (MAP13)': {
        'Dark Crypt (MAP13) - Backpack',
        'Dark Crypt (MAP13) - Blue keycard',
        'Dark Crypt (MAP13) - Chainsaw',
        'Dark Crypt (MAP13) - Exit',
        'Dark Crypt (MAP13) - Megasphere',
        'Dark Crypt (MAP13) - Plasma gun',
        'Dark Crypt (MAP13) - Super Shotgun',
        'Dark Crypt (MAP13) - Yellow keycard',
    },
    'Death Row (MAP20)': {
        'Death Row (MAP20) - Armor',
        'Death Row (MAP20) - Armor 2',
        'Death Row (MAP20) - BFG9000',
        'Death Row (MAP20) - Backpack',
        'Death Row (MAP20) - Backpack 2',
        'Death Row (MAP20) - Backpack 3',
        'Death Row (MAP20) - Berserk',
        'Death Row (MAP20) - Blue keycard',
        'Death Row (MAP20) - Chaingun',
        'Death Row (MAP20) - Computer area map',
        'Death Row (MAP20) - Exit',
        'Death Row (MAP20) - Invulnerability',
        'Death Row (MAP20) - Red keycard',
        'Death Row (MAP20) - Rocket launcher',
        'Death Row (MAP20) - Rocket launcher 2',
        'Death Row (MAP20) - Super Shotgun',
        'Death Row (MAP20) - Supercharge',
    },
    'Den of Torture (MAP29)': {
        'Den of Torture (MAP29) - Backpack',
        'Den of Torture (MAP29) - Backpack 2',
        'Den of Torture (MAP29) - Blue skull key',
        'Den of Torture (MAP29) - Chaingun',
        'Den of Torture (MAP29) - Exit',
        'Den of Torture (MAP29) - Mega Armor',
        'Den of Torture (MAP29) - Rocket launcher',
        'Den of Torture (MAP29) - Super Shotgun',
    },
    'Dissect (MAP27)': {
        'Dissect (MAP27) - Berserk',
        'Dissect (MAP27) - Chaingun',
        'Dissect (MAP27) - Exit',
        'Dissect (MAP27) - Red skull key',
        'Dissect (MAP27) - Shotgun',
        'Dissect (MAP27) - Shotgun 2',
        'Dissect (MAP27) - Shotgun 3',
        'Dissect (MAP27) - Shotgun 4',
        'Dissect (MAP27) - Super Shotgun',
    },
    'Dungeon of Inferno (MAP23)': {
        'Dungeon of Inferno (MAP23) - Armor',
        'Dungeon of Inferno (MAP23) - Blue skull key',
        'Dungeon of Inferno (MAP23) - Exit',
        'Dungeon of Inferno (MAP23) - Red skull key',
        'Dungeon of Inferno (MAP23) - Rocket launcher',
        'Dungeon of Inferno (MAP23) - Super Shotgun',
        'Dungeon of Inferno (MAP23) - Supercharge',
    },
    'Eternal Core (MAP30)': {
        'Eternal Core (MAP30) - BFG9000',
        'Eternal Core (MAP30) - Backpack',
        'Eternal Core (MAP30) - Backpack 2',
        'Eternal Core (MAP30) - Backpack 3',
        'Eternal Core (MAP30) - Backpack 4',
        'Eternal Core (MAP30) - Chaingun',
        'Eternal Core (MAP30) - Chainsaw',
        'Eternal Core (MAP30) - Exit',
        'Eternal Core (MAP30) - Invulnerability',
        'Eternal Core (MAP30) - Mega Armor',
        'Eternal Core (MAP30) - Plasma gun',
        'Eternal Core (MAP30) - Rocket launcher',
        'Eternal Core (MAP30) - Shotgun',
        'Eternal Core (MAP30) - Super Shotgun',
        'Eternal Core (MAP30) - Supercharge',
    },
    'Firestorm Tomb (MAP22)': {
        'Firestorm Tomb (MAP22) - Berserk',
        'Firestorm Tomb (MAP22) - Exit',
        'Firestorm Tomb (MAP22) - Mega Armor',
        'Firestorm Tomb (MAP22) - Red skull key',
        'Firestorm Tomb (MAP22) - Rocket launcher',
        'Firestorm Tomb (MAP22) - Super Shotgun',
        'Firestorm Tomb (MAP22) - Supercharge',
        'Firestorm Tomb (MAP22) - Yellow skull key',
    },
    'Heavyweight (MAP07)': {
        'Heavyweight (MAP07) - Backpack',
        'Heavyweight (MAP07) - Backpack 2',
        'Heavyweight (MAP07) - Backpack 3',
        'Heavyweight (MAP07) - Backpack 4',
        'Heavyweight (MAP07) - Berserk',
        'Heavyweight (MAP07) - Chaingun',
        'Heavyweight (MAP07) - Exit',
        'Heavyweight (MAP07) - Mega Armor',
        'Heavyweight (MAP07) - Partial invisibility',
        'Heavyweight (MAP07) - Plasma gun',
        'Heavyweight (MAP07) - Rocket launcher',
        'Heavyweight (MAP07) - Shotgun',
        'Heavyweight (MAP07) - Super Shotgun',
    },
    'Hellucination (MAP25)': {
        'Hellucination (MAP25) - Armor',
        'Hellucination (MAP25) - Berserk',
        'Hellucination (MAP25) - Blue skull key',
        'Hellucination (MAP25) - Chainsaw',
        'Hellucination (MAP25) - Exit',
        'Hellucination (MAP25) - Plasma gun',
        'Hellucination (MAP25) - Red skull key',
        'Hellucination (MAP25) - Super Shotgun',
        'Hellucination (MAP25) - Yellow skull key',
    },
    'Nuclear Power Station (MAP09)': {
        'Nuclear Power Station (MAP09) - Armor',
        'Nuclear Power Station (MAP09) - Berserk',
        'Nuclear Power Station (MAP09) - Blue keycard',
        'Nuclear Power Station (MAP09) - Chaingun',
        'Nuclear Power Station (MAP09) - Chainsaw',
        'Nuclear Power Station (MAP09) - Exit',
        'Nuclear Power Station (MAP09) - Red keycard',
        'Nuclear Power Station (MAP09) - Rocket launcher',
        'Nuclear Power Station (MAP09) - Super Shotgun',
        'Nuclear Power Station (MAP09) - Yellow keycard',
    },
    'Simbattle (MAP11)': {
        'Simbattle (MAP11) - BFG9000',
        'Simbattle (MAP11) - Backpack',
        'Simbattle (MAP11) - Berserk',
        'Simbattle (MAP11) - Blue keycard',
        'Simbattle (MAP11) - Chaingun',
        'Simbattle (MAP11) - Exit',
        'Simbattle (MAP11) - Invulnerability',
        'Simbattle (MAP11) - Mega Armor',
        'Simbattle (MAP11) - Megasphere',
        'Simbattle (MAP11) - Partial invisibility',
        'Simbattle (MAP11) - Plasma gun',
        'Simbattle (MAP11) - Red keycard',
        'Simbattle (MAP11) - Rocket launcher',
        'Simbattle (MAP11) - Super Shotgun',
        'Simbattle (MAP11) - Supercharge',
        'Simbattle (MAP11) - Yellow keycard',
    },
    'Skybase 300 (MAP05)': {
        'Skybase 300 (MAP05) - Armor',
        'Skybase 300 (MAP05) - Blue keycard',
        'Skybase 300 (MAP05) - Exit',
        'Skybase 300 (MAP05) - Rocket launcher',
        'Skybase 300 (MAP05) - Shotgun',
        'Skybase 300 (MAP05) - Super Shotgun',
        'Skybase 300 (MAP05) - Yellow keycard',
    },
    'The Alleyway (MAP03)': {
        'The Alleyway (MAP03) - Backpack',
        'The Alleyway (MAP03) - Berserk',
        'The Alleyway (MAP03) - Blue keycard',
        'The Alleyway (MAP03) - Chaingun',
        'The Alleyway (MAP03) - Exit',
        'The Alleyway (MAP03) - Supercharge',
    },
    'The Circle (MAP14)': {
        'The Circle (MAP14) - Armor',
        'The Circle (MAP14) - Berserk',
        'The Circle (MAP14) - Exit',
        'The Circle (MAP14) - Red skull key',
        'The Circle (MAP14) - Rocket launcher',
        'The Circle (MAP14) - Super Shotgun',
        'The Circle (MAP14) - Yellow skull key',
    },
    'The Invasion (MAP19)': {
        'The Invasion (MAP19) - Berserk',
        'The Invasion (MAP19) - Chaingun',
        'The Invasion (MAP19) - Exit',
        'The Invasion (MAP19) - Mega Armor',
        'The Invasion (MAP19) - Plasma gun',
        'The Invasion (MAP19) - Red skull key',
        'The Invasion (MAP19) - Rocket launcher',
        'The Invasion (MAP19) - Super Shotgun',
        'The Invasion (MAP19) - Supercharge',
        'The Invasion (MAP19) - Yellow skull key',
    },
    'The Spaceport (MAP01)': {
        'The Spaceport (MAP01) - Armor',
        'The Spaceport (MAP01) - Chaingun',
        'The Spaceport (MAP01) - Exit',
        'The Spaceport (MAP01) - Shotgun',
    },
    'Trouble Town (MAP15)': {
        'Trouble Town (MAP15) - BFG9000',
        'Trouble Town (MAP15) - Backpack',
        'Trouble Town (MAP15) - Berserk',
        'Trouble Town (MAP15) - Blue keycard',
        'Trouble Town (MAP15) - Exit',
        'Trouble Town (MAP15) - Mega Armor',
        'Trouble Town (MAP15) - Plasma gun',
        'Trouble Town (MAP15) - Red keycard',
        'Trouble Town (MAP15) - Rocket launcher',
        'Trouble Town (MAP15) - Shotgun',
        'Trouble Town (MAP15) - Super Shotgun',
        'Trouble Town (MAP15) - Supercharge',
        'Trouble Town (MAP15) - Yellow keycard',
    },
    'Unholy Demise (MAP28)': {
        'Unholy Demise (MAP28) - Armor',
        'Unholy Demise (MAP28) - Backpack',
        'Unholy Demise (MAP28) - Chaingun',
        'Unholy Demise (MAP28) - Exit',
        'Unholy Demise (MAP28) - Red skull key',
        'Unholy Demise (MAP28) - Rocket launcher',
        'Unholy Demise (MAP28) - Shotgun',
        'Unholy Demise (MAP28) - Super Shotgun',
        'Unholy Demise (MAP28) - Supercharge',
        'Unholy Demise (MAP28) - Yellow skull key',
    },
    'Valley of Brimstone (MAP26)': {
        'Valley of Brimstone (MAP26) - Armor',
        'Valley of Brimstone (MAP26) - Exit',
        'Valley of Brimstone (MAP26) - Plasma gun',
        'Valley of Brimstone (MAP26) - Rocket launcher',
        'Valley of Brimstone (MAP26) - Super Shotgun',
        'Valley of Brimstone (MAP26) - Supercharge',
        'Valley of Brimstone (MAP26) - Yellow skull key',
    },
    'Villa of Pain (MAP12)': {
        'Villa of Pain (MAP12) - Armor',
        'Villa of Pain (MAP12) - Berserk',
        'Villa of Pain (MAP12) - Exit',
        'Villa of Pain (MAP12) - Red skull key',
        'Villa of Pain (MAP12) - Super Shotgun',
        'Villa of Pain (MAP12) - Yellow skull key',
    },
    'Waste Disposal Plant (MAP08)': {
        'Waste Disposal Plant (MAP08) - Armor',
        'Waste Disposal Plant (MAP08) - Backpack',
        'Waste Disposal Plant (MAP08) - Blue keycard',
        'Waste Disposal Plant (MAP08) - Exit',
        'Waste Disposal Plant (MAP08) - Plasma gun',
        'Waste Disposal Plant (MAP08) - Red keycard',
        'Waste Disposal Plant (MAP08) - Rocket launcher',
        'Waste Disposal Plant (MAP08) - Super Shotgun',
        'Waste Disposal Plant (MAP08) - Supercharge',
    },
    'Whispering Corridor (MAP06)': {
        'Whispering Corridor (MAP06) - Armor',
        'Whispering Corridor (MAP06) - Blue skull key',
        'Whispering Corridor (MAP06) - Chainsaw',
        'Whispering Corridor (MAP06) - Exit',
        'Whispering Corridor (MAP06) - Rocket launcher',
        'Whispering Corridor (MAP06) - Super Shotgun',
    },
    'Zerstorung (MAP33)': {
        'Zerstorung (MAP33) - Armor',
        'Zerstorung (MAP33) - BFG9000',
        'Zerstorung (MAP33) - Backpack',
        'Zerstorung (MAP33) - Berserk',
        'Zerstorung (MAP33) - Blue skull key',
        'Zerstorung (MAP33) - Chaingun',
        'Zerstorung (MAP33) - Chaingun 2',
        'Zerstorung (MAP33) - Chaingun 3',
        'Zerstorung (MAP33) - Chaingun 4',
        'Zerstorung (MAP33) - Exit',
        'Zerstorung (MAP33) - Invulnerability',
        'Zerstorung (MAP33) - Megasphere',
        'Zerstorung (MAP33) - Partial invisibility',
        'Zerstorung (MAP33) - Plasma gun',
        'Zerstorung (MAP33) - Red skull key',
        'Zerstorung (MAP33) - Rocket launcher',
        'Zerstorung (MAP33) - Shotgun',
        'Zerstorung (MAP33) - Super Shotgun',
        'Zerstorung (MAP33) - Super Shotgun 2',
        'Zerstorung (MAP33) - Supercharge',
        'Zerstorung (MAP33) - Supercharge 2',
        'Zerstorung (MAP33) - Yellow skull key',
    },
    'Zombie Hideout (MAP18)': {
        'Zombie Hideout (MAP18) - Berserk',
        'Zombie Hideout (MAP18) - Blue skull key',
        'Zombie Hideout (MAP18) - Exit',
        'Zombie Hideout (MAP18) - Super Shotgun',
        'Zombie Hideout (MAP18) - Yellow skull key',
    },
}


death_logic_locations = [
]
