# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from typing import List


map_names: List[str] = [
    'The Spaceport (MAP01)',
    'Control Facility (MAP02)',
    'The Alleyway (MAP03)',
    'Canyon Hub (MAP04)',
    'Skybase 300 (MAP05)',
    'Whispering Corridor (MAP06)',
    'Heavyweight (MAP07)',
    'Waste Disposal Plant (MAP08)',
    'Nuclear Power Station (MAP09)',
    'Cargo Bay (MAP10)',
    'Simbattle (MAP11)',
    'Villa of Pain (MAP12)',
    'Dark Crypt (MAP13)',
    'The Circle (MAP14)',
    'Trouble Town (MAP15)',
    'Bruiser Fortress (MAP16)',
    'Constriction (MAP17)',
    'Zombie Hideout (MAP18)',
    'The Invasion (MAP19)',
    'Death Row (MAP20)',
    'Blood Lust (MAP21)',
    'Firestorm Tomb (MAP22)',
    'Dungeon of Inferno (MAP23)',
    'Cavern of the Evil Spirit (MAP24)',
    'Hellucination (MAP25)',
    'Valley of Brimstone (MAP26)',
    'Dissect (MAP27)',
    'Unholy Demise (MAP28)',
    'Den of Torture (MAP29)',
    'Eternal Core (MAP30)',
    'Creepy (MAP31)',
    'Condemnation (MAP32)',
    'Zerstorung (MAP33)',
]
